// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-1.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { act, renderHook, waitFor } from "@testing-library/react";

vi.mock("@/app/(roles)/rm/requests/actions", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/app/(roles)/rm/requests/actions")>()),
  getTickets: vi.fn(),
}));

import { getTickets } from "@/app/(roles)/rm/requests/actions";
import { useRmTickets } from "@/hooks/api/useRmTickets";
import type { RmTicketDTO } from "@/lib/rm/tickets";

function ok<T>(data: T) {
  return { success: true as const, data };
}
function fail(error: string, code = "NETWORK_ERROR") {
  return { success: false as const, error, code };
}

function dto(overrides: Partial<RmTicketDTO> = {}): RmTicketDTO {
  return {
    ref: "REQ-1001", client_id: "c1", client: "Ardent Capital", contact: "Marcus Lindqvist",
    email: "m@x.com", account: "IB-4471", model: "Global Balanced", kind: "allotment",
    currency: "USD", amount: 180000, multiplier: 2, subject: "Subject line",
    message: "msg", status: "new", created_at: "2026-06-06T00:00:00Z",
    responded_by: null, responded_at: null, response_note: null,
    ...overrides,
  };
}

describe("ADM-1 useRmTickets", () => {
  beforeEach(() => vi.clearAllMocks());

  it("fetches and populates mapped data on mount", async () => {
    vi.mocked(getTickets).mockResolvedValue(ok([dto()]));
    const { result } = renderHook(() => useRmTickets());
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toHaveLength(1);
    expect(result.current.data?.[0].ref).toBe("REQ-1001");
    expect(result.current.error).toBeNull();
  });

  it("a failed fetch sets error and leaves data null (the existing empty/error treatment, not a thrown error)", async () => {
    vi.mocked(getTickets).mockResolvedValue(fail("boom"));
    const { result } = renderHook(() => useRmTickets());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.error).toBe("boom");
    expect(result.current.data).toBeNull();
  });

  it("refetch() re-triggers a fetch and overwrites the data on success", async () => {
    vi.mocked(getTickets).mockResolvedValue(ok([dto()]));
    const { result } = renderHook(() => useRmTickets());
    await waitFor(() => expect(result.current.loading).toBe(false));

    vi.mocked(getTickets).mockResolvedValue(ok([dto({ ref: "REQ-1002" })]));
    await act(async () => result.current.refetch());
    await waitFor(() => expect(result.current.data?.[0].ref).toBe("REQ-1002"));
    expect(getTickets).toHaveBeenCalledTimes(2);
  });

  it("calling refetch() while a fetch is already in flight is a no-op (the inFlight guard)", async () => {
    let resolveFirst!: (v: ReturnType<typeof ok<RmTicketDTO[]>>) => void;
    vi.mocked(getTickets).mockReturnValueOnce(
      new Promise((resolve) => { resolveFirst = resolve; }),
    );
    const { result } = renderHook(() => useRmTickets());
    expect(result.current.loading).toBe(true);

    act(() => { result.current.refetch(); });
    expect(getTickets).toHaveBeenCalledTimes(1);

    await act(async () => resolveFirst(ok([dto()])));
    await waitFor(() => expect(result.current.loading).toBe(false));
  });
});
