// Generated by test-gen (standard) from docs/implementations/011-2026-07-13-post-trade-allocation-fe.md §FE-3.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { act, renderHook, waitFor } from "@testing-library/react";

vi.mock("@/app/(roles)/mobo/post-trade-allocation/actions", () => ({
  getView: vi.fn(),
  getRuns: vi.fn(),
  runSync: vi.fn(),
}));

import { getRuns, getView, runSync } from "@/app/(roles)/mobo/post-trade-allocation/actions";
import { usePostTradeAllocation, usePostTradeAllocationRuns } from "@/hooks/api/usePostTradeAllocation";
import type { PtaRunResultDTO, PtaRunsDTO, PtaViewDTO } from "@/lib/mobo/types";

function ok<T>(data: T) {
  return { success: true as const, data };
}
function fail(error: string, code = "NETWORK_ERROR") {
  return { success: false as const, error, code };
}

function dto(overrides: Partial<PtaViewDTO> = {}): PtaViewDTO {
  return { tradeDate: "2026-06-03", settleDay: "Tue 03 Jun 2026", grandTotal: 100, models: [], ...overrides };
}

// Each test uses its own trade date so the hook's module-scoped cache
// (keyed by date) never bleeds state between tests.
describe("FE-3 usePostTradeAllocation", () => {
  beforeEach(() => vi.clearAllMocks());

  it("fetches and populates data on mount", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto()));
    const { result } = renderHook(() => usePostTradeAllocation("2026-01-01"));
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toEqual({ settleDay: "Tue 03 Jun 2026", models: [], grandTotal: 100 });
    expect(getView).toHaveBeenCalledWith("2026-01-01");
  });

  it("a failed fetch sets error and leaves data null", async () => {
    vi.mocked(getView).mockResolvedValue(fail("boom"));
    const { result } = renderHook(() => usePostTradeAllocation("2026-01-02"));
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.error).toBe("boom");
    expect(result.current.data).toBeNull();
  });

  it("a second hook instance for the same date is seeded from the module cache immediately", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto({ grandTotal: 777 })));
    const { result: first } = renderHook(() => usePostTradeAllocation("2026-01-03"));
    await waitFor(() => expect(first.current.loading).toBe(false));

    const { result: second } = renderHook(() => usePostTradeAllocation("2026-01-03"));
    expect(second.current.data).toEqual(first.current.data);
  });

  it("re-fetches on window refocus", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto()));
    const { result } = renderHook(() => usePostTradeAllocation("2026-01-04"));
    await waitFor(() => expect(result.current.loading).toBe(false));
    const callsBefore = vi.mocked(getView).mock.calls.length;

    await act(async () => {
      window.dispatchEvent(new Event("focus"));
    });

    await waitFor(() => expect(vi.mocked(getView).mock.calls.length).toBeGreaterThan(callsBefore));
  });

  it("sync() on a real-run response invalidates the cache and repopulates with the fresh view", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto({ grandTotal: 100 })));
    const fresh: PtaRunResultDTO = {
      newRuns: [{ date: "2026-06-04", label: "Wed 04 Jun 2026", grandTotal: 500 }],
      latest: dto({
        grandTotal: 500,
        models: [{ id: "m1", name: "Zero", acct: "U-1", traded: 500, unitsTotal: 1, clientShares: [] }],
      }),
      checkedAt: "14:32",
    };
    vi.mocked(runSync).mockResolvedValue(ok(fresh));

    const { result } = renderHook(() => usePostTradeAllocation("2026-01-05"));
    await waitFor(() => expect(result.current.loading).toBe(false));

    // sync() invalidates the cache and re-fetches via getView (not fresh.latest directly) —
    // the post-sync refetch must see the new value.
    vi.mocked(getView).mockResolvedValue(ok(fresh.latest));

    let syncResult: { empty: boolean; checkedAt?: string; error?: string } | undefined;
    await act(async () => {
      syncResult = await result.current.sync();
    });

    expect(syncResult).toEqual({ empty: false, checkedAt: "14:32" });
    expect(result.current.data?.grandTotal).toBe(500);
  });

  it("sync() on an empty-run response resolves {empty:true} without throwing", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto()));
    const empty: PtaRunResultDTO = {
      newRuns: [{ date: "2026-06-04", label: "Wed 04 Jun 2026", grandTotal: 0 }],
      latest: dto({ models: [], grandTotal: 0 }),
      checkedAt: "15:00",
    };
    vi.mocked(runSync).mockResolvedValue(ok(empty));

    const { result } = renderHook(() => usePostTradeAllocation("2026-01-06"));
    await waitFor(() => expect(result.current.loading).toBe(false));

    let syncResult: { empty: boolean; checkedAt?: string; error?: string } | undefined;
    await act(async () => {
      syncResult = await result.current.sync();
    });
    expect(syncResult).toEqual({ empty: true, checkedAt: "15:00" });
  });

  it("a failed sync() resolves {empty:false, error} and leaves the cached data untouched", async () => {
    vi.mocked(getView).mockResolvedValue(ok(dto({ grandTotal: 42 })));
    vi.mocked(runSync).mockResolvedValue(fail("sync failed"));

    const { result } = renderHook(() => usePostTradeAllocation("2026-01-07"));
    await waitFor(() => expect(result.current.loading).toBe(false));
    const dataBefore = result.current.data;

    let syncResult: { empty: boolean; checkedAt?: string; error?: string } | undefined;
    await act(async () => {
      syncResult = await result.current.sync();
    });
    expect(syncResult).toEqual({ empty: false, error: "sync failed" });
    expect(result.current.data).toEqual(dataBefore);
  });
});

describe("FE-3 usePostTradeAllocationRuns", () => {
  beforeEach(() => vi.clearAllMocks());

  it("populates runs from getRuns() and flips loading to false", async () => {
    const runsDto: PtaRunsDTO = { runs: [{ date: "2026-06-03", label: "Tue 03 Jun 2026", grandTotal: 100 }] };
    vi.mocked(getRuns).mockResolvedValue(ok(runsDto));
    const { result } = renderHook(() => usePostTradeAllocationRuns());
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.runs).toEqual(runsDto.runs);
  });

  it("a failed getRuns() leaves runs empty and still flips loading to false", async () => {
    vi.mocked(getRuns).mockResolvedValue(fail("boom"));
    const { result } = renderHook(() => usePostTradeAllocationRuns());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.runs).toEqual([]);
  });
});
