// Generated by test-gen (standard) from docs/implementations/015-eod-exception-report-fe.md §FE-3.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { act, renderHook, waitFor } from "@testing-library/react";

vi.mock("@/app/(roles)/mobo/daily-exception-report/actions", () => ({
  getEodReport: vi.fn(),
  signOff: vi.fn(),
}));

import { getEodReport, signOff as signOffAction } from "@/app/(roles)/mobo/daily-exception-report/actions";
import { useEodReport } from "@/hooks/api/useEodReport";
import type { EodReportViewDTO } from "@/lib/mobo/eod-types";

function ok<T>(data: T) {
  return { success: true as const, data };
}
function fail(error: string, code = "NETWORK_ERROR") {
  return { success: false as const, error, code };
}

function dto(overrides: Partial<EodReportViewDTO> = {}): EodReportViewDTO {
  return {
    settleDay: "Tue 03 Jun 2026", tradeDate: "2026-06-03",
    orders: [], allocs: [], ports: [],
    algoTotal: "$0", ibTotal: "$0", crmTotal: "$0",
    counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
    status: "OPEN", signedOffBy: null, signedOffAt: null, generated: "10:02am",
    orderCount: 0, executionCount: 0, notionalTraded: "$0", breakTotal: 0,
    outcome: "CLEAR", canSignOff: true, exportReady: false,
    ...overrides,
  };
}

// Each test uses its own tradeDate so the hook's module-scoped cache
// (keyed by tradeDate ?? "__default__") never bleeds state between tests.
describe("FE-3 useEodReport", () => {
  beforeEach(() => vi.clearAllMocks());

  it("fetches and populates data on mount", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-03" })));
    const { result } = renderHook(() => useEodReport("2026-06-03"));
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data?.tradeDate).toBe("2026-06-03");
    expect(getEodReport).toHaveBeenCalledWith("2026-06-03");
  });

  it("a failed fetch sets error and leaves data null", async () => {
    vi.mocked(getEodReport).mockResolvedValue(fail("boom"));
    const { result } = renderHook(() => useEodReport("2026-06-04"));
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.error).toBe("boom");
    expect(result.current.data).toBeNull();
  });

  it("a second hook instance for the same tradeDate is seeded from the module cache immediately", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-05" })));
    const { result: first } = renderHook(() => useEodReport("2026-06-05"));
    await waitFor(() => expect(first.current.loading).toBe(false));

    const { result: second } = renderHook(() => useEodReport("2026-06-05"));
    expect(second.current.data).toEqual(first.current.data);
  });

  it("refetch() re-triggers a fetch and overwrites the cache on success", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-06", breakTotal: 1 })));
    const { result } = renderHook(() => useEodReport("2026-06-06"));
    await waitFor(() => expect(result.current.loading).toBe(false));

    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-06", breakTotal: 0 })));
    await act(async () => result.current.refetch());
    await waitFor(() => expect(result.current.data?.breakTotal).toBe(0));
    expect(getEodReport).toHaveBeenCalledTimes(2);
  });

  it("calling refetch() while a fetch is already in flight is a no-op (the inFlight guard)", async () => {
    let resolveFirst!: (v: ReturnType<typeof ok<EodReportViewDTO>>) => void;
    vi.mocked(getEodReport).mockReturnValueOnce(
      new Promise((resolve) => { resolveFirst = resolve; }),
    );
    const { result } = renderHook(() => useEodReport("2026-06-07"));
    expect(result.current.loading).toBe(true);

    act(() => { result.current.refetch(); }); // fires while the first fetch is still in flight
    expect(getEodReport).toHaveBeenCalledTimes(1); // second call was swallowed by the inFlight guard

    await act(async () => resolveFirst(ok(dto({ tradeDate: "2026-06-07" }))));
    await waitFor(() => expect(result.current.loading).toBe(false));
  });

  it("signOff() on success updates data to the returned (now-SIGNED) view and returns true", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-08", status: "OPEN" })));
    const { result } = renderHook(() => useEodReport("2026-06-08"));
    await waitFor(() => expect(result.current.loading).toBe(false));

    vi.mocked(signOffAction).mockResolvedValue(ok(dto({ tradeDate: "2026-06-08", status: "SIGNED", exportReady: true })));
    let signOffResult: boolean | undefined;
    await act(async () => { signOffResult = await result.current.signOff(); });

    expect(signOffResult).toBe(true);
    expect(signOffAction).toHaveBeenCalledWith("2026-06-08");
    expect(result.current.data?.status).toBe("SIGNED");
  });

  it("signOff() on a 409 failure sets error, leaves data unchanged, and returns false", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-09" })));
    const { result } = renderHook(() => useEodReport("2026-06-09"));
    await waitFor(() => expect(result.current.loading).toBe(false));
    const before = result.current.data;

    vi.mocked(signOffAction).mockResolvedValue(fail("already signed", "HTTP_409"));
    let signOffResult: boolean | undefined;
    await act(async () => { signOffResult = await result.current.signOff(); });

    expect(signOffResult).toBe(false);
    expect(result.current.error).toBe("already signed");
    expect(result.current.data).toBe(before);
  });

  it("signOff() sets signingOff true while in flight and false once settled", async () => {
    vi.mocked(getEodReport).mockResolvedValue(ok(dto({ tradeDate: "2026-06-10" })));
    const { result } = renderHook(() => useEodReport("2026-06-10"));
    await waitFor(() => expect(result.current.loading).toBe(false));

    let resolveSignOff!: (v: ReturnType<typeof ok<EodReportViewDTO>>) => void;
    vi.mocked(signOffAction).mockReturnValue(new Promise((resolve) => { resolveSignOff = resolve; }));

    let pending!: Promise<boolean>;
    act(() => { pending = result.current.signOff(); });
    await waitFor(() => expect(result.current.signingOff).toBe(true));

    await act(async () => { resolveSignOff(ok(dto({ tradeDate: "2026-06-10", status: "SIGNED" }))); await pending; });
    expect(result.current.signingOff).toBe(false);
  });
});
