// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-4 (hook half).
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderHook, waitFor, act } from "@testing-library/react";

vi.mock("@/app/(roles)/compliance/review/actions", () => ({
  fetchComplianceQueue: vi.fn(),
  submitVerdict: vi.fn(),
  approveOnboarding: vi.fn(),
  rejectOnboarding: vi.fn(),
  downloadDocument: vi.fn(),
}));

import * as actions from "@/app/(roles)/compliance/review/actions";
import { useComplianceQueue } from "@/hooks/api/useComplianceQueue";

describe("FE-4 useComplianceQueue", () => {
  beforeEach(() => vi.clearAllMocks());

  it("loads the queue on mount: loading true → false with data populated", async () => {
    vi.mocked(actions.fetchComplianceQueue).mockResolvedValue({ success: true, data: [] } as never);
    const { result } = renderHook(() => useComplianceQueue());
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toEqual([]);
  });

  it("a failed fetchComplianceQueue sets error and leaves data null", async () => {
    vi.mocked(actions.fetchComplianceQueue).mockResolvedValue({ success: false, error: "boom", code: "NETWORK_ERROR" } as never);
    const { result } = renderHook(() => useComplianceQueue());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toBeNull();
    expect(result.current.error).toBe("boom");
  });

  it("submitVerdict()/approve()/reject() each trigger a refetch on success", async () => {
    vi.mocked(actions.fetchComplianceQueue).mockResolvedValue({ success: true, data: [] } as never);
    vi.mocked(actions.submitVerdict).mockResolvedValue({ success: true, data: {} } as never);
    vi.mocked(actions.approveOnboarding).mockResolvedValue({ success: true, data: {} } as never);
    vi.mocked(actions.rejectOnboarding).mockResolvedValue({ success: true, data: {} } as never);
    const { result } = renderHook(() => useComplianceQueue());
    await waitFor(() => expect(result.current.loading).toBe(false));

    await act(async () => { await result.current.submitVerdict("ob-1", "passport", "valid"); });
    await act(async () => { await result.current.approve("ob-1"); });
    await act(async () => { await result.current.reject("ob-1", "bad scan"); });

    expect(actions.fetchComplianceQueue).toHaveBeenCalledTimes(4); // 1 mount + 3 mutations
  });

  it("download() does NOT trigger a refetch (read-only) and returns the file payload on success", async () => {
    vi.mocked(actions.fetchComplianceQueue).mockResolvedValue({ success: true, data: [] } as never);
    vi.mocked(actions.downloadDocument).mockResolvedValue({
      success: true, data: { filename: "passport.pdf", contentType: "application/pdf", base64: "abc" },
    } as never);
    const { result } = renderHook(() => useComplianceQueue());
    await waitFor(() => expect(result.current.loading).toBe(false));

    const out = await result.current.download("ob-1", "passport");
    expect(out).toEqual({ success: true, filename: "passport.pdf", contentType: "application/pdf", base64: "abc" });
    expect(actions.fetchComplianceQueue).toHaveBeenCalledTimes(1); // no extra refetch
  });

  it("a failed approve() surfaces error without mutating data optimistically", async () => {
    vi.mocked(actions.fetchComplianceQueue).mockResolvedValue({ success: true, data: [] } as never);
    vi.mocked(actions.approveOnboarding).mockResolvedValue({ success: false, error: "not all verified" } as never);
    const { result } = renderHook(() => useComplianceQueue());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const out = await result.current.approve("ob-1");
    expect(out).toEqual({ success: false, error: "not all verified" });
    expect(actions.fetchComplianceQueue).toHaveBeenCalledTimes(1);
  });
});
