// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-5 (hook half).
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { renderHook, waitFor, act } from "@testing-library/react";

vi.mock("@/app/(roles)/pc/allotment-redemption/actions", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/app/(roles)/pc/allotment-redemption/actions")>()),
  fetchAllotments: vi.fn(),
  acknowledgeAllotment: vi.fn(),
}));

import * as actions from "@/app/(roles)/pc/allotment-redemption/actions";
import { useAllotments } from "@/hooks/api/useAllotments";

describe("FE-5 useAllotments", () => {
  beforeEach(() => vi.clearAllMocks());

  it("loads allotments on mount: loading true → false with data populated", async () => {
    vi.mocked(actions.fetchAllotments).mockResolvedValue({ success: true, data: [] } as never);
    const { result } = renderHook(() => useAllotments());
    expect(result.current.loading).toBe(true);
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toEqual([]);
  });

  it("a failed fetchAllotments sets error and leaves data null", async () => {
    vi.mocked(actions.fetchAllotments).mockResolvedValue({ success: false, error: "boom", code: "NETWORK_ERROR" } as never);
    const { result } = renderHook(() => useAllotments());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toBeNull();
    expect(result.current.error).toBe("boom");
  });

  it("acknowledge() triggers a refetch on success", async () => {
    vi.mocked(actions.fetchAllotments).mockResolvedValue({ success: true, data: [] } as never);
    vi.mocked(actions.acknowledgeAllotment).mockResolvedValue({ success: true, data: {} } as never);
    const { result } = renderHook(() => useAllotments());
    await waitFor(() => expect(result.current.loading).toBe(false));
    await act(async () => { await result.current.acknowledge("al-1"); });
    expect(actions.fetchAllotments).toHaveBeenCalledTimes(2);
  });

  it("a failed acknowledge() surfaces error without refetching", async () => {
    vi.mocked(actions.fetchAllotments).mockResolvedValue({ success: true, data: [] } as never);
    vi.mocked(actions.acknowledgeAllotment).mockResolvedValue({ success: false, error: "already acknowledged" } as never);
    const { result } = renderHook(() => useAllotments());
    await waitFor(() => expect(result.current.loading).toBe(false));
    const out = await result.current.acknowledge("al-1");
    expect(out).toEqual({ success: false, error: "already acknowledged" });
    expect(actions.fetchAllotments).toHaveBeenCalledTimes(1);
  });
});
