// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-2 (Compliance half).
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/onboarding", () => ({
  fetchComplianceQueue: vi.fn(),
  submitVerdict: vi.fn(),
  approveOnboarding: vi.fn(),
  rejectOnboarding: vi.fn(),
  downloadDocument: vi.fn(),
}));

import * as serverOnboarding from "@/server/onboarding";
import {
  fetchComplianceQueue, submitVerdict, approveOnboarding, rejectOnboarding, downloadDocument,
} from "@/app/(roles)/compliance/review/actions";

describe("FE-2 Compliance action wrappers", () => {
  beforeEach(() => vi.clearAllMocks());

  it("fetchComplianceQueue() calls the FE-1 function and returns its success result verbatim", async () => {
    const ok = { success: true, data: [] };
    vi.mocked(serverOnboarding.fetchComplianceQueue).mockResolvedValue(ok as never);
    const result = await fetchComplianceQueue();
    expect(serverOnboarding.fetchComplianceQueue).toHaveBeenCalled();
    expect(result).toBe(ok);
  });

  it("submitVerdict(id, docType, body) forwards all three args unchanged", async () => {
    const ok = { success: true, data: { doc_type: "passport", status: "verified" } };
    vi.mocked(serverOnboarding.submitVerdict).mockResolvedValue(ok as never);
    const body = { verdict: "valid" as const, note: null };
    const result = await submitVerdict("ob-1", "passport", body);
    expect(serverOnboarding.submitVerdict).toHaveBeenCalledWith("ob-1", "passport", body);
    expect(result).toBe(ok);
  });

  it("approveOnboarding(id) converts a thrown error into ACTION_ERROR instead of propagating", async () => {
    vi.mocked(serverOnboarding.approveOnboarding).mockRejectedValue(new Error("not all docs verified"));
    const result = await approveOnboarding("ob-1");
    expect(result).toEqual({ success: false, error: "not all docs verified", code: "ACTION_ERROR" });
  });

  it("rejectOnboarding(id, body) forwards body unchanged", async () => {
    const ok = { success: true, data: { status: "pending_review" } };
    vi.mocked(serverOnboarding.rejectOnboarding).mockResolvedValue(ok as never);
    const result = await rejectOnboarding("ob-1", { reason: "bad scan" });
    expect(serverOnboarding.rejectOnboarding).toHaveBeenCalledWith("ob-1", { reason: "bad scan" });
    expect(result).toBe(ok);
  });

  it("downloadDocument(id, docType) passes a failure result through untouched", async () => {
    const err = { success: false, error: "Not Found", code: "HTTP_404" };
    vi.mocked(serverOnboarding.downloadDocument).mockResolvedValue(err as never);
    const result = await downloadDocument("ob-1", "passport");
    expect(result).toBe(err);
  });
});
