# Generated by test-gen (thorough) from
# docs/implementations/016-allotment-redemption-integration-be.md §BE-3.
# Regenerate: /test-gen thorough docs/implementations/016-allotment-redemption-integration-be.md
#
# Seam mocks: none per §8.3 -- exercises OnboardingService.submit_redemption
# directly against the in-memory SQLite session fixture.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/onboarding/test_be3_submit_redemption.py

from __future__ import annotations

import uuid
from datetime import date, timedelta
from decimal import Decimal

import pytest
from fastapi import HTTPException

from app.libs.onboarding.schemas import SubmitRedemptionReq
from app.libs.onboarding.service import OnboardingService
from app.models.onboarding import AllotRdmpKind, AllotRdmpStatus
from app.models.pc import ClientSubscription
from app.models.post_trade_allocation import ClientPortfolio

from tests.libs.onboarding.conftest import make_client, make_model, make_portfolio, make_subscription


# --- Positive: $300k boundary routing ($300,000 model_size=1 for cent-exact math) ------


def test_redemption_exactly_300k_routes_to_awaiting_pc(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("500000"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("300000"))
    dto = svc.submit_redemption(req)

    assert dto.status == "awaiting_pc"


def test_redemption_one_dollar_above_300k_routes_to_awaiting_co(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("500000"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("300001"))
    dto = svc.submit_redemption(req)

    assert dto.status == "awaiting_co"


# --- Positive: emergent flag (D-3) -----------------------------------------------------


def test_emergent_redeems_full_current_subscription_regardless_of_requested_multiplier(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("7"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(
        client_id=client.id, model_id=model.id, multiplier=Decimal("1"), emergent=True
    )
    dto = svc.submit_redemption(req)

    allotment = svc.repo.get_allotment(dto.id)
    assert allotment.multiplier == Decimal("7")
    assert allotment.emergent is True


def test_emergent_forces_expected_cash_out_to_t_plus_1_regardless_of_requested_date(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("7"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    far_future = date.today() + timedelta(days=90)
    req = SubmitRedemptionReq(
        client_id=client.id,
        model_id=model.id,
        multiplier=Decimal("1"),
        expected_cash_out=far_future,
        emergent=True,
    )
    dto = svc.submit_redemption(req)

    allotment = svc.repo.get_allotment(dto.id)
    expected = date.today() + timedelta(days=1)
    assert allotment.expected_cash_out.date() == expected


def test_emergent_does_not_bypass_either_approval_gate(session):
    """D-3: no bypass -- an emergent redemption above $300k still lands in
    awaiting_co, not some emergent-only fast lane."""
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("500000"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(
        client_id=client.id, model_id=model.id, multiplier=Decimal("1"), emergent=True
    )
    dto = svc.submit_redemption(req)
    assert dto.status == "awaiting_co"  # full sub (500000) * 1 > 300000


# --- Negative ---------------------------------------------------------------------------


def test_redemption_exceeding_current_subscription_raises_422(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("5"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("6"))
    with pytest.raises(HTTPException) as exc:
        svc.submit_redemption(req)
    assert exc.value.status_code == 422


def test_redemption_with_no_subscription_raises_404(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("1"))
    with pytest.raises(HTTPException) as exc:
        svc.submit_redemption(req)
    assert exc.value.status_code == 404


def test_redemption_against_a_zero_unit_subscription_raises_422(session):
    """A fully-redeemed subscription is never deleted -- multiplier is floored
    at 0, not the row (see _execute_redemption_approval). `sub is None` no
    longer catches this case, so it needs its own guard, distinct from the
    404 "never subscribed at all" case below."""
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("0"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("1"))
    with pytest.raises(HTTPException) as exc:
        svc.submit_redemption(req)
    assert exc.value.status_code == 422
    assert "No units remaining" in exc.value.detail


def test_emergent_redemption_against_a_zero_unit_subscription_raises_422(session):
    """Without this guard, emergent's `multiplier = sub.multiplier` (already 0)
    would sail a no-op redemption through the whole CO/PC approval chain."""
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("0"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(
        client_id=client.id, model_id=model.id, multiplier=Decimal("1"), emergent=True
    )
    with pytest.raises(HTTPException) as exc:
        svc.submit_redemption(req)
    assert exc.value.status_code == 422
    assert "No units remaining" in exc.value.detail


def test_unknown_model_id_raises_422(session):
    client = make_client(session)
    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=uuid.uuid4(), multiplier=Decimal("1"))
    with pytest.raises(HTTPException) as exc:
        svc.submit_redemption(req)
    assert exc.value.status_code == 422


# --- Invariants: no subscription/portfolio write on submit -----------------------------


@pytest.mark.parametrize("emergent", [False, True])
@pytest.mark.parametrize("multiplier", [Decimal("300000"), Decimal("300001")])
def test_submit_never_touches_subscription_or_portfolio(session, multiplier, emergent):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("500000"))
    make_portfolio(
        session,
        client,
        cash_deposit=Decimal("123"),
        amount_in_trade=Decimal("456"),
        previous_amount_in_trade=Decimal("789"),
    )
    session.expire_all()

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(
        client_id=client.id, model_id=model.id, multiplier=multiplier, emergent=emergent
    )
    svc.submit_redemption(req)

    sub = session.get(ClientSubscription, (client.id, model.id))
    assert sub.multiplier == Decimal("500000")
    portfolio = session.get(ClientPortfolio, client.id)
    assert portfolio.cash_deposit == Decimal("123")
    assert portfolio.amount_in_trade == Decimal("456")
    assert portfolio.previous_amount_in_trade == Decimal("789")


def test_submit_inserts_exactly_one_allotment_row_and_one_event(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("5"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    req = SubmitRedemptionReq(client_id=client.id, model_id=model.id, multiplier=Decimal("2"))
    dto = svc.submit_redemption(req)

    allotment = svc.repo.get_allotment(dto.id)
    assert allotment.kind == AllotRdmpKind.REDEMPTION
    assert allotment.status in (AllotRdmpStatus.AWAITING_PC, AllotRdmpStatus.AWAITING_CO)

    from app.models.onboarding import ClientEvent

    events = session.query(ClientEvent).filter(ClientEvent.user_id == client.id).all()
    assert len(events) == 1


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
