# Generated by test-gen (standard) from
# docs/implementations/014-onboarding-follow-up-fixes-be.md §BE-2.
# Regenerate: /test-gen standard docs/implementations/014-onboarding-follow-up-fixes-be.md
#
# RM-scoped single-document download route -- byte-for-byte mirror of the
# existing compliance download route, gated by ONBOARDING_MANAGE instead of
# ONBOARDING_REVIEW. Seam mocks: none -- real app.main.app + TestClient +
# dependency-override for auth, following tests/libs/onboarding/test_be6_router.py's
# precedent.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/onboarding/test_014_be2_rm_download_route.py

from __future__ import annotations

import io
import uuid
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.config import Settings, get_settings
from app.core.database import Base, get_db
from app.libs.auth.deps import get_current_admin_user
from app.main import app
from app.models.pc import Model
from app.models.users import AdminProfile, AdminRole
from tests.conftest import make_admin_stub
from tests.libs.onboarding.conftest import FakeStorage


@pytest.fixture
def db_factory():
    engine = create_engine(
        "sqlite:///:memory:", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine, expire_on_commit=False)


@pytest.fixture
def fake_storage(monkeypatch):
    storage = FakeStorage()
    monkeypatch.setattr("app.libs.onboarding.service.get_storage", lambda bucket: storage)
    return storage


@pytest.fixture
def admin_client(db_factory, fake_storage):
    def _override_get_db():
        db = db_factory()
        try:
            yield db
        finally:
            db.close()

    stub_user = make_admin_stub(
        db_factory, role=AdminRole.RM, firebase_uid="uid-be2-router-test", email="rm@example.com"
    )

    app.dependency_overrides[get_db] = _override_get_db
    app.dependency_overrides[get_settings] = lambda: Settings(firebase_auth_disabled=True)
    app.dependency_overrides[get_current_admin_user] = lambda: stub_user

    def _set_role(role: AdminRole):
        db = db_factory()
        db.query(AdminProfile).filter_by(user_id=stub_user.id).update({"role": role})
        db.commit()
        db.close()
        # BE-2: admin_profile is loaded eagerly on stub_user (make_admin_stub) -- keep
        # the cached relationship in sync with the row this function just changed.
        stub_user.admin_profile.role = role

    try:
        yield TestClient(app), db_factory, _set_role
    finally:
        app.dependency_overrides.clear()


def _seed_model(db_factory) -> uuid.UUID:
    db = db_factory()
    model = Model(
        id=uuid.uuid4(), name="Alpha Model", model_size=Decimal("1000000"),
        mgmt_fee=Decimal("0.02"), incentive_fee=Decimal("0.2"),
    )
    db.add(model)
    db.commit()
    model_id = model.id
    db.close()
    return model_id


def _start_and_upload_one_doc(http, model_id) -> str:
    body = {
        "client_name": "Cathy Client", "email": "cathy@example.com", "primary_phone": "1",
        "address": "A", "country_of_residence": "HK", "id_type": "Passport", "id_number": "P1",
        "ibhk_account": "IB1", "sw_account": "SW1", "model_id": str(model_id), "units": "5",
        "mgmt_fee": "0.02", "incentive_fee": "0.2", "initial_cash_deposit": "5000000",
    }
    onboarding_id = http.post("/api/rm/onboardings", json=body).json()["id"]
    http.post(
        f"/api/rm/onboardings/{onboarding_id}/documents/identity_proof",
        files={"file": ("id.pdf", io.BytesIO(b"kyc bytes"), "application/pdf")},
    )
    return onboarding_id


# --- Positive ------------------------------------------------------------------------


def test_rm_download_route_returns_same_bytes_the_compliance_route_would(admin_client):
    http, db_factory, set_role = admin_client
    model_id = _seed_model(db_factory)
    onboarding_id = _start_and_upload_one_doc(http, model_id)

    resp = http.get(f"/api/rm/onboardings/{onboarding_id}/documents/identity_proof/download")
    assert resp.status_code == 200, resp.text
    assert resp.content == b"kyc bytes"

    set_role(AdminRole.COMPLIANCE)
    compliance_resp = http.get(
        f"/api/compliance/onboardings/{onboarding_id}/documents/identity_proof/download"
    )
    assert compliance_resp.content == resp.content


# --- Negative --------------------------------------------------------------------------


def test_rm_download_route_403_for_compliance_only_caller(admin_client):
    http, db_factory, set_role = admin_client
    model_id = _seed_model(db_factory)
    onboarding_id = _start_and_upload_one_doc(http, model_id)
    set_role(AdminRole.COMPLIANCE)

    resp = http.get(f"/api/rm/onboardings/{onboarding_id}/documents/identity_proof/download")
    assert resp.status_code == 403


def test_rm_download_route_404_when_no_file_uploaded(admin_client):
    http, db_factory, _set_role = admin_client
    model_id = _seed_model(db_factory)
    body = {
        "client_name": "Cathy Client", "email": "no-doc@example.com", "primary_phone": "1",
        "address": "A", "country_of_residence": "HK", "id_type": "Passport", "id_number": "P1",
        "ibhk_account": "IB1", "sw_account": "SW1", "model_id": str(model_id), "units": "5",
        "mgmt_fee": "0.02", "incentive_fee": "0.2", "initial_cash_deposit": "5000000",
    }
    onboarding_id = http.post("/api/rm/onboardings", json=body).json()["id"]

    resp = http.get(f"/api/rm/onboardings/{onboarding_id}/documents/identity_proof/download")
    assert resp.status_code == 404


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
