# Generated by test-gen (thorough) from
# docs/implementations/013-client-onboarding-integration-be.md §BE-7.
# Regenerate: /test-gen thorough docs/implementations/013-client-onboarding-integration-be.md
#
# Renewal scheduler. Per §8.3, `reopen_for_renewal` is NOT mocked -- this
# unit tests the real call chain -- only the tick's `asyncio.sleep` loop is
# bypassed, either by calling `_trigger_due_renewals()` directly (the doc's
# own recommended shortcut) or, for the tick-loop-shape tests, by faking the
# `asyncio` name inside scheduler.py (mirrors
# tests/libs/post_trade_allocation/test_be8_scheduler.py's own precedent).
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/onboarding/test_be7_scheduler.py

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timedelta
from decimal import Decimal

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base
from app.libs.onboarding import scheduler as sched
from app.libs.onboarding.repository import OnboardingRepository
from app.models.onboarding import ClientOnboarding, OnboardingStatus
from app.models.pc import ClientSubscription
from app.models.users import User
from tests.libs.onboarding.conftest import make_client, make_model
from tests.libs.onboarding.conftest import make_ib as _ib


class _FakeAsyncioNamespace:
    """Stands in for the `asyncio` name inside scheduler.py only -- the real
    asyncio module elsewhere (including this test's own asyncio.run) is
    untouched, matching test_be8_scheduler.py's precedent exactly."""

    CancelledError = asyncio.CancelledError

    @staticmethod
    def create_task(coro, name=None):
        return asyncio.create_task(coro)

    @staticmethod
    async def sleep(_seconds):
        return None


@pytest.fixture
def db_session_factory(monkeypatch):
    engine = create_engine(
        "sqlite:///:memory:", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False)

    import app.core.database as db_module

    monkeypatch.setattr(db_module, "SessionLocal", Session)
    return Session


def _seed_active_cycle_with_due_doc(Session, *, expires_in_days: int):
    db = Session()
    model = make_model(db)
    client = make_client(db)
    repo = OnboardingRepository(db)
    onboarding = repo.create_cycle(
        user_id=client.id,
        model_id=model.id,
        units=Decimal("5"),
        mgmt_fee=Decimal("0.02"),
        incentive_fee=Decimal("0.2"),
        client_ib=_ib(),
        sw_account="SW1",
        id_type="Passport",
        id_number="P1",
    )
    onboarding.status = OnboardingStatus.ACTIVE
    db.commit()
    docs = repo.documents_for(onboarding.id)
    due_doc, other_doc = docs[0], docs[1]
    due_doc.status = "verified"
    due_doc.expires_at = datetime.utcnow() + timedelta(days=expires_in_days)
    other_doc.status = "verified"
    other_doc.expires_at = None  # non-periodic-review doc: no expiry at all
    db.commit()
    ids = (onboarding.id, client.id, due_doc.id, other_doc.id)
    db.close()
    return ids


# --- _trigger_due_renewals(): reopens exactly the due client(s) --------------------


def test_trigger_due_renewals_reopens_a_cycle_with_a_doc_inside_the_lookahead_window(
    db_session_factory,
):
    onboarding_id, _client_id, due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=10
    )

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        from app.models.onboarding import OnboardingDocument

        onboarding = db.get(ClientOnboarding, onboarding_id)
        assert onboarding.kind == "renewal"
        assert onboarding.status == "pending_review"
        due_doc = db.get(OnboardingDocument, due_doc_id)
        assert due_doc.status == "pending"
    finally:
        db.close()


def test_trigger_due_renewals_leaves_a_doc_outside_the_lookahead_window_untouched(
    db_session_factory,
):
    onboarding_id, _client_id, _due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=60
    )

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        onboarding = db.get(ClientOnboarding, onboarding_id)
        assert onboarding.kind == "initial"
        assert onboarding.status == "active"
    finally:
        db.close()


def test_trigger_due_renewals_leaves_the_non_periodic_doc_verified(db_session_factory):
    _onboarding_id, _client_id, _due_doc_id, other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=10
    )

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        from app.models.onboarding import OnboardingDocument

        other_doc = db.get(OnboardingDocument, other_doc_id)
        assert other_doc.status == "verified"  # untouched -- it has no expires_at at all
    finally:
        db.close()


def test_trigger_due_renewals_reopens_multiple_due_clients_in_one_call(db_session_factory):
    ids_a = _seed_active_cycle_with_due_doc(db_session_factory, expires_in_days=5)
    ids_b = _seed_active_cycle_with_due_doc(db_session_factory, expires_in_days=15)

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        onboarding_a = db.get(ClientOnboarding, ids_a[0])
        onboarding_b = db.get(ClientOnboarding, ids_b[0])
        assert onboarding_a.status == "pending_review"
        assert onboarding_b.status == "pending_review"
    finally:
        db.close()


# --- Negative: a cycle already off "active" (renewal in flight) is skipped ---------


def test_trigger_due_renewals_skips_a_cycle_not_currently_active(db_session_factory):
    onboarding_id, _client_id, _due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=5
    )
    db = db_session_factory()
    onboarding = db.get(ClientOnboarding, onboarding_id)
    onboarding.status = "pending_review"  # already mid-renewal from a prior tick
    onboarding.compl_note = "existing renewal in flight"
    db.commit()
    db.close()

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        onboarding = db.get(ClientOnboarding, onboarding_id)
        assert onboarding.compl_note == "existing renewal in flight"  # untouched
    finally:
        db.close()


def test_trigger_due_renewals_called_twice_is_idempotent(db_session_factory):
    onboarding_id, _client_id, _due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=5
    )

    asyncio.run(sched._trigger_due_renewals())
    db = db_session_factory()
    onboarding = db.get(ClientOnboarding, onboarding_id)
    first_compl_note = onboarding.compl_note
    db.close()

    asyncio.run(sched._trigger_due_renewals())  # second call: cycle is no longer "active"

    db = db_session_factory()
    try:
        onboarding = db.get(ClientOnboarding, onboarding_id)
        assert onboarding.compl_note == first_compl_note  # not re-stamped a second time
        assert onboarding.status == "pending_review"  # still exactly one transition, not two
    finally:
        db.close()


# --- Invariant: users/client_subscriptions/client_allotment_redemptions untouched ---


def test_trigger_due_renewals_never_touches_users_status_or_subscriptions_or_allotments(
    db_session_factory,
):
    onboarding_id, client_id, _due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=5
    )
    db = db_session_factory()
    before_user_status = db.get(User, client_id).status
    before_sub_count = db.query(ClientSubscription).count()
    before_onboarding = db.get(ClientOnboarding, onboarding_id)
    before_multiplier = before_onboarding.multiplier
    db.close()

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        assert db.get(User, client_id).status == before_user_status
        assert db.query(ClientSubscription).count() == before_sub_count
        assert db.get(ClientOnboarding, onboarding_id).multiplier == before_multiplier
    finally:
        db.close()


def test_trigger_due_renewals_with_no_due_documents_is_a_pure_noop(db_session_factory):
    db = db_session_factory()
    model = make_model(db)
    client = make_client(db)
    repo = OnboardingRepository(db)
    onboarding = repo.create_cycle(
        user_id=client.id,
        model_id=model.id,
        units=Decimal("1"),
        mgmt_fee=Decimal("0.02"),
        incentive_fee=Decimal("0.2"),
        client_ib=_ib(),
        sw_account="SW1",
        id_type="Passport",
        id_number="P1",
    )
    onboarding.status = OnboardingStatus.ACTIVE
    db.commit()
    onboarding_id = onboarding.id
    db.close()

    asyncio.run(sched._trigger_due_renewals())  # no expires_at ever set on any doc

    db = db_session_factory()
    try:
        assert db.get(ClientOnboarding, onboarding_id).status == "active"
    finally:
        db.close()


# --- _RENEWAL_LOOKAHEAD_DAYS: default + boundary --------------------------------------


def test_renewal_lookahead_days_defaults_to_thirty():
    assert sched._RENEWAL_LOOKAHEAD_DAYS == 30


def test_smaller_monkeypatched_lookahead_excludes_a_doc_that_the_default_would_include(
    monkeypatch, db_session_factory
):
    onboarding_id, _client_id, _due_doc_id, _other_doc_id = _seed_active_cycle_with_due_doc(
        db_session_factory, expires_in_days=25
    )
    monkeypatch.setattr(sched, "_RENEWAL_LOOKAHEAD_DAYS", 10)

    asyncio.run(sched._trigger_due_renewals())

    db = db_session_factory()
    try:
        onboarding = db.get(ClientOnboarding, onboarding_id)
        assert onboarding.status == "active"  # 25 days > the monkeypatched 10-day window
    finally:
        db.close()


# --- start_scheduler() -------------------------------------------------------------


def test_start_scheduler_returns_an_asyncio_task(monkeypatch):
    monkeypatch.setattr(sched, "asyncio", _FakeAsyncioNamespace())

    async def _run():
        task = sched.start_scheduler()
        assert isinstance(task, asyncio.Task)
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

    asyncio.run(_run())


# --- Tick loop shape: fires each tick, logs (not raises) on unexpected error --------


def test_renewal_check_job_calls_trigger_due_renewals_every_tick(monkeypatch):
    monkeypatch.setattr(sched, "asyncio", _FakeAsyncioNamespace())
    calls = []

    async def _fake_trigger():
        calls.append(1)
        if len(calls) >= 2:
            raise asyncio.CancelledError("ending test loop")

    monkeypatch.setattr(sched, "_trigger_due_renewals", _fake_trigger)

    with pytest.raises(asyncio.CancelledError):
        asyncio.run(sched._renewal_check_job())

    assert calls == [1, 1]


def test_renewal_check_job_tick_exception_is_logged_not_raised(monkeypatch, caplog):
    monkeypatch.setattr(sched, "asyncio", _FakeAsyncioNamespace())
    calls = []

    async def _boom_then_cancel():
        calls.append(1)
        if len(calls) == 1:
            raise RuntimeError("boom")
        raise asyncio.CancelledError("ending test loop")

    monkeypatch.setattr(sched, "_trigger_due_renewals", _boom_then_cancel)

    with caplog.at_level(logging.ERROR):
        with pytest.raises(asyncio.CancelledError):
            asyncio.run(sched._renewal_check_job())

    assert "unexpected error in tick" in caplog.text
    assert calls == [1, 1]  # the tick after the boom still ran -- error didn't kill the loop


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
