# Generated by test-gen (standard) from
# docs/implementations/014-onboarding-follow-up-fixes-be.md §BE-7.
# Regenerate: /test-gen standard docs/implementations/014-onboarding-follow-up-fixes-be.md
#
# GET /rm/onboardings/by-client/{client_id} and GET /rm/clients/{client_id}/events --
# thin RM-scoped re-exposure of existing onboarding lookups by client_id instead
# of the caller's own token. Seam mocks: none -- real app.main.app + TestClient,
# same pattern as test_014_be2_rm_download_route.py.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/onboarding/test_014_be7_by_client_routes.py

from __future__ import annotations

import uuid
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.config import Settings, get_settings
from app.core.database import Base, get_db
from app.libs.auth.deps import get_current_admin_user
from app.main import app
from app.models.pc import Model
from app.models.users import AdminRole
from tests.conftest import make_admin_stub
from tests.libs.onboarding.conftest import FakeStorage


@pytest.fixture
def db_factory():
    engine = create_engine(
        "sqlite:///:memory:", connect_args={"check_same_thread": False}, poolclass=StaticPool
    )
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine, expire_on_commit=False)


@pytest.fixture
def fake_storage(monkeypatch):
    storage = FakeStorage()
    monkeypatch.setattr("app.libs.onboarding.service.get_storage", lambda: storage)
    return storage


@pytest.fixture
def admin_client(db_factory, fake_storage):
    def _override_get_db():
        db = db_factory()
        try:
            yield db
        finally:
            db.close()

    stub_user = make_admin_stub(
        db_factory, role=AdminRole.RM, firebase_uid="uid-be7-router-test", email="rm@example.com"
    )

    app.dependency_overrides[get_db] = _override_get_db
    app.dependency_overrides[get_settings] = lambda: Settings(firebase_auth_disabled=True)
    app.dependency_overrides[get_current_admin_user] = lambda: stub_user

    try:
        yield TestClient(app), db_factory
    finally:
        app.dependency_overrides.clear()


def _seed_model(db_factory) -> uuid.UUID:
    db = db_factory()
    model = Model(
        id=uuid.uuid4(), name="Alpha Model", model_size=Decimal("1000000"),
        mgmt_fee=Decimal("0.02"), incentive_fee=Decimal("0.2"),
    )
    db.add(model)
    db.commit()
    model_id = model.id
    db.close()
    return model_id


def _start_onboarding(http, model_id) -> dict:
    body = {
        "client_name": "Cathy Client", "email": "cathy@example.com", "primary_phone": "1",
        "address": "A", "country_of_residence": "HK", "id_type": "Passport", "id_number": "P1",
        "ibhk_account": "IB1", "sw_account": "SW1", "model_id": str(model_id), "units": "5",
        "mgmt_fee": "0.02", "incentive_fee": "0.2", "initial_cash_deposit": "5000000",
    }
    return http.post("/api/rm/onboardings", json=body).json()


# --- by-client onboarding route: positive -------------------------------------------


def test_get_onboarding_by_client_matches_the_token_scoped_route_for_the_same_client(admin_client):
    http, db_factory = admin_client
    model_id = _seed_model(db_factory)
    started = _start_onboarding(http, model_id)

    by_id = http.get(f"/api/rm/onboardings/{started['id']}")
    by_client = http.get(f"/api/rm/onboardings/by-client/{started['user_id']}")
    assert by_client.status_code == 200, by_client.text
    assert by_client.json() == by_id.json()


def test_get_onboarding_by_client_404s_for_a_client_with_no_onboarding_row(admin_client):
    http, _db_factory = admin_client
    resp = http.get(f"/api/rm/onboardings/by-client/{uuid.uuid4()}")
    assert resp.status_code == 404


# --- by-client events route ----------------------------------------------------------


def test_get_client_events_rm_returns_the_same_rows_the_clients_own_token_would(admin_client):
    http, db_factory = admin_client
    model_id = _seed_model(db_factory)
    started = _start_onboarding(http, model_id)

    resp = http.get(f"/api/rm/clients/{started['user_id']}/events")
    assert resp.status_code == 200, resp.text
    assert resp.json() == []  # no events yet -- onboarding not yet approved


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
