# Generated by test-gen (thorough) from
# docs/implementations/016-allotment-redemption-integration-be.md §BE-5.
# Regenerate: /test-gen thorough docs/implementations/016-allotment-redemption-integration-be.md
#
# Seam mocks: none per §8.3. Redemption rows are built directly via
# OnboardingRepository.create_allotment (BE-2's widened contract), same
# approach as test_be4_pc_decide.py, to isolate BE-5's own decide logic.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/onboarding/test_be5_co_decide.py

from __future__ import annotations

from decimal import Decimal

import pytest
from fastapi import HTTPException

from app.libs.onboarding.schemas import RedemptionDecisionReq
from app.libs.onboarding.service import OnboardingService
from app.models.onboarding import AllotRdmpKind, AllotRdmpStatus
from app.models.pc import ClientSubscription
from app.models.post_trade_allocation import ClientPortfolio

from tests.libs.onboarding.conftest import make_client, make_model, make_portfolio, make_subscription


def _make_redemption_row(svc, *, client, model, multiplier, status):
    return svc.repo.create_allotment(
        user_id=client.id,
        model_id=model.id,
        multiplier=multiplier,
        agg_before=Decimal("0"),
        agg_after=Decimal("0") - multiplier,
        kind=AllotRdmpKind.REDEMPTION,
        status=status,
        note="redemption",
    )


# --- Positive: reject --------------------------------------------------------------------


def test_reject_on_awaiting_co_sets_terminal_fields_no_side_effects(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))
    make_portfolio(session, client, cash_deposit=Decimal("100"), amount_in_trade=Decimal("50"))

    svc = OnboardingService(session)
    row = _make_redemption_row(
        svc, client=client, model=model, multiplier=Decimal("3"), status=AllotRdmpStatus.AWAITING_CO
    )
    session.commit()

    dto = svc.co_decide_redemption(
        row.id, RedemptionDecisionReq(verdict="reject", reason="policy breach"), decided_by="co-uid"
    )

    assert dto.status == "rejected"
    fresh = svc.repo.get_allotment(row.id)
    assert fresh.reject_reason == "policy breach"
    assert fresh.decided_by == "co-uid"
    assert fresh.decided_at is not None

    sub = session.get(ClientSubscription, (client.id, model.id))
    assert sub.multiplier == Decimal("10")
    portfolio = session.get(ClientPortfolio, client.id)
    assert portfolio.cash_deposit == Decimal("100")
    assert portfolio.amount_in_trade == Decimal("50")


# --- Positive: approve hands off to awaiting_pc, non-terminal -----------------------------


def test_approve_on_awaiting_co_hands_off_to_awaiting_pc_only(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))
    make_portfolio(session, client, cash_deposit=Decimal("100"), amount_in_trade=Decimal("50"))

    svc = OnboardingService(session)
    row = _make_redemption_row(
        svc, client=client, model=model, multiplier=Decimal("3"), status=AllotRdmpStatus.AWAITING_CO
    )
    session.commit()

    dto = svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="approve"), decided_by="co-uid")

    assert dto.status == "awaiting_pc"
    fresh = svc.repo.get_allotment(row.id)
    assert fresh.decided_by is None
    assert fresh.decided_at is None

    sub = session.get(ClientSubscription, (client.id, model.id))
    assert sub.multiplier == Decimal("10")
    portfolio = session.get(ClientPortfolio, client.id)
    assert portfolio.cash_deposit == Decimal("100")
    assert portfolio.amount_in_trade == Decimal("50")


# --- Positive: full two-gate sequence (CO approve -> PC approve) -------------------------


def test_full_sequence_co_approve_then_pc_approve_reaches_approved_with_pc_as_final_decider(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))

    svc = OnboardingService(session)
    row = _make_redemption_row(
        svc, client=client, model=model, multiplier=Decimal("3"), status=AllotRdmpStatus.AWAITING_CO
    )
    session.commit()

    svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="approve"), decided_by="co-uid")
    dto = svc.pc_decide_redemption(
        row.id, RedemptionDecisionReq(verdict="approve"), decided_by="pc-uid"
    )

    assert dto.status == "approved"
    fresh = svc.repo.get_allotment(row.id)
    assert fresh.decided_by == "pc-uid"  # the FINAL decider, not CO's uid

    sub = session.get(ClientSubscription, (client.id, model.id))
    assert sub.multiplier == Decimal("7")
    # Unit 13: shift_portfolio_for_redemption is gone -- final approval no
    # longer writes client_portfolios at all.


# --- Negative ------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "status",
    [AllotRdmpStatus.AWAITING_PC, AllotRdmpStatus.APPROVED, AllotRdmpStatus.REJECTED],
)
def test_decide_on_non_awaiting_co_status_raises_409(session, status):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    row = _make_redemption_row(svc, client=client, model=model, multiplier=Decimal("3"), status=status)
    session.commit()

    with pytest.raises(HTTPException) as exc:
        svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="approve"), decided_by="co-uid")
    assert exc.value.status_code == 409


def test_reject_without_reason_raises_422(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    row = _make_redemption_row(
        svc, client=client, model=model, multiplier=Decimal("3"), status=AllotRdmpStatus.AWAITING_CO
    )
    session.commit()

    with pytest.raises(HTTPException) as exc:
        svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="reject"), decided_by="co-uid")
    assert exc.value.status_code == 422


# --- Invariant: CO approve is idempotently non-terminal -----------------------------------


def test_second_co_decide_call_on_now_awaiting_pc_row_raises_409_not_reapprove(session):
    client = make_client(session)
    model = make_model(session, model_size=Decimal("1"))
    make_subscription(session, client, model, multiplier=Decimal("10"))
    make_portfolio(session, client)

    svc = OnboardingService(session)
    row = _make_redemption_row(
        svc, client=client, model=model, multiplier=Decimal("3"), status=AllotRdmpStatus.AWAITING_CO
    )
    session.commit()

    svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="approve"), decided_by="co-uid")

    with pytest.raises(HTTPException) as exc:
        svc.co_decide_redemption(row.id, RedemptionDecisionReq(verdict="approve"), decided_by="co-uid")
    assert exc.value.status_code == 409


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
