// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-2.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/mobo", () => ({
  getReconciliation: vi.fn(),
}));

import * as serverMobo from "@/server/mobo";
import { getFlow } from "@/app/(roles)/mobo/trade-reconciliation/actions";

describe("FE-2 getFlow server-action wrapper", () => {
  beforeEach(() => vi.clearAllMocks());

  it("getFlow(sessionId) calls getReconciliation(sessionId) and returns its result verbatim", async () => {
    const dto = { success: true, data: { settleDay: "03 Jun 2026" } };
    vi.mocked(serverMobo.getReconciliation).mockResolvedValue(dto as never);
    const result = await getFlow("abc-123");
    expect(serverMobo.getReconciliation).toHaveBeenCalledWith("abc-123");
    expect(result).toBe(dto);
  });

  it("getFlow() with no session id passes undefined straight through (no default substitution)", async () => {
    vi.mocked(serverMobo.getReconciliation).mockResolvedValue({ success: true, data: {} } as never);
    await getFlow();
    expect(serverMobo.getReconciliation).toHaveBeenCalledWith(undefined);
  });

  it("a thrown error from getReconciliation is caught and converted to an ACTION_ERROR result, not re-thrown", async () => {
    vi.mocked(serverMobo.getReconciliation).mockRejectedValue(new Error("network down"));
    const result = await getFlow("abc-123");
    expect(result).toEqual({ success: false, error: "network down", code: "ACTION_ERROR" });
  });

  it("a failed (non-throwing) APIResult passes through unchanged", async () => {
    const err = { success: false, error: "boom", code: "HTTP_404" };
    vi.mocked(serverMobo.getReconciliation).mockResolvedValue(err as never);
    const result = await getFlow("abc-123");
    expect(result).toBe(err);
  });
});
