// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-5.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen } from "@testing-library/react";

vi.mock("@/hooks/api/useReconciliationFlow", () => ({
  useReconciliationFlow: vi.fn(),
}));

import { useReconciliationFlow } from "@/hooks/api/useReconciliationFlow";
import TradeReconciliationPage from "@/app/(roles)/mobo/trade-reconciliation/page";

const VIEW = {
  settleDay: "03 Jun 2026",
  orders: [
    {
      id: "o1", m: "mA", inst: "AAPL US", cat: "Equity", side: "Buy",
      qty: "12,000", px: "$187.40", not: "$2.25M", notVal: 2_250_000,
      ref: "TRD-88142", ib: "IB-40118", st: "ok" as const,
      execs: [{ id: "x1", qty: "12,000", px: "$187.40", t: "09:31:02", st: "ok" as const }],
    },
  ],
  allocs: [],
  ports: [],
  algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
  counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
};

function mockHook(overrides: Partial<ReturnType<typeof useReconciliationFlow>> = {}) {
  vi.mocked(useReconciliationFlow).mockReturnValue({
    data: VIEW, loading: false, error: null, refetch: vi.fn(),
    ...overrides,
  } as ReturnType<typeof useReconciliationFlow>);
}

describe("FE-5 TradeReconciliationPage", () => {
  beforeEach(() => vi.clearAllMocks());

  it("renders the live-fetched view's settleDay and order once loaded", () => {
    mockHook();
    render(<TradeReconciliationPage />);
    expect(screen.getByText(/03 Jun 2026/)).toBeInTheDocument();
    expect(screen.getByText("AAPL US")).toBeInTheDocument();
  });

  it("renders a loading state without throwing on undefined array access, when data is null and loading is true", () => {
    mockHook({ data: null, loading: true });
    expect(() => render(<TradeReconciliationPage />)).not.toThrow();
  });

  it("renders an error branch (not a crash) when the hook reports an error", () => {
    mockHook({ data: null, loading: false, error: "network down" });
    render(<TradeReconciliationPage />);
    expect(screen.getByRole("alert")).toBeInTheDocument();
  });

  it("clicking Retry in the error branch calls the hook's refetch", () => {
    const refetch = vi.fn();
    mockHook({ data: null, loading: false, error: "network down", refetch });
    render(<TradeReconciliationPage />);
    fireEvent.click(screen.getByRole("button", { name: /retry/i }));
    expect(refetch).toHaveBeenCalled();
  });
});
