// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-6.
// Regenerate: /test-gen standard.
//
// Orchestrator note (012-fe run): per the FE-4 test file's note, this run
// resequenced the RcScenarioKey export removal into this unit (FE-6), landing
// it in the same commit as the mock-file deletion, so no in-between wave ever
// has a dangling import. Asserted here instead of in the FE-4 test file.
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ADMIN_FRONTEND_ROOT = process.cwd();

function readIfExists(relPath: string): string | null {
  const full = path.resolve(ADMIN_FRONTEND_ROOT, relPath);
  return fs.existsSync(full) ? fs.readFileSync(full, "utf-8") : null;
}

describe("FE-6 mock deletion", () => {
  it("lib/mock/mobo-flow-data.ts no longer exists", () => {
    expect(readIfExists("lib/mock/mobo-flow-data.ts")).toBeNull();
  });

  it("no remaining import of mobo-flow-data anywhere under admin-frontend", () => {
    const searchDirs = ["app", "components", "hooks", "lib", "server"];
    const offenders: string[] = [];
    for (const dir of searchDirs) {
      const abs = path.resolve(ADMIN_FRONTEND_ROOT, dir);
      if (!fs.existsSync(abs)) continue;
      for (const file of walk(abs)) {
        const src = fs.readFileSync(file, "utf-8");
        if (/mobo-flow-data/.test(src)) offenders.push(path.relative(ADMIN_FRONTEND_ROOT, file));
      }
    }
    expect(offenders).toEqual([]);
  });

  it("RcScenarioKey is no longer exported from lib/mobo/flow-types.ts", () => {
    const src = readIfExists("lib/mobo/flow-types.ts");
    expect(src).not.toBeNull();
    expect(src).not.toMatch(/export\s+type\s+RcScenarioKey/);
  });
});

// Plain array return (not a generator) — this tsconfig has no `target` set
// (defaults below ES2015), so iterating a Generator trips TS2802.
function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next" || entry.name === "tests") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry.name)) out.push(full);
  }
  return out;
}
