"""Shared fixtures/doubles for tests/libs/identity, and re-used (imported) by
tests/libs/{clients,staff,dev}/conftest.py wherever a §7-adjacent identity
seam needs faking.

Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-1..BE-4.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Layer isolation: only imports app/ + stdlib + pytest. No sibling-layer (DB/FE) imports.

Pre-implementation note: app.libs.identity does not exist on this branch yet (BE-1..BE-4
are unimplemented) -- collection of test_be1.py/test_be2.py/test_be3.py/test_be4.py is
expected to fail with ModuleNotFoundError until those units land. This conftest itself
has no import on app.libs.identity, so it collects cleanly on its own.
"""

from __future__ import annotations

import itertools

import pytest

_fake_uid_sequence = itertools.count(1)


@pytest.fixture(autouse=True)
def _reset_fake_uid_sequence():
    """Fresh uid sequence per test (BE-1 asserts a deterministic first uid),
    while still shared across multiple FakeAuthModule instances constructed
    WITHIN one test (BE-2 needs two independently-constructed fakes -- e.g.
    simulating two concurrent callers hitting one real Firebase project -- to
    mint distinct uids, which a real globally-unique auth backend guarantees
    but two isolated per-instance counters starting at 0 cannot)."""
    global _fake_uid_sequence
    _fake_uid_sequence = itertools.count(1)
    yield


class FakeUserNotFoundError(Exception):
    """Stand-in for firebase_admin.auth.UserNotFoundError -- BE-1's create_user
    catches this exact type from the real SDK, so the fake module's exception
    class must be what BE-1's code is patched to see, not a bare Exception."""


class FakeAuthModule:
    """Fakes the `firebase_admin.auth` module surface FirebaseIdentityService (BE-1)
    calls: create_user / get_user_by_email / delete_user / generate_password_reset_link.
    Deterministic, in-memory, call-tracked -- no network."""

    UserNotFoundError = FakeUserNotFoundError

    def __init__(self, *, existing: dict[str, str] | None = None) -> None:
        self._by_email: dict[str, str] = dict(existing or {})
        # ponytail: module-level sequence (not a per-instance counter) so two
        # independently constructed fakes -- simulating two concurrent callers
        # hitting one real Firebase project -- still mint distinct uids, matching
        # what a real globally-unique auth backend guarantees.
        self.create_user_calls: list[str] = []
        self.create_user_kwargs: list[dict] = []  # BE-5 (014): records password= too
        self.get_user_by_email_calls: list[str] = []
        self.delete_user_calls: list[str] = []
        self.generate_password_reset_link_calls: list[str] = []
        self._raise_on_create: Exception | None = None

    def fail_next_create(self, exc: Exception) -> None:
        self._raise_on_create = exc

    class _FakeUserRecord:
        def __init__(self, uid: str) -> None:
            self.uid = uid

    def create_user(self, *, email: str, password: str | None = None):
        self.create_user_calls.append(email)
        self.create_user_kwargs.append({"email": email, "password": password})
        if self._raise_on_create is not None:
            exc, self._raise_on_create = self._raise_on_create, None
            raise exc
        uid = f"fb-uid-{next(_fake_uid_sequence)}"
        self._by_email[email] = uid
        return self._FakeUserRecord(uid)

    def get_user_by_email(self, email: str):
        self.get_user_by_email_calls.append(email)
        uid = self._by_email.get(email)
        if uid is None:
            raise self.UserNotFoundError(email)
        return self._FakeUserRecord(uid)

    def delete_user(self, uid: str) -> None:
        self.delete_user_calls.append(uid)
        for email, existing_uid in list(self._by_email.items()):
            if existing_uid == uid:
                del self._by_email[email]
                return
        raise self.UserNotFoundError(uid)

    def generate_password_reset_link(self, email: str) -> str:
        self.generate_password_reset_link_calls.append(email)
        return f"https://fake-firebase.invalid/reset?email={email}"


class FakeFirebaseIdentityService:
    """Test double for the FULL FirebaseIdentityService public surface (BE-1's
    contract), used by tests OUTSIDE the identity module (BE-12/13/15/17/21/23/25)
    as their §7-adjacent seam mock -- these callers never construct a real
    FirebaseIdentityService or touch firebase_admin at all."""

    def __init__(
        self,
        *,
        existing: dict[str, str] | None = None,
        fail_create: bool = False,
        fail_create_exc: Exception | None = None,
    ) -> None:
        self._existing: dict[str, str] = dict(existing or {})
        self._counter = 0
        self._fail_create = fail_create
        self._fail_create_exc = fail_create_exc or RuntimeError("firebase create failed")
        self.create_user_calls: list[str] = []
        self.ensure_identity_calls: list[str] = []
        self.delete_user_calls: list[str] = []
        self.generate_set_password_link_calls: list[str] = []
        self.get_user_by_email_calls: list[str] = []

    def get_user_by_email(self, email: str) -> str | None:
        self.get_user_by_email_calls.append(email)
        return self._existing.get(email)

    def create_user(self, email: str) -> str:
        self.create_user_calls.append(email)
        if self._fail_create:
            raise self._fail_create_exc
        self._counter += 1
        uid = f"fake-uid-{self._counter}"
        self._existing[email] = uid
        return uid

    def ensure_identity(self, email: str) -> tuple[str, bool]:
        self.ensure_identity_calls.append(email)
        existing_uid = self.get_user_by_email(email)
        if existing_uid is not None:
            return existing_uid, False
        return self.create_user(email), True

    def delete_user(self, uid: str) -> None:
        self.delete_user_calls.append(uid)
        for email, existing_uid in list(self._existing.items()):
            if existing_uid == uid:
                del self._existing[email]

    def generate_set_password_link(self, email: str) -> str:
        self.generate_set_password_link_calls.append(email)
        return f"https://fake.invalid/invite?email={email}"


# ============================================================================
# 019 section -- BE-12 / BE-13 / BE-14 (Admin Access Control & Staff Enrollment)
#
# Generated by test-gen (thorough) from
# docs/implementations/019-admin-access-control-and-staff-enrollment-be.md
# Regenerate: /test-gen thorough docs/implementations/019-admin-access-control-and-staff-enrollment-be.md
#
# Additive only -- nothing above this marker is modified or removed.
# ============================================================================


class FakeAuthModuleQ5(FakeAuthModule):
    """Extends FakeAuthModule (BE-1) with the two calls BE-13's
    generate_set_password_link needs: a `generate_password_reset_link` that can
    be told to raise (simulating Firebase rejecting a passwordless account),
    and `generate_sign_in_with_email_link`, the email-link fallback. Kept as a
    subclass rather than an edit to FakeAuthModule so nothing already relied on
    by BE-1..BE-4/BE-25 tests changes shape."""

    def __init__(self, *, existing: dict[str, str] | None = None) -> None:
        super().__init__(existing=existing)
        self._raise_on_reset_link: Exception | None = None
        self.generate_sign_in_with_email_link_calls: list[tuple[str, object]] = []

    def fail_next_generate_password_reset_link(self, exc: Exception) -> None:
        self._raise_on_reset_link = exc

    def generate_password_reset_link(self, email: str) -> str:
        self.generate_password_reset_link_calls.append(email)
        if self._raise_on_reset_link is not None:
            exc, self._raise_on_reset_link = self._raise_on_reset_link, None
            raise exc
        return f"https://fake-firebase.invalid/reset?email={email}"

    def generate_sign_in_with_email_link(self, email: str, action_code_settings=None) -> str:
        self.generate_sign_in_with_email_link_calls.append((email, action_code_settings))
        return f"https://fake-firebase.invalid/email-link?email={email}"
