"""Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-3.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Layer isolation: no firebase_admin import at all is exercised on this path -- the
whole point of the test is to prove zero calls into the faked SDK.

Pre-implementation: app.libs.identity.service does not exist yet -- expected
ModuleNotFoundError until BE-1/BE-2/BE-3 land.
Run: .venv/Scripts/python.exe -m pytest -q tests/libs/identity/test_be3_dev_stub.py
"""

from __future__ import annotations

from unittest.mock import patch

import pytest

from app.core.config import Settings
from app.libs.identity.service import FirebaseIdentityService
from tests.libs.identity.conftest import FakeAuthModule


def _dev_service() -> FirebaseIdentityService:
    return FirebaseIdentityService(Settings(firebase_auth_disabled=True))


# --- Positive ------------------------------------------------------------------


def test_create_user_under_dev_bypass_returns_deterministic_value_with_zero_sdk_calls():
    fake_auth = FakeAuthModule()
    svc = _dev_service()
    with patch("app.libs.identity.service.auth", fake_auth):
        uid = svc.create_user("dev@example.com")
    assert uid == "dev-dev@example.com"
    assert fake_auth.create_user_calls == []


def test_generate_set_password_link_dev_bypass_is_deterministic_with_zero_sdk_calls():
    fake_auth = FakeAuthModule()
    svc = _dev_service()
    with patch("app.libs.identity.service.auth", fake_auth):
        link = svc.generate_set_password_link("dev@example.com")
    assert link == "https://dev.invalid/set-password?email=dev@example.com"
    assert fake_auth.generate_password_reset_link_calls == []


# --- Invariants ------------------------------------------------------------------


@pytest.mark.parametrize("email", ["a@example.com", "b@example.com", "unicode-ñ@example.com"])
def test_same_email_always_yields_same_synthetic_uid_deterministic(email):
    svc = _dev_service()
    with patch("app.libs.identity.service.auth", FakeAuthModule()):
        uid1 = svc.create_user(email)
        uid2 = svc.create_user(email)
    assert uid1 == uid2


def test_different_emails_yield_different_synthetic_uids():
    svc = _dev_service()
    with patch("app.libs.identity.service.auth", FakeAuthModule()):
        uid_a = svc.create_user("a@example.com")
        uid_b = svc.create_user("b@example.com")
    assert uid_a != uid_b


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
