// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-3.
// Regenerate: /test-gen standard.
//
// Refetch-wiring note: ADM-3's "Files:" list touches only components/rm/RequestTickets.tsx
// (not app/(roles)/rm/requests/[ref]/page.tsx), so this test assumes RequestTicketDetail /
// its action panels obtain their own refetch handle via useRmTicket(ticket.ref) internally —
// the only way to satisfy impl doc §6 ADM-3's "on success, the detail page refetches" without
// also touching page.tsx. If the implementation instead threads refetch through as a prop
// from the page, this is a real spec gap — flag it rather than editing these assertions.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn() }) }));
vi.mock("@/app/(roles)/rm/requests/actions", () => ({ setTicketStatus: vi.fn() }));
vi.mock("@/hooks/api/useRmTickets", () => ({ useRmTicket: vi.fn() }));

import { setTicketStatus } from "@/app/(roles)/rm/requests/actions";
import { useRmTicket } from "@/hooks/api/useRmTickets";
import { RequestTicketDetail } from "@/components/rm/RequestTickets";
import type { RequestTicket } from "@/lib/mock/rm-data";

function ok(data: unknown) {
  return { success: true as const, data };
}
function fail409() {
  return { success: false as const, error: "Cannot transition out of a terminal status", code: "HTTP_409" };
}

function tradeTicket(overrides: Partial<RequestTicket> = {}): RequestTicket {
  return {
    ref: "REQ-1001", client: "Ardent Capital", contact: "Marcus Lindqvist", email: "m@x.com",
    model: "Global Balanced", account: "IB-4471", type: "Allotment", ccy: "USD", cash: "180,000",
    mult: "2×", notional: "360,000", date: "Jun 06", status: "New", tone: "warm",
    message: "Please allot USD 180,000.",
    ...overrides,
  };
}

function otherTicket(overrides: Partial<RequestTicket> = {}): RequestTicket {
  return {
    ref: "REQ-2041", client: "Coalfield & Co.", contact: "Derek Mwangi", email: "derek@coalfield.com.au",
    account: "IB-1190", type: "Other", ccy: "—", cash: "—", mult: "—", notional: "—", date: "Jun 03",
    status: "In Progress", tone: "review", subject: "Update authorised signatory",
    message: "We've appointed a new CFO.",
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(useRmTicket).mockReturnValue({ data: null, loading: false, error: null, refetch: vi.fn() } as never);
});

describe("ADM-3 ActOnTradePanel — Decline", () => {
  it("posts {status:'declined', note} and refetches on success", async () => {
    const refetch = vi.fn();
    vi.mocked(useRmTicket).mockReturnValue({ data: null, loading: false, error: null, refetch } as never);
    vi.mocked(setTicketStatus).mockResolvedValue(ok(tradeTicket({ status: "Declined" })) as never);

    render(<RequestTicketDetail ticket={tradeTicket()} />);
    fireEvent.click(screen.getByText("Select a reason…"));
    fireEvent.click(screen.getByText("Insufficient documentation"));
    fireEvent.click(screen.getByRole("button", { name: /decline request/i }));

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-1001", { status: "declined", note: "Insufficient documentation" },
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });

  it("a 409 renders inline without crashing and does not silently no-op", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(fail409() as never);
    render(<RequestTicketDetail ticket={tradeTicket()} />);
    fireEvent.click(screen.getByText("Select a reason…"));
    fireEvent.click(screen.getByText("Insufficient documentation"));
    expect(() => fireEvent.click(screen.getByRole("button", { name: /decline request/i }))).not.toThrow();
    await waitFor(() => expect(screen.getByText(/terminal status/i)).toBeInTheDocument());
  });
});

describe("ADM-3 ActOnTradePanel — Act on request (implicit in-progress transition)", () => {
  it("clicking 'Act on request' also posts {status:'in_progress'} with no note", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(ok(tradeTicket({ status: "In Progress" })) as never);
    render(<RequestTicketDetail ticket={tradeTicket()} />);
    fireEvent.click(screen.getByRole("button", { name: /act on request/i }));
    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith("REQ-1001", { status: "in_progress" }));
  });
});

describe("ADM-3 TicketActions (Other tickets) — Resolve", () => {
  it("posts {status:'resolved'} and refetches on success", async () => {
    const refetch = vi.fn();
    vi.mocked(useRmTicket).mockReturnValue({ data: null, loading: false, error: null, refetch } as never);
    vi.mocked(setTicketStatus).mockResolvedValue(ok(otherTicket({ status: "Resolved" })) as never);

    render(<RequestTicketDetail ticket={otherTicket()} />);
    fireEvent.click(screen.getByRole("button", { name: /resolve/i }));

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-2041", expect.objectContaining({ status: "resolved" }),
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });

  it("a 409 renders inline without crashing", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(fail409() as never);
    render(<RequestTicketDetail ticket={otherTicket()} />);
    expect(() => fireEvent.click(screen.getByRole("button", { name: /resolve/i }))).not.toThrow();
    await waitFor(() => expect(screen.getByText(/terminal status/i)).toBeInTheDocument());
  });
});

describe("ADM-3 TicketActions (Other tickets) — Decline", () => {
  it("requires a note before Decline is enabled, then posts {status:'declined', note}", async () => {
    const refetch = vi.fn();
    vi.mocked(useRmTicket).mockReturnValue({ data: null, loading: false, error: null, refetch } as never);
    vi.mocked(setTicketStatus).mockResolvedValue(ok(otherTicket({ status: "Declined" })) as never);

    render(<RequestTicketDetail ticket={otherTicket()} />);
    const declineButton = screen.getByRole("button", { name: /decline/i });
    expect(declineButton).toBeDisabled();

    fireEvent.change(screen.getByPlaceholderText(/add a note/i), {
      target: { value: "Not enough detail provided." },
    });
    expect(declineButton).not.toBeDisabled();
    fireEvent.click(declineButton);

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-2041", { status: "declined", note: "Not enough detail provided." },
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });
});
