// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-3.
// Regenerate: /test-gen standard.
//
// Refetch-wiring note (resolved): current source threads refetch through as a required
// `onRefetch` prop (RequestTicketDetail -> ActOnTradePanel/TicketActions as
// `onStatusChange`, RequestTickets.tsx:213/270/286) — it is NOT obtained internally via
// useRmTicket(ticket.ref). That's deliberate prop-drilling from the page, not a spec gap;
// the fixture below supplies onRefetch directly rather than relying on useRmTicket's mock.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, screen, waitFor } from "@testing-library/react";
import { renderWithAuth as render } from "@/tests/_helpers/renderWithAuth";

// RequestTickets.tsx gates its Decline/Act-on-request controls on
// useCanEdit("rm.request-tickets") (D-14 — see FE-6.gate-sites.test.tsx). A real,
// unauthenticated AuthProvider resolves every grant to "NONE"; mock useAuth with an
// EDIT grant so the action buttons render, matching the gate-sites precedent.
const mockUseAuth = vi.fn(() => ({ portalUser: { role: "RM", grants: { "rm.request-tickets": "EDIT" } } }));
vi.mock("@/components/auth/AuthProvider", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/components/auth/AuthProvider")>()),
  useAuth: () => mockUseAuth(),
}));

vi.mock("next/navigation", async (importOriginal) => ({
    ...(await importOriginal<typeof import("next/navigation")>()),
  useRouter: () => ({ push: vi.fn() }),
  useSearchParams: () => new URLSearchParams(),
}));
vi.mock("@/app/(roles)/rm/requests/actions", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/app/(roles)/rm/requests/actions")>()), setTicketStatus: vi.fn() }));

import { setTicketStatus } from "@/app/(roles)/rm/requests/actions";
import { RequestTicketDetail } from "@/components/rm/RequestTickets";
import type { RequestTicket } from "@/lib/rm/tickets";

function ok(data: unknown) {
  return { success: true as const, data };
}
function fail409() {
  return { success: false as const, error: "Cannot transition out of a terminal status", code: "HTTP_409" };
}

function tradeTicket(overrides: Partial<RequestTicket> = {}): RequestTicket {
  return {
    ref: "REQ-1001", clientId: "c-1", client: "Ardent Capital", contact: "Marcus Lindqvist", email: "m@x.com",
    modelId: "m-1", model: "Global Balanced", account: "IB-4471", type: "Allotment", ccy: "USD", cash: "180,000",
    mult: "2×", notional: "360,000", date: "Jun 06", status: "New", tone: "warm",
    message: "Please allot USD 180,000.",
    ...overrides,
  };
}

function otherTicket(overrides: Partial<RequestTicket> = {}): RequestTicket {
  return {
    ref: "REQ-2041", clientId: "c-2", client: "Coalfield & Co.", contact: "Derek Mwangi", email: "derek@coalfield.com.au",
    account: "IB-1190", type: "Other", ccy: "—", cash: "—", mult: "—", notional: "—", date: "Jun 03",
    status: "In Progress", tone: "review", subject: "Update authorised signatory",
    message: "We've appointed a new CFO.",
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe("ADM-3 ActOnTradePanel — Decline", () => {
  it("posts {status:'declined', note} and refetches on success", async () => {
    const refetch = vi.fn();
    vi.mocked(setTicketStatus).mockResolvedValue(ok(tradeTicket({ status: "Declined" })) as never);

    render(<RequestTicketDetail ticket={tradeTicket()} onRefetch={refetch} />);
    fireEvent.click(screen.getByText("Select a reason…"));
    fireEvent.click(screen.getByText("Insufficient documentation"));
    fireEvent.click(screen.getByRole("button", { name: /decline request/i }));

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-1001", { status: "declined", note: "Insufficient documentation" },
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });

  it("a 409 renders inline without crashing and does not silently no-op", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(fail409() as never);
    render(<RequestTicketDetail ticket={tradeTicket()} onRefetch={vi.fn()} />);
    fireEvent.click(screen.getByText("Select a reason…"));
    fireEvent.click(screen.getByText("Insufficient documentation"));
    expect(() => fireEvent.click(screen.getByRole("button", { name: /decline request/i }))).not.toThrow();
    await waitFor(() => expect(screen.getByText(/terminal status/i)).toBeInTheDocument());
  });
});

describe("ADM-3 ActOnTradePanel — Act on request (implicit in-progress transition)", () => {
  it("clicking 'Act on request' also posts {status:'in_progress'} with no note", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(ok(tradeTicket({ status: "In Progress" })) as never);
    render(<RequestTicketDetail ticket={tradeTicket()} onRefetch={vi.fn()} />);
    fireEvent.click(screen.getByRole("button", { name: /act on request/i }));
    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith("REQ-1001", { status: "in_progress" }));
  });
});

describe("ADM-3 TicketActions (Other tickets) — Resolve", () => {
  it("posts {status:'resolved'} and refetches on success", async () => {
    const refetch = vi.fn();
    vi.mocked(setTicketStatus).mockResolvedValue(ok(otherTicket({ status: "Resolved" })) as never);

    render(<RequestTicketDetail ticket={otherTicket()} onRefetch={refetch} />);
    fireEvent.click(screen.getByRole("button", { name: /resolve/i }));

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-2041", expect.objectContaining({ status: "resolved" }),
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });

  it("a 409 renders inline without crashing", async () => {
    vi.mocked(setTicketStatus).mockResolvedValue(fail409() as never);
    render(<RequestTicketDetail ticket={otherTicket()} onRefetch={vi.fn()} />);
    expect(() => fireEvent.click(screen.getByRole("button", { name: /resolve/i }))).not.toThrow();
    await waitFor(() => expect(screen.getByText(/terminal status/i)).toBeInTheDocument());
  });
});

describe("ADM-3 TicketActions (Other tickets) — Decline", () => {
  it("requires a note before Decline is enabled, then posts {status:'declined', note}", async () => {
    const refetch = vi.fn();
    vi.mocked(setTicketStatus).mockResolvedValue(ok(otherTicket({ status: "Declined" })) as never);

    render(<RequestTicketDetail ticket={otherTicket()} onRefetch={refetch} />);
    const declineButton = screen.getByRole("button", { name: /decline/i });
    expect(declineButton).toBeDisabled();

    fireEvent.change(screen.getByPlaceholderText(/add a note/i), {
      target: { value: "Not enough detail provided." },
    });
    expect(declineButton).not.toBeDisabled();
    fireEvent.click(declineButton);

    await waitFor(() => expect(setTicketStatus).toHaveBeenCalledWith(
      "REQ-2041", { status: "declined", note: "Not enough detail provided." },
    ));
    await waitFor(() => expect(refetch).toHaveBeenCalled());
  });
});
