// Generated by test-gen (standard) from docs/implementations/014-onboarding-follow-up-fixes-fe.md §FE-2. Regenerate: /test-gen standard.
import { describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";

vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn() }) }));
vi.mock("@/hooks/api/useOnboardingBoard", () => ({ useOnboardingBoard: vi.fn() }));

import { useOnboardingBoard } from "@/hooks/api/useOnboardingBoard";
import { OnboardingBoard } from "@/components/rm/OnboardingBoard";
import { mapRow } from "@/lib/onboarding/mappers";
import type { KycBoardClient, OnboardingDTO, OnboardingStatus } from "@/lib/onboarding/types";

function makeDto(overrides: Partial<OnboardingDTO> = {}): OnboardingDTO {
  return {
    id: "ob-1", user_id: "u-1", client_name: "Jane Doe", email: "j@x.com", assigned_rm: "Alice",
    client_ref: "MEGA-0001", primary_phone: "+1", address: "addr", country_of_residence: "US",
    id_type: "passport", id_number: "P1", ibhk_account: "U-1", sw_account: "SW-1",
    status: "reviewing", kind: "initial", model_id: "m-1", model_name: "Balanced", units: 2,
    mgmt_fee: 0.01, incentive_fee: 0.1, verified_count: 0, required_count: 7,
    reject_reason: null, submitted_at: null, created_at: "2026-07-18T00:00:00Z", documents: [],
    ...overrides,
  };
}

function makeClient(overrides: Partial<KycBoardClient> = {}): KycBoardClient {
  return {
    id: "ob-1", name: "Jane Doe", owner: "Alice", clientRef: "MEGA-0001",
    phone: "+1", address: "addr", country: "US", idType: "passport", idNumber: "P1",
    ibhkAccount: "U-1", swAccount: "SW-1", verifiedCount: 0, requiredCount: 7, documents: [],
    ...({ status: "reviewing" } as Record<string, unknown>),
    ...overrides,
  } as KycBoardClient;
}

/** Renders the board with a single column/card so the mocked hook's data
 *  and the props spread onto <OnboardingBoard> are the same object — this
 *  test targets FE-2's chip logic, not FE-1's prop-vs-hook plumbing, so it
 *  must pass regardless of which of the two FE-1 has wired up yet. */
function renderCard(status: OnboardingStatus, client: KycBoardClient) {
  const board = {
    data: [{ label: status, status, clients: [client] }],
    loading: false, error: null, refetch: vi.fn(),
    startOnboarding: vi.fn(), uploadDocument: vi.fn(), submitAll: vi.fn(),
    fetchRmOptions: vi.fn(), fetchDocSpecs: vi.fn(), fetchOnboarding: vi.fn(),
  };
  vi.mocked(useOnboardingBoard).mockReturnValue(board as never);
  render(<OnboardingBoard {...(board as never)} />);
}

describe("FE-2 mapRow copies OnboardingDTO.status onto KycBoardClient.status", () => {
  it("copies status verbatim for every status value", () => {
    expect(mapRow(makeDto({ status: "reviewing" })).status).toBe("reviewing");
    expect(mapRow(makeDto({ status: "initial" })).status).toBe("initial");
    expect(mapRow(makeDto({ status: "pending_review" })).status).toBe("pending_review");
    expect(mapRow(makeDto({ status: "active" })).status).toBe("active");
  });
});

describe("FE-2 KanbanCard chip branches on status, not verifiedCount", () => {
  it("a freshly-submitted client (status=reviewing, verifiedCount=0) shows '0/7 verified', not 'Not started'", () => {
    renderCard("reviewing", makeClient({ verifiedCount: 0, requiredCount: 7, ...({ status: "reviewing" } as Record<string, unknown>) } as never));
    expect(screen.getByText("0/7 verified")).toBeInTheDocument();
    expect(screen.queryByText("Not started")).not.toBeInTheDocument();
  });

  it("status=initial always shows 'Not started', even with a nonzero verifiedCount", () => {
    renderCard("initial", makeClient({ verifiedCount: 3, requiredCount: 7, ...({ status: "initial" } as Record<string, unknown>) } as never));
    expect(screen.getByText("Not started")).toBeInTheDocument();
    expect(screen.queryByText("3/7 verified")).not.toBeInTheDocument();
  });

  it.each([
    ["reviewing", 2, 7],
    ["pending_review", 7, 7],
    ["active", 7, 7],
  ] as const)("status=%s renders '%d/%d verified' (never re-derives status from verifiedCount === 0)", (status, verified, required) => {
    renderCard(status, makeClient({
      verifiedCount: verified, requiredCount: required,
      ...({ status } as Record<string, unknown>),
    } as never));
    expect(screen.getByText(`${verified}/${required} verified`)).toBeInTheDocument();
  });
});
