// Generated by test-gen (standard) from docs/implementations/016-allotment-redemption-integration-fe.md §FE-4. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-4 replaces TxnTable's hardcoded
// "Confirmed" chip with a statusToChip(r[9]) call and adds the D-5
// muted+overline treatment — until the feature agent lands it, every row
// (including rejected ones) still renders the literal "Confirmed" chip and
// no cell carries the muted class, so the assertions below fail as the
// correct pre-implementation signal.
import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import { SubscriptionAccordion } from "@/components/rm/SubscriptionAccordion";
import type { SubClient, TxnRow } from "@/lib/rm/subscriptions";

function makeClient(rows: TxnRow[]): SubClient {
  return {
    id: "c-1", name: "Ardent Capital", initials: "AC", mandate: "Discretionary", aum: "$2.0M",
    models: [
      {
        name: "Balanced", status: "Active", tone: "active",
        mgmtFee: "1.0%", incentiveFee: "10%", account: "IB-4471",
        modelId: "m-1", rows,
      },
    ],
  };
}

describe("FE-4 TxnTable renders the status-driven chip instead of hardcoded 'Confirmed'", () => {
  it.each([
    ["pending", "Confirmed"],
    ["acknowledged", "Confirmed"],
    ["awaiting_pc", "Awaiting Approval"],
    ["awaiting_co", "Awaiting Approval"],
    ["approved", "Approved"],
    ["rejected", "Rejected"],
  ] as const)("a row with status=%s shows the '%s' chip", (status, label) => {
    const row: TxnRow = ["Allotment", "01/01/2026", "IB-4471", "USD", "200,000", "2×", "200,000", "01/01/2026", "—", status];
    render(<SubscriptionAccordion clients={[makeClient([row])]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />);
    expect(screen.getByText(label)).toBeInTheDocument();
  });
});

describe("FE-4 Net row never renders a chip, regardless of its 10th element", () => {
  it("a Net row with 10th element '' shows no chip text", () => {
    const netRow: TxnRow = ["Net", "", "", "", "200,000", "2×", "200,000", "", "", ""];
    render(<SubscriptionAccordion clients={[makeClient([netRow])]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />);
    expect(screen.queryByText("Confirmed")).not.toBeInTheDocument();
    expect(screen.queryByText("Rejected")).not.toBeInTheDocument();
  });
});

describe("FE-4 D-5 rejected-row muted+overline treatment", () => {
  it("a rejected row mutes only Cash Amt/Model ×/Notional, not Type/Date/IB Account/Ccy/Expected", () => {
    const row: TxnRow = ["Redemption", "01/02/2026", "IB-4471", "USD", "(80,000)", "−1×", "(75,000)", "—", "01/03/2026", "rejected"];
    render(<SubscriptionAccordion clients={[makeClient([row])]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />);
    const cashAmtCell = screen.getByText("(80,000)").closest("td");
    expect(cashAmtCell?.className).toMatch(/overline/);
    const notionalCell = screen.getByText("(75,000)").closest("td");
    expect(notionalCell?.className).toMatch(/overline/);
    const typeCell = screen.getByText("Redemption").closest("td");
    expect(typeCell?.className ?? "").not.toMatch(/overline/);
    const dateCell = screen.getByText("01/02/2026").closest("td");
    expect(dateCell?.className ?? "").not.toMatch(/overline/);
    const expectedCell = screen.getByText("01/03/2026").closest("td");
    expect(expectedCell?.className ?? "").not.toMatch(/overline/);
  });

  it("a non-rejected row (e.g. approved) never receives the muted+overline class, even with matching numeric values", () => {
    const row: TxnRow = ["Redemption", "01/03/2026", "IB-4471", "USD", "(80,000)", "−1×", "(75,000)", "—", "01/03/2026", "approved"];
    render(<SubscriptionAccordion clients={[makeClient([row])]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />);
    const cell = screen.getByText("(80,000)").closest("td");
    expect(cell?.className ?? "").not.toMatch(/overline/);
  });
});
