// Generated by test-gen (standard) from docs/implementations/017-transaction-details-wiring-fe.md §FE-5. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-5 wires SubscriptionAccordion to the
// new fileTransactionDetail/getTransactionDetail actions and drops the
// ephemeral `filled` client-side state — today, clicking any eligible row
// always opens the modal in (the only existing) edit mode with no fetch and
// Save just updates local state, so every mode='view'/fetch-triggering
// assertion below fails as the correct pre-implementation signal.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

vi.mock("@/app/(roles)/rm/model-subscription/actions", () => ({
  fileTransactionDetail: vi.fn(),
  getTransactionDetail: vi.fn(),
}));

import * as actions from "@/app/(roles)/rm/model-subscription/actions";
import { SubscriptionAccordion } from "@/components/rm/SubscriptionAccordion";
import type { SubClient, TxnRow } from "@/lib/mock/rm-data";
import type { TransactionDetailDTO } from "@/lib/onboarding/types";

const DETAILS: TransactionDetailDTO = {
  id: "td-1", allotment_id: "a-1", bank_account: "HSBC-4471-001",
  settlement_amount: 180_000, transaction_date: "2026-08-01", transaction_time: "14:30",
  currency: "USD", reference_no: "TXN-1", filed_by: "rm-uid", filed_at: "2026-08-01T14:31:00Z",
};

function makeClient(row: TxnRow): SubClient {
  return {
    id: "c-1", name: "Ardent Capital", initials: "AC", mandate: "Discretionary", aum: "$2.0M",
    models: [
      { name: "Model A", status: "Active", tone: "active", mgmtFee: "1.0%", incentiveFee: "10%", account: "IB-4471", modelId: "m-1", rows: [row] },
    ],
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  document.body.innerHTML = '<div id="content-overlay-root"></div>';
});

describe("FE-5 clicking an unfiled eligible row opens edit mode with no fetch", () => {
  it("does not call getTransactionDetail; Save calls fileTransactionDetail and closes on success", async () => {
    const row: TxnRow = ["Allotment", "01/01/2026", "IB-4471", "USD", "180,000", "2×", "180,000", "01/01/2026", "—", "pending", "a-1", false];
    vi.mocked(actions.fileTransactionDetail).mockResolvedValue({ success: true, data: DETAILS } as never);
    const onFiled = vi.fn();
    render(
      <SubscriptionAccordion
        clients={[makeClient(row)]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0"
        onTransactionDetailFiled={onFiled}
      />,
    );
    fireEvent.click(screen.getByText("IB-4471"));
    expect(actions.getTransactionDetail).not.toHaveBeenCalled();
    fireEvent.change(screen.getByPlaceholderText("e.g. HSBC-4471-001"), { target: { value: "HSBC-4471-001" } });
    const dateInput = document.querySelector('input[type="date"]') as HTMLInputElement;
    fireEvent.change(dateInput, { target: { value: "2026-08-01" } });
    const timeInput = document.querySelector('input[type="time"]') as HTMLInputElement;
    fireEvent.change(timeInput, { target: { value: "14:30" } });
    fireEvent.click(screen.getByRole("button", { name: /^save$/i }));
    await waitFor(() => expect(actions.fileTransactionDetail).toHaveBeenCalledTimes(1));
    expect(actions.fileTransactionDetail).toHaveBeenCalledWith("a-1", expect.objectContaining({
      bank_account: "HSBC-4471-001", transaction_date: "2026-08-01", transaction_time: "14:30",
    }));
    await waitFor(() => expect(onFiled).toHaveBeenCalledWith("c-1"));
    expect(screen.queryByRole("button", { name: /^save$/i })).not.toBeInTheDocument();
  });
});

describe("FE-5 clicking an already-filed row opens view mode via getTransactionDetail", () => {
  it("fetches and displays the exact previously-filed values as read-only text, no Save button", async () => {
    const row: TxnRow = ["Allotment", "01/01/2026", "IB-4471", "USD", "180,000", "2×", "180,000", "01/01/2026", "—", "pending", "a-1", true];
    vi.mocked(actions.getTransactionDetail).mockResolvedValue({ success: true, data: DETAILS } as never);
    render(
      <SubscriptionAccordion clients={[makeClient(row)]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />,
    );
    fireEvent.click(screen.getByText("IB-4471"));
    expect(actions.getTransactionDetail).toHaveBeenCalledWith("a-1");
    await waitFor(() => expect(screen.getByText("HSBC-4471-001")).toBeInTheDocument());
    expect(screen.queryByRole("button", { name: /^save$/i })).not.toBeInTheDocument();
    // Modal's header dismiss button is icon-only with aria-label="Close" too
    // (Shared.tsx) — query by visible text to target only the footer button.
    expect(screen.getByText("Close")).toBeInTheDocument();
  });
});

describe("FE-5 a failed Save leaves the modal open", () => {
  it("does not call onTransactionDetailFiled and keeps the Save button present", async () => {
    const row: TxnRow = ["Allotment", "01/01/2026", "IB-4471", "USD", "180,000", "2×", "180,000", "01/01/2026", "—", "pending", "a-1", false];
    vi.mocked(actions.fileTransactionDetail).mockResolvedValue({ success: false, error: "409 already filed", code: "HTTP_409" } as never);
    const onFiled = vi.fn();
    render(
      <SubscriptionAccordion
        clients={[makeClient(row)]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0"
        onTransactionDetailFiled={onFiled}
      />,
    );
    fireEvent.click(screen.getByText("IB-4471"));
    fireEvent.change(screen.getByPlaceholderText("e.g. HSBC-4471-001"), { target: { value: "HSBC-4471-001" } });
    fireEvent.change(document.querySelector('input[type="date"]') as HTMLInputElement, { target: { value: "2026-08-01" } });
    fireEvent.change(document.querySelector('input[type="time"]') as HTMLInputElement, { target: { value: "14:30" } });
    fireEvent.click(screen.getByRole("button", { name: /^save$/i }));
    await waitFor(() => expect(actions.fileTransactionDetail).toHaveBeenCalledTimes(1));
    expect(onFiled).not.toHaveBeenCalled();
    expect(screen.getByRole("button", { name: /^save$/i })).toBeInTheDocument();
  });
});

describe("FE-5 removed ephemeral 'filled' state", () => {
  it("the done/eligible icon reads row[11] directly — a filed row (12th element true) shows the check icon with no prior click", () => {
    const row: TxnRow = ["Allotment", "01/01/2026", "IB-4471", "USD", "180,000", "2×", "180,000", "01/01/2026", "—", "pending", "a-1", true];
    render(
      <SubscriptionAccordion clients={[makeClient(row)]} onOpenModal={() => {}} initialOpenClient="c-1" initialOpenModelKey="c-1-0" />,
    );
    expect(screen.getByTitle("Details submitted")).toBeInTheDocument();
  });
});
