// Generated by test-gen (thorough) from docs/implementations/014-onboarding-follow-up-fixes-fe.md §FE-5. Regenerate: /test-gen thorough.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

vi.mock("@/hooks/api/useOnboardingBoard", () => ({ useOnboardingBoard: vi.fn() }));
vi.mock("@/hooks/api/useModels", () => ({ useModels: vi.fn() }));

import { useOnboardingBoard } from "@/hooks/api/useOnboardingBoard";
import { useModels } from "@/hooks/api/useModels";
import { OnboardingModal } from "@/components/rm/OnboardingModal";

/** A fake Model, deliberately carrying BOTH `size` (the field the existing
 *  `Model` type in lib/pc/types.ts actually uses) and `model_size` (the
 *  literal name §6 FE-5's contract snippet reads) so this black-box test
 *  doesn't have to take a side on that naming — it only ever observes the
 *  modal through its rendered DOM, never the implementation's internal
 *  property access. `size: undefined` simulates the "model_size unknown"
 *  case from §8.3's negative goal. */
function makeModel(size: number | undefined, id = "m-1") {
  return { id, name: "Balanced", status: "live", mgmt: 1, incentive: 10, size, model_size: size };
}

function boardFixture(startOnboarding = vi.fn().mockResolvedValue({ success: true, id: "ob-1" })) {
  return {
    data: null, loading: false, error: null, refetch: vi.fn(),
    startOnboarding,
    uploadDocument: vi.fn().mockResolvedValue({ success: true }),
    submitAll: vi.fn().mockResolvedValue({ success: true }),
    fetchRmOptions: vi.fn().mockResolvedValue({ success: true, data: [] }),
    fetchDocSpecs: vi.fn().mockResolvedValue({ success: true, data: [] }),
    fetchOnboarding: vi.fn().mockResolvedValue({ success: true, data: null }),
  };
}

/** Renders the modal, wired so it works whether OnboardingModal still calls
 *  useOnboardingBoard() internally (pre-FE-1) or reads props (post-FE-1) —
 *  `startOnboarding` is the SAME spy reference either way. */
function renderModal(model: ReturnType<typeof makeModel>, startOnboarding = vi.fn().mockResolvedValue({ success: true, id: "ob-1" })) {
  const board = boardFixture(startOnboarding);
  vi.mocked(useOnboardingBoard).mockReturnValue(board as never);
  vi.mocked(useModels).mockReturnValue({ data: [model], loading: false, error: null, refetch: vi.fn() } as never);
  render(
    <OnboardingModal
      onClose={vi.fn()}
      startOnboarding={startOnboarding}
      uploadDocument={board.uploadDocument}
      fetchRmOptions={board.fetchRmOptions}
      fetchDocSpecs={board.fetchDocSpecs}
      {...({} as never)}
    />,
  );
  return board;
}

function goToTradeInfo() {
  fireEvent.click(screen.getByRole("button", { name: /trade info/i }));
}

function fillTradeInfo({ modelId, units, deposit }: { modelId: string; units: string; deposit: string }) {
  fireEvent.change(screen.getByPlaceholderText("e.g. IB-8801"), { target: { value: "IB-1" } });
  fireEvent.change(screen.getByPlaceholderText("e.g. SW-4420"), { target: { value: "SW-1" } });
  fireEvent.change(screen.getByDisplayValue("Select a model…"), { target: { value: modelId } });
  fireEvent.change(screen.getByPlaceholderText("e.g. 2"), { target: { value: units } });
  const depositInput = screen.queryByPlaceholderText("e.g. 250000");
  if (depositInput) fireEvent.change(depositInput, { target: { value: deposit } });
}

function fillBasicInfo() {
  fireEvent.change(screen.getByPlaceholderText("e.g. Greystone Partners"), { target: { value: "Acme Corp" } });
  fireEvent.change(screen.getByPlaceholderText("+1 (312) 555-0199"), { target: { value: "+1 555 0100" } });
  fireEvent.change(screen.getByPlaceholderText("name@company.com"), { target: { value: "a@b.com" } });
  fireEvent.change(screen.getByPlaceholderText("Registered address"), { target: { value: "1 Main St" } });
  fireEvent.change(screen.getByPlaceholderText("e.g. A1234567"), { target: { value: "A1" } });
  fireEvent.change(screen.getByPlaceholderText("e.g. Hong Kong SAR"), { target: { value: "HK" } });
}

beforeEach(() => {
  vi.clearAllMocks();
  document.body.innerHTML = '<div id="content-overlay-root"></div>';
});

describe("FE-5 floor check: initial_cash_deposit >= units * model_size (N=0)", () => {
  it.each([
    { size: 100_000, units: "2", deposit: "200000", expectEnabled: true, label: "exactly at the floor" },
    { size: 100_000, units: "2", deposit: "199999", expectEnabled: false, label: "one unit under the floor" },
    { size: 100_000, units: "2", deposit: "500000", expectEnabled: true, label: "well above the floor" },
    { size: 100_000, units: "1", deposit: "0", expectEnabled: false, label: "zero deposit against a nonzero floor" },
  ])("$label -> Onboard Client enabled = $expectEnabled", async ({ size, units, deposit, expectEnabled }) => {
    renderModal(makeModel(size));
    fillBasicInfo();
    goToTradeInfo();
    fillTradeInfo({ modelId: "m-1", units, deposit });
    fireEvent.click(screen.getByRole("button", { name: /documents/i }));
    const submitBtn = screen.getByRole("button", { name: /onboard client/i });
    if (expectEnabled) expect(submitBtn).toBeEnabled();
    else expect(submitBtn).toBeDisabled();
  });

  it("model_size unknown/null for the selected model is treated as 0 (any non-negative deposit passes, no NaN/crash)", async () => {
    renderModal(makeModel(undefined));
    fillBasicInfo();
    goToTradeInfo();
    expect(() => fillTradeInfo({ modelId: "m-1", units: "3", deposit: "0" })).not.toThrow();
    fireEvent.click(screen.getByRole("button", { name: /documents/i }));
    const submitBtn = screen.getByRole("button", { name: /onboard client/i });
    expect(submitBtn).toBeEnabled();
    expect(submitBtn.textContent).not.toMatch(/nan/i);
  });

  it("an empty Initial Cash Deposit keeps the form invalid", async () => {
    renderModal(makeModel(100_000));
    fillBasicInfo();
    goToTradeInfo();
    fillTradeInfo({ modelId: "m-1", units: "2", deposit: "" });
    fireEvent.click(screen.getByRole("button", { name: /documents/i }));
    expect(screen.getByRole("button", { name: /onboard client/i })).toBeDisabled();
  });
});

describe("FE-5 submitted payload", () => {
  it("includes initial_cash_deposit as a plain number matching the typed value", async () => {
    const startOnboarding = vi.fn().mockResolvedValue({ success: true, id: "ob-1" });
    renderModal(makeModel(100_000), startOnboarding);
    fillBasicInfo();
    goToTradeInfo();
    fillTradeInfo({ modelId: "m-1", units: "2", deposit: "250000" });
    fireEvent.click(screen.getByRole("button", { name: /documents/i }));
    fireEvent.click(screen.getByRole("button", { name: /onboard client/i }));

    await waitFor(() => expect(startOnboarding).toHaveBeenCalled());
    const payload = startOnboarding.mock.calls[0][0] as Record<string, unknown>;
    expect(payload.initial_cash_deposit).toBe(250000);
    expect(typeof payload.initial_cash_deposit).toBe("number");
  });
});

describe("FE-5 controlled-input pattern (matches modelUnit's existing convention)", () => {
  it("strips non [\\d.] characters as they're typed, same as the Model Unit field", () => {
    renderModal(makeModel(100_000));
    goToTradeInfo();
    const depositInput = screen.getByPlaceholderText("e.g. 250000") as HTMLInputElement;
    fireEvent.change(depositInput, { target: { value: "25a0,000" } });
    expect(depositInput.value).toBe("250000");
  });
});
