# Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-be.md §BE-5.
# Regenerate: /test-gen thorough docs/implementations/019-admin-access-control-and-staff-enrollment-be.md
#
# Pre-implementation note: app/libs/auth/deps.py's require_action TODAY still
# resolves via `get_actions_for_role(AdminRole(profile.role))` against the
# hardcoded `ROLE_ACTIONS` dict in app/libs/auth/actions.py -- it never looks at
# `page_access` / `page_access_overrides` at all (BE-5 is unimplemented; there is
# no `app/libs/access/resolver.py` yet). Every test below that seeds a
# `page_access` row and expects the *DB* row to be authoritative is expected to
# FAIL: the real behaviour today is governed entirely by ROLE_ACTIONS, so
# seeded page_access rows are silently ignored. Distinct expected failure
# modes, called out per test:
#   - "synthetic VIEW-only row on pc.model-management should still 403 the
#     PATCH" -> FAILS (200 instead of 403): ROLE_ACTIONS grants PC's
#     MODEL_MANAGE unconditionally today, so the synthetic page_access VIEW
#     row is simply never consulted and the write goes through anyway.
#   - "PC x PTA seeded VIEW should now allow a read that ROLE_ACTIONS denies"
#     -> FAILS (403 instead of 200) because ROLE_ACTIONS has no entry at all
#     for that (role, action) pair.
#   - "empty page_access -> 403 for EVERY role incl. ADMIN" -> FAILS for every
#     role ROLE_ACTIONS currently grants the action to (ADMIN/RM/MOBO/PC/
#     COMPLIANCE); PM is the one role that already has an empty ROLE_ACTIONS
#     set, so it coincidentally already 403s.
#   - "ROLE_ACTIONS / get_actions_for_role gone" -> FAILS (both still exist).
#   - "query budget == 3" -> FAILS (actual budget today is 1: only the
#     AdminProfileRepository lookup; get_actions_for_role is a pure dict read).
#
# Layer isolation: no sibling-layer (DB/FE) imports. `app.models.access`'s
# PageAccess/PageAccessOverride ORM classes ARE in this layer's own tree
# (api-backend/app/models/access.py, already committed by the DB layer's own
# work per its own migration/model files) -- consuming them as the frozen §7
# seam's row shape is exactly what §8.1 calls "DB rows" seam mocks, not a
# cross-layer import of TypeScript or a sibling branch.
#
# The two named HTTP-level cases use TestClient + app.dependency_overrides,
# reusing this directory's shared `http_client` fixture (tests/libs/auth/
# conftest.py, 019 section) built on the same pattern as
# app/libs/trade_models/test_router_symbols.py. The broader fail-closed /
# invariant sweep calls `require_action(...)`'s returned dependency directly
# with a plain User + Session, exactly as test_be9_status_gate_wiring.py (004)
# already does for get_current_admin_user/get_current_client_user in this same
# directory -- Depends() markers are irrelevant when the closure is invoked as
# a plain function.

from __future__ import annotations

from sqlalchemy import event

import pytest
from fastapi import HTTPException

from app.libs.auth import actions as actions_module
from app.libs.auth.actions import Action
from app.libs.auth.deps import get_current_admin_user, require_action
from app.models.access import AccessLevel
from app.models.pc import Model
from app.models.users import AdminRole
from tests.libs.auth.conftest import make_admin_user, make_page_access_row


# --- The named shipping case: PC x mobo.post-trade-allocation @ view (D-10) --


def test_pc_pta_view_case_shipping(http_client, monkeypatch):
    """PC x `mobo.post-trade-allocation` seeded `view` (the one cell ruled on
    individually, D-10): reads 200, POST /run 403. Business-logic isolation:
    PostTradeAllocationService.get_view is monkeypatched to a fixed view so
    this test proves the AUTH GUARD, not proposal 011's PTA business logic
    (which owns its own tests) -- feeding real run/allocation rows here would
    couple a BE-5 auth test to a sibling feature's fixture shape."""
    http, SessionFactory = http_client
    seed_db = SessionFactory()
    pc_user = make_admin_user(seed_db, firebase_uid="uid-pc-pta", role=AdminRole.PC)
    make_page_access_row(
        seed_db, page_id="mobo.post-trade-allocation", role=AdminRole.PC, level=AccessLevel.VIEW
    )
    seed_db.close()

    from app.schemas.post_trade_allocation import PostTradeAllocationView
    from app.libs.post_trade_allocation.service import PostTradeAllocationService

    monkeypatch.setattr(
        PostTradeAllocationService,
        "get_view",
        lambda self, trade_date=None: PostTradeAllocationView(
            tradeDate="2026-01-01", grandTotal=0.0, models=[]
        ),
    )

    from app.main import app

    app.dependency_overrides[get_current_admin_user] = lambda: pc_user
    try:
        assert http.get("/api/mobo/post-trade-allocation").status_code == 200
        assert http.get("/api/mobo/post-trade-allocation/runs").status_code == 200
        assert (
            http.get(
                "/api/mobo/post-trade-allocation/history",
                params={"from_date": "2026-01-01", "to_date": "2026-01-31"},
            ).status_code
            == 200
        )
        assert http.post("/api/mobo/post-trade-allocation/run").status_code == 403
    finally:
        app.dependency_overrides.pop(get_current_admin_user, None)


def test_pc_synthetic_view_grant_on_model_management(http_client):
    """The second, hand-constructed VIEW case (§8.3 BE-5 positive/negative):
    a synthetic `view`-only page_access row on `pc.model-management` -> the PC
    caller's read succeeds and the write is denied, even though PC's role
    otherwise holds full model-management access today."""
    http, SessionFactory = http_client
    seed_db = SessionFactory()
    pc_user = make_admin_user(seed_db, firebase_uid="uid-pc-synth", role=AdminRole.PC)
    make_page_access_row(
        seed_db, page_id="pc.model-management", role=AdminRole.PC, level=AccessLevel.VIEW
    )
    model = Model(name="Synthetic Model")
    seed_db.add(model)
    seed_db.commit()
    seed_db.refresh(model)
    model_id = str(model.id)
    seed_db.close()

    from app.main import app

    app.dependency_overrides[get_current_admin_user] = lambda: pc_user
    try:
        assert http.get("/api/pc/models").status_code == 200
        # NOTE: expected to currently FAIL with 200, not 403 -- ROLE_ACTIONS
        # grants PC's MODEL_MANAGE unconditionally today, so this synthetic
        # page_access VIEW row is simply never consulted and the write goes
        # through. This assertion only becomes a genuine proof of the VIEW
        # level once BE-5 makes page_access authoritative (see file header).
        resp = http.patch(f"/api/pc/models/{model_id}", json={"name": "Changed"})
        assert resp.status_code == 403
    finally:
        app.dependency_overrides.pop(get_current_admin_user, None)


# --- Fail-closed sweep: empty page_access -> 403 for EVERY role, incl. ADMIN -


@pytest.mark.parametrize(
    "role, action",
    [
        (AdminRole.RM, Action.CLIENT_VIEW),
        (AdminRole.MOBO, Action.RECON_VIEW),
        (AdminRole.PM, Action.MODEL_VIEW),
        (AdminRole.PC, Action.MODEL_VIEW),
        (AdminRole.COMPLIANCE, Action.ONBOARDING_REVIEW),
        (AdminRole.ADMIN, Action.MODEL_VIEW),
    ],
    ids=lambda v: getattr(v, "name", v),
)
def test_fail_closed_with_empty_page_access_for_every_role(session, role, action):
    """C-2 / D-9: with `page_access` empty (the un-migrated-DB simulation --
    this in-memory DB never gets a page_access row in this test), every guarded
    route denies for every role, ADMIN included -- no ROLE_ACTIONS-style
    fallback of any kind."""
    user = make_admin_user(session, firebase_uid=f"uid-{role.value.lower()}-empty", role=role)
    dep = require_action(action)
    with pytest.raises(HTTPException) as exc_info:
        dep(user=user, db=session)
    assert exc_info.value.status_code == 403


def test_no_admin_profile_still_403_no_admin_profile(session):
    """Unchanged by BE-5 (contract explicitly keeps this branch): a staged
    admin user with no admin_profiles row gets a distinct 403, not an empty
    action set silently resolved."""
    user = make_admin_user(session, firebase_uid="uid-no-profile", with_profile=False)
    dep = require_action(Action.MODEL_VIEW)
    with pytest.raises(HTTPException) as exc_info:
        dep(user=user, db=session)
    assert exc_info.value.status_code == 403
    assert exc_info.value.detail == "No admin profile"


def test_403_detail_string_byte_identical_to_pre_019(session):
    """The denial message text must not change shape -- the FE displays it
    verbatim (§ Layer 3 B)."""
    user = make_admin_user(session, firebase_uid="uid-rm-detail", role=AdminRole.RM)
    dep = require_action(Action.MODEL_VIEW)  # RM never holds MODEL_VIEW
    with pytest.raises(HTTPException) as exc_info:
        dep(user=user, db=session)
    assert (
        exc_info.value.detail
        == f"Action '{Action.MODEL_VIEW}' not permitted for your role."
    )


# --- ROLE_ACTIONS / get_actions_for_role fully deleted -----------------------


def test_role_actions_dict_no_longer_exists():
    assert not hasattr(actions_module, "ROLE_ACTIONS")


def test_get_actions_for_role_no_longer_exists():
    assert not hasattr(actions_module, "get_actions_for_role")


# --- Query budget -------------------------------------------------------------


def test_query_budget_is_three_queries_per_guarded_request(session):
    """§6 BE-5: 'Query budget per guarded request: 3 (profile + role levels +
    overrides), up from 1.' Counted via a `before_cursor_execute` listener on
    the session's own bound engine -- no ORM-level query-count helper exists
    in this codebase, so this is the plainest correct instrument."""
    user = make_admin_user(session, firebase_uid="uid-pc-budget", role=AdminRole.PC)
    make_page_access_row(
        session, page_id="pc.model-management", role=AdminRole.PC, level=AccessLevel.EDIT
    )
    engine = session.get_bind()
    counter = {"n": 0}

    def _count(*_args, **_kwargs):
        counter["n"] += 1

    event.listen(engine, "before_cursor_execute", _count)
    try:
        require_action(Action.MODEL_VIEW)(user=user, db=session)
    finally:
        event.remove(engine, "before_cursor_execute", _count)

    assert counter["n"] == 3


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
