"""Shared fixtures/factories for tests/libs/post_trade_allocation tests.

Generated by test-gen (thorough) from
docs/implementations/011-2026-07-13-post-trade-allocation-be.md.
Regenerate: /test-gen thorough docs/implementations/011-2026-07-13-post-trade-allocation-be.md

Layer isolation: only imports from app/libs/post_trade_allocation/, app/models/,
app/schemas/post_trade_allocation.py, and stdlib/pytest — no sibling -db/-fe code.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base
from app.core.flex_query import FlexRows, FlexUnavailable
from app.libs.post_trade_allocation import service as service_module
from app.models.pc import (
    AllocationModelSnapshot,
    AllocationPeriod,
    Model,
    ModelStatus,
    PeriodStatus,
)
from app.models.post_trade_allocation import (
    PostTradeAllocationRun,
    RunStatus,
    RunTrigger,
)
from app.models.reconciliation import Order
from app.models.users import Portal, User


@pytest.fixture
def engine():
    eng = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(eng)
    return eng


@pytest.fixture
def session(engine):
    Session = sessionmaker(bind=engine, expire_on_commit=False)
    db = Session()
    try:
        yield db
    finally:
        db.close()


def make_user(session, *, email: str = "client@example.com") -> User:
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"uid-{uuid.uuid4()}",
        email=email,
        portal=Portal.CLIENT,
    )
    session.add(user)
    session.flush()
    return user


def make_model(session, *, name: str = "Zero", status: ModelStatus = ModelStatus.LIVE) -> Model:
    model = Model(id=uuid.uuid4(), name=name, status=status)
    session.add(model)
    session.flush()
    return model


def make_confirmed_period(
    session, *, label: str = "P-CONFIRMED", confirmed_at: datetime | None = None
) -> AllocationPeriod:
    period = AllocationPeriod(
        id=uuid.uuid4(),
        label=label,
        status=PeriodStatus.CONFIRMED,
        # ponytail: default to 1 day ago so orders created after this call
        # naturally pass the ingested_at > confirmed_at filter
        confirmed_at=confirmed_at or (datetime.now(timezone.utc) - timedelta(days=1)),
    )
    session.add(period)
    session.flush()
    return period


def make_open_period(session, *, label: str = "P-OPEN") -> AllocationPeriod:
    period = AllocationPeriod(id=uuid.uuid4(), label=label, status=PeriodStatus.OPEN)
    session.add(period)
    session.flush()
    return period


def make_snapshot(
    session, *, period, model, user, multiplier, ib_account: str | None = "U-0001"
) -> AllocationModelSnapshot:
    snap = AllocationModelSnapshot(
        period_id=period.id,
        user_id=user.id,
        model_id=model.id,
        multiplier=Decimal(str(multiplier)),
        ib_account=ib_account,
    )
    session.add(snap)
    session.flush()
    return snap


def make_order(
    session,
    *,
    trade_date: str = "20260603",
    model: str = "Zero",
    proceeds,
    amount=None,
    account_id: str = "U-1234567",
    ingested_at=None,
    settle_date=None,
) -> Order:
    order = Order(
        id=uuid.uuid4(),
        tradeDate=trade_date,
        settleDate=settle_date,
        model=model,
        proceeds=Decimal(str(proceeds)),
        amount=Decimal(str(amount)) if amount is not None else Decimal(str(proceeds)),
        accountId=account_id,
        orderID=f"O-{uuid.uuid4()}",
        **({"ingested_at": ingested_at} if ingested_at is not None else {}),
    )
    session.add(order)
    session.flush()
    return order


# --- IB archive double -------------------------------------------------------
#
# run() is anchored on the IB flex archive: it only allocates a date whose
# stored statement carries trade records, and it will not scan past the newest
# such date. Tests must therefore declare an archive, or run() correctly does
# nothing. This double replaces StoredFetcher inside the service module.


class FakeArchive:
    """Stands in for StoredFetcher.

    By DEFAULT it mirrors the orders table: every date that has an order is a
    date IB delivered records for. That keeps the archive from being a thing
    every test has to think about, while still exercising the real rule that
    run() never allocates a date its source does not cover.

    Tests that are ABOUT the source declare it explicitly with use_archive():
    `empty` days are ones IB delivered a statement showing no trades, and a
    day in neither set was never delivered at all -- fetch() raises
    FlexUnavailable for it, which is what makes run() mark the date FAILED
    and retry it on the next scan.
    """

    session = None
    record_days = None  # None == derive from the orders table
    empty_days: set = set()

    @classmethod
    def _records(cls) -> set:
        if cls.record_days is not None:
            return cls.record_days
        if cls.session is None:
            return set()
        return {
            _as_date(t)
            for (t,) in cls.session.query(Order.tradeDate).distinct().all()
            if t
        }

    def days(self):
        return sorted(self._records(), reverse=True)

    def fetch(self, day):
        if day in self._records():
            return FlexRows(orders=[{"x": 1}], fills=[])
        if day in self.empty_days:
            return FlexRows(orders=[], fills=[])
        raise FlexUnavailable(f"no stored IB statement for {day}")


@pytest.fixture(autouse=True)
def fake_archive(session, monkeypatch):
    """Autouse so no test can reach the real crm_filesystem/ archive, or the
    real filesystem at all, through StoredFetcher."""
    FakeArchive.session = session
    FakeArchive.record_days = None
    FakeArchive.empty_days = set()
    monkeypatch.setattr(service_module, "StoredFetcher", FakeArchive)
    yield FakeArchive
    FakeArchive.session = None


def _as_date(token: str) -> date:
    return datetime.strptime(token, "%Y%m%d").date()


def use_archive(*, records=None, empty: tuple = ()) -> None:
    """Pin the archive explicitly, for tests that are about the source itself.

    `records=None` keeps the default (derive from the orders table).
    """
    FakeArchive.record_days = None if records is None else {_as_date(t) for t in records}
    FakeArchive.empty_days = {_as_date(t) for t in empty}


def make_floor_run(session, *, trade_date: str, period) -> PostTradeAllocationRun:
    """Seed one completed session row so the scan floor reaches back this far.

    The floor is MIN(trade_date) in the ledger (D4); on an empty ledger it
    collapses to the anchor, so a scan covering several dates needs an oldest
    date already present. This is the ledger's own bootstrap, not a fixture
    hack -- in production the first run establishes it the same way.
    """
    run = PostTradeAllocationRun(
        id=uuid.uuid4(),
        trade_date=trade_date,
        period_id=period.id,
        status=RunStatus.COMPLETED.value,
        trigger=RunTrigger.MANUAL.value,
        grand_total=Decimal("0"),
        run_by="floor@example.com",
    )
    session.add(run)
    session.flush()
    return run
