"""Generated by test-gen (thorough) from
docs/implementations/011-2026-07-13-post-trade-allocation-be.md §BE-3.
Regenerate: /test-gen thorough docs/implementations/011-2026-07-13-post-trade-allocation-be.md

PostTradeAllocationService.run() — the 5-step run. D-3 (signed proceeds, never
abs()) is safety-critical and gets the heaviest coverage here.

Run: .venv/Scripts/python.exe -m pytest -q tests/libs/post_trade_allocation/test_be3_service_run.py
"""

from __future__ import annotations

from decimal import Decimal

import pytest

from app.libs.post_trade_allocation.repository import PostTradeAllocationRepository
from app.libs.post_trade_allocation.service import PostTradeAllocationService
from app.models.post_trade_allocation import (
    ClientPortfolio,
    PostTradeAllocation,
    PostTradeAllocationRun,
    RunStatus,
    RunTrigger,
)
from tests.libs.post_trade_allocation.conftest import (
    make_confirmed_period,
    make_floor_run,
    make_model,
    make_open_period,
    make_order,
    make_snapshot,
    make_user,
    use_archive,
)


@pytest.fixture
def service(session):
    return PostTradeAllocationService(session)


# --- D-10: empty run -----------------------------------------------------------


def test_run_with_no_source_at_all_returns_none_and_writes_nothing(session, service):
    """A fresh install, not an error.

    The old contract wrote an EMPTY run dated today whenever there were no
    orders. That is a claim we cannot make without a statement: EMPTY means
    "IB says nothing traded", and with no archive we do not know. So run()
    does nothing and says so by returning None.
    """
    make_confirmed_period(session)  # period_id is NOT NULL — a run always needs one
    use_archive(records=())

    run = service.run(trigger=RunTrigger.MANUAL, actor="admin@example.com")

    assert run is None
    assert session.query(PostTradeAllocationRun).count() == 0
    assert session.query(PostTradeAllocation).count() == 0
    assert session.query(ClientPortfolio).count() == 0


def test_a_delivered_statement_with_no_trades_is_an_empty_run(session, service):
    """The other half of the same distinction: IB DID deliver, and it showed
    no trades, so the date is genuinely done and must not be retried."""
    make_confirmed_period(session)
    use_archive(records=(), empty=("20260603",))

    run = service._run_one_date(
        "20260603",
        period=service.repo.latest_confirmed_period(),
        trigger=RunTrigger.MANUAL,
        actor=None,
    )

    assert run.status == RunStatus.EMPTY.value
    assert run.grand_total == Decimal("0")
    assert session.query(PostTradeAllocation).count() == 0


def test_a_missing_statement_is_a_failed_run_that_comes_back(session, service):
    """D7: no statement means we do not know what happened, so the date stays
    pending and the next scan retries it. grand_total is NULL, not zero --
    zero would be a claim about a day we have no data for."""
    period = make_confirmed_period(session)
    use_archive(records=())  # 20260603 delivered nothing at all

    run = service._run_one_date(
        "20260603", period=period, trigger=RunTrigger.MANUAL, actor=None
    )

    assert run.status == RunStatus.FAILED.value
    assert run.grand_total is None
    assert service._pending_dates("20260603") == ["20260603"]  # retried


def test_anchor_is_resolved_once_and_does_not_drift_mid_scan(session, service):
    """"Must not shift while the process is running": a statement landing
    during a scan must not extend that scan's own reach."""
    make_confirmed_period(session)
    use_archive(records=("20260603",))

    first = service._resolve_anchor()
    use_archive(records=("20260603", "20260610"))  # archive grows mid-flight

    # _pending_dates is driven by the anchor passed in, never by a re-read.
    assert first == "20260603"
    assert service._pending_dates(first) == ["20260603"]


def test_empty_archive_resolves_to_no_anchor_rather_than_raising(session, service):
    """max([]) raises ValueError; a fresh install must not crash on it."""
    use_archive(records=())

    assert service._resolve_anchor() is None


# --- Core positive split --------------------------------------------------------


def test_run_pro_rata_split_matches_multiplier_ratio(session, service):
    model = make_model(session, name="Zero")
    user_a = make_user(session, email="a@example.com")
    user_b = make_user(session, email="b@example.com")
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user_a, multiplier=3)
    make_snapshot(session, period=period, model=model, user=user_b, multiplier=2)
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    cells = {c.user_id: c for c in session.query(PostTradeAllocation).filter_by(run_id=run.id)}
    assert cells[user_a.id].allocated == Decimal("60")
    assert cells[user_b.id].allocated == Decimal("40")
    assert cells[user_a.id].pct == Decimal("60.000")
    assert cells[user_b.id].pct == Decimal("40.000")


# The per-order marker column is gone (unit A4) -- there is nothing left to
# assert on here. A5's date-floor + gap scan is what makes a processed order
# not get re-picked up on the next run().


# Unit 13: client_portfolios is a frozen-but-readable placeholder now --
# upsert_portfolio_deltas no longer touches it (only DailyClientPortfolio),
# so the old "run() shifts ClientPortfolio.amount_in_trade" coverage that
# lived in this test is gone, not converted -- there is no replacement
# write to assert on.


# --- D-3: signed proceeds, safety-critical --------------------------------------


def test_run_losing_day_produces_negative_allocated(session, service):
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=-100)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert run.grand_total == Decimal("-100")
    cell = session.query(PostTradeAllocation).filter_by(run_id=run.id).one()
    assert cell.allocated == Decimal("-100")


def test_run_never_abs_never_sums_amount_instead_of_proceeds(session, service):
    """proceeds and amount diverge in sign; grand_total must follow proceeds only."""
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=-50, amount=999)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert run.grand_total == Decimal("-50")


def test_run_mixed_sign_orders_same_model_day_net_correctly(session, service):
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=150)
    make_order(session, trade_date="20260603", model="Zero", proceeds=-200)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert run.grand_total == Decimal("-50")


# --- Unresolvable model name -----------------------------------------------------


def test_run_unknown_model_name_creates_run_but_no_cells_no_portfolio(session, service):
    make_confirmed_period(session)  # period_id is NOT NULL — a run always needs one
    make_order(session, trade_date="20260603", model="Ghost", proceeds=100)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert run.status == RunStatus.COMPLETED.value
    assert session.query(PostTradeAllocation).count() == 0
    assert session.query(ClientPortfolio).count() == 0


# --- D-9 / Idempotency (C-2) ------------------------------------------------------
# ponytail (unit A4): both of these relied on the per-order marker column to
# tell a processed order from a new one across two run() calls -- that
# marker is gone, and until A5 lands the date-floor + gap scan, a second
# run() call simply re-processes every order the ingested_at cutoff still
# lets through.
# Dropped rather than weakened: asserting today's actual (regressed) output
# would bless behaviour this rework explicitly doesn't want kept. A5's own
# test rework (plan Part 4d) is where "late order, same day" and "no new
# orders is a no-op" coverage belongs once the ledger is the source of truth.


# --- D-5: split basis is the latest CONFIRMED period, never OPEN ----------------


def test_run_uses_latest_confirmed_period_not_open(session, service):
    model = make_model(session, name="Zero")
    user = make_user(session)
    open_period = make_open_period(session, label="P-OPEN")
    make_snapshot(session, period=open_period, model=model, user=user, multiplier=99)
    confirmed = make_confirmed_period(session, label="P-CONFIRMED")
    make_snapshot(session, period=confirmed, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    cell = session.query(PostTradeAllocation).filter_by(run_id=run.id).one()
    assert cell.units == Decimal("1")  # confirmed multiplier, not the open period's 99
    assert cell.allocated == Decimal("100")


def test_run_raises_when_no_confirmed_period_exists(session, service):
    """Corrected 2026-07-14: post_trade_allocation_runs.period_id is NOT NULL,
    so zero confirmed periods is a hard failure, not a degrade-gracefully case —
    run() must raise and write zero rows (of any kind)."""
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)

    with pytest.raises(RuntimeError):
        service.run(trigger=RunTrigger.MANUAL, actor=None)

    from app.models.post_trade_allocation import PostTradeAllocationRun

    assert session.query(PostTradeAllocationRun).count() == 0
    assert session.query(PostTradeAllocation).count() == 0


# --- Zero units_total edge case --------------------------------------------------


def test_run_model_with_no_subscribers_produces_run_but_no_cells(session, service):
    make_model(session, name="Zero")
    make_confirmed_period(session)  # confirmed period exists, but no snapshot rows for it
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)

    run = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert run.grand_total == Decimal("100")
    assert session.query(PostTradeAllocation).count() == 0


# --- Multiple distinct (tradeDate, model) pairs in one batch --------------------
# ponytail (unit A4): trade_date is now UNIQUE on post_trade_allocation_runs,
# but run() still creates one row per (tradeDate, model) pair (unchanged in
# this unit) -- so two DIFFERENT models trading on the SAME day would now
# raise IntegrityError on the second create_run() call. Verified data facts
# (plan) say this has never happened live (exactly 1 model per trade_date on
# all 785 existing orders), so this test covers two distinct dates instead
# of asserting the same-day case; A5 restructures run() to write one row per
# date (aggregating across models via cells), which is what actually closes
# this gap.


def test_two_models_on_one_day_share_a_single_session_row(session, service):
    """D5: the ledger is one session row per trading day, so a day on which
    two models traded nets into one row -- the per-model breakdown lives in
    post_trade_allocations, which is keyed (run_id, model_id, user_id)."""
    model_a = make_model(session, name="Alpha")
    model_b = make_model(session, name="Beta")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model_a, user=user, multiplier=1)
    make_snapshot(session, period=period, model=model_b, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Alpha", proceeds=100)
    make_order(session, trade_date="20260603", model="Beta", proceeds=200)

    service.run(trigger=RunTrigger.MANUAL, actor=None)

    runs = session.query(PostTradeAllocationRun).all()
    assert len(runs) == 1
    assert runs[0].trade_date == "20260603"
    assert runs[0].grand_total == Decimal("300")  # signed day total across models
    assert {c.model_id for c in session.query(PostTradeAllocation).all()} == {
        model_a.id,
        model_b.id,
    }


def test_each_date_gets_its_own_session_row_oldest_first(session, service):
    """Dates are processed oldest-first: the portfolio balance is a running
    total, so write order is chain order."""
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)
    make_order(session, trade_date="20260604", model="Zero", proceeds=200)
    make_floor_run(session, trade_date="20260602", period=period)

    assert service._pending_dates("20260604") == ["20260603", "20260604"]

    service.run(trigger=RunTrigger.MANUAL, actor=None)

    rows = (
        session.query(PostTradeAllocationRun)
        .filter(
            PostTradeAllocationRun.status == RunStatus.COMPLETED.value,
            PostTradeAllocationRun.trade_date > "20260602",  # exclude the seeded floor
        )
        .order_by(PostTradeAllocationRun.trade_date)
        .all()
    )
    assert [(r.trade_date, r.grand_total) for r in rows] == [
        ("20260603", Decimal("100")),
        ("20260604", Decimal("200")),
    ]


def test_weekends_are_never_scanned(session, service):
    """D2: ingest runs Mon-Fri, so a weekend with no statement is expected,
    not a gap. 20260606/07 are a Saturday and Sunday."""
    period = make_confirmed_period(session)
    make_floor_run(session, trade_date="20260605", period=period)  # Friday

    assert service._pending_dates("20260608") == ["20260608"]  # Monday only


def test_a_date_already_completed_is_not_run_again(session, service):
    """Idempotency without a per-order marker: the ledger alone decides."""
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)

    service.run(trigger=RunTrigger.MANUAL, actor=None)
    cells_after_first = session.query(PostTradeAllocation).count()
    second = service.run(trigger=RunTrigger.MANUAL, actor=None)

    assert second is None
    assert session.query(PostTradeAllocationRun).count() == 1
    assert session.query(PostTradeAllocation).count() == cells_after_first


# --- Atomicity / rollback safety --------------------------------------------------


def test_run_exception_before_commit_leaves_no_cells(session, service, monkeypatch):
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    order = make_order(session, trade_date="20260603", model="Zero", proceeds=100)
    session.commit()  # seed data must be committed — run()'s own rollback is a savepoint,
    # not a fresh session; without this, session.rollback() below would also wipe the arrange step.

    def _boom(*args, **kwargs):
        raise RuntimeError("simulated failure mid-run")

    monkeypatch.setattr(service.repo, "write_cells", _boom)

    with pytest.raises(RuntimeError):
        service.run(trigger=RunTrigger.MANUAL, actor=None)

    session.rollback()
    session.refresh(order)
    assert session.query(PostTradeAllocation).count() == 0


def test_run_after_rollback_is_safely_retryable(session, service, monkeypatch):
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260603", model="Zero", proceeds=100)
    session.commit()  # see note in test_run_exception_before_commit_leaves_orders_unmarked

    original_write_cells = PostTradeAllocationRepository.write_cells
    call_count = {"n": 0}

    def _fail_once(self, rows):
        call_count["n"] += 1
        if call_count["n"] == 1:
            raise RuntimeError("simulated failure")
        return original_write_cells(self, rows)

    monkeypatch.setattr(PostTradeAllocationRepository, "write_cells", _fail_once)

    with pytest.raises(RuntimeError):
        service.run(trigger=RunTrigger.MANUAL, actor=None)
    session.rollback()

    retry_run = service.run(trigger=RunTrigger.MANUAL, actor=None)
    assert retry_run.status == RunStatus.COMPLETED.value
    assert retry_run.grand_total == Decimal("100")


# --- Period boundary filter -----------------------------------------------------


def test_dates_below_the_floor_are_never_swept_in(session, service):
    """The ingested_at > confirmed_at cutoff is gone; the floor replaces it.

    Floor is MIN(trade_date) in the ledger (D4), so history older than the
    first run it ever did stays untouched -- which is what keeps the 217
    pre-ledger orders in the live DB from suddenly allocating themselves.
    """
    model = make_model(session, name="Zero")
    user = make_user(session)
    period = make_confirmed_period(session)
    make_snapshot(session, period=period, model=model, user=user, multiplier=1)
    make_order(session, trade_date="20260602", model="Zero", proceeds=999)  # below floor
    make_order(session, trade_date="20260604", model="Zero", proceeds=50)
    make_floor_run(session, trade_date="20260603", period=period)

    assert "20260602" not in service._pending_dates("20260604")

    service.run(trigger=RunTrigger.MANUAL, actor=None)

    completed = (
        session.query(PostTradeAllocationRun)
        .filter(
            PostTradeAllocationRun.status == RunStatus.COMPLETED.value,
            PostTradeAllocationRun.trade_date > "20260603",  # exclude the seeded floor
        )
        .all()
    )
    assert [(r.trade_date, r.grand_total) for r in completed] == [("20260604", Decimal("50"))]
    # the below-floor date was never even considered
    assert session.query(PostTradeAllocationRun).filter_by(trade_date="20260602").count() == 0


def test_an_empty_ledger_scans_only_the_anchor(session, service):
    """D4: with no runs at all the floor collapses to the anchor, so a
    first-ever run covers one date instead of sweeping in all of history."""
    make_confirmed_period(session)
    use_archive(records=("20260601", "20260602", "20260603"))

    assert service._pending_dates("20260603") == ["20260603"]


# settle_date is gone (unit A4, plan D8) -- post_trade_allocation_runs no
# longer carries it, so there is nothing left to assert here.
