"""Generated by test-gen (thorough) from
docs/implementations/011-2026-07-13-post-trade-allocation-be.md §BE-6.
Regenerate: /test-gen thorough docs/implementations/011-2026-07-13-post-trade-allocation-be.md

PostTradeAllocationService GET-path assembly: get_view / list_runs. Reads
exclusively from post_trade_allocation_runs / post_trade_allocations — never
re-derives from orders.

Run: .venv/Scripts/python.exe -m pytest -q tests/libs/post_trade_allocation/test_be6_service_view.py
"""

from __future__ import annotations

import uuid
from decimal import Decimal

import pytest
from app.libs.post_trade_allocation.repository import PostTradeAllocationRepository
from app.libs.post_trade_allocation.service import PostTradeAllocationService
from app.models.post_trade_allocation import RunStatus, RunTrigger

from tests.libs.post_trade_allocation.conftest import make_confirmed_period, make_model, make_user


@pytest.fixture
def service(session):
    return PostTradeAllocationService(session)


@pytest.fixture
def repo(session):
    return PostTradeAllocationRepository(session)


def _seed_completed_run(
    session, repo, *, model, user, trade_date, traded, trigger=RunTrigger.MANUAL
):
    # ponytail: post_trade_allocation_runs.period_id is NOT NULL (DB-1/DB-5) —
    # a confirmed period must exist before any run row can be written, same
    # narrow fix authorized for BE-3's own test seeding. Unique label per call
    # since allocation_periods.label is unique and one test may seed >1 run.
    period = make_confirmed_period(session, label=f"P-CONFIRMED-{uuid.uuid4()}")
    run = repo.create_run(
        trade_date=trade_date,
        period_id=period.id,
        status=RunStatus.COMPLETED.value,
        trigger=trigger.value,
        grand_total=Decimal(str(traded)),
        run_by=None,
    )
    repo.write_cells(
        [
            {
                "run_id": run.id,
                "model_id": model.id,
                "user_id": user.id,
                "model_traded": Decimal(str(traded)),
                "units": Decimal("1"),
                "units_total": Decimal("1"),
                "allocated": Decimal(str(traded)),
                "pct": Decimal("100.000"),
                "ib_account": "U-1234567",
                "model_name": model.name,
                "model_acct": "U-1234567",
            }
        ]
    )
    session.commit()
    return run


def _seed_empty_run(session, repo, *, trade_date, trigger=RunTrigger.MANUAL):
    # ponytail: same NOT-NULL period_id fix as _seed_completed_run above.
    period = make_confirmed_period(session, label=f"P-CONFIRMED-{uuid.uuid4()}")
    run = repo.create_run(
        trade_date=trade_date,
        period_id=period.id,
        status=RunStatus.EMPTY.value,
        trigger=trigger.value,
        grand_total=Decimal("0"),
        run_by=None,
    )
    return run


# --- get_view --------------------------------------------------------------------


def test_get_view_returns_none_for_date_with_no_run(service):
    assert service.get_view("20990101") is None


def test_get_view_returns_none_for_date_with_only_empty_run(session, repo, service):
    _seed_empty_run(session, repo, trade_date="20260604")
    session.commit()
    assert service.get_view("20260604") is None


def test_get_view_returns_latest_non_empty_trade_date_when_no_date_given(session, repo, service):
    model = make_model(session)
    user = make_user(session)
    _seed_completed_run(session, repo, model=model, user=user, trade_date="20260601", traded=100)
    _seed_completed_run(session, repo, model=model, user=user, trade_date="20260603", traded=200)

    view = service.get_view()
    assert view.tradeDate == "2026-06-03"


# ponytail (unit A4): D-9 ("late-arriving order for the same tradeDate/model
# creates a second run row, get_view sums across both") is retired --
# trade_date is now UNIQUE on post_trade_allocation_runs, so a second run
# row for a date that already has one can no longer be written. The
# multi-run-per-date seeding this test relied on is impossible now; there is
# nothing left to sum across.


def test_get_view_never_recomputes_from_orders(session, repo, service):
    """The run already froze the split; a stray/contradictory Order row for the
    same tradeDate/model must not change what get_view reports."""
    from tests.libs.post_trade_allocation.conftest import make_order

    model = make_model(session)
    user = make_user(session)
    _seed_completed_run(session, repo, model=model, user=user, trade_date="20260603", traded=100)
    # An unallocated order that would sum to a very different total if get_view
    # (incorrectly) re-aggregated from `orders` instead of reading the frozen cells.
    make_order(session, trade_date="20260603", model=model.name, proceeds=999999)
    session.commit()

    view = service.get_view("20260603")
    assert view.grandTotal == 100.0


def test_get_view_requested_date_with_no_runs_at_all_returns_none(service):
    assert service.get_view("20260603") is None


# settle_date / settleDay are gone (unit A4, plan D8) -- get_view's view no
# longer carries a settle-day field to test.


# --- list_runs ---------------------------------------------------------------------


def test_list_runs_default_excludes_empty(session, repo, service):
    model = make_model(session)
    user = make_user(session)
    _seed_completed_run(session, repo, model=model, user=user, trade_date="20260603", traded=100)
    _seed_empty_run(session, repo, trade_date="20260604")
    session.commit()

    result = service.list_runs()
    dates = {r.date for r in result.runs}
    assert dates == {"2026-06-03"}


def test_list_runs_include_empty_true_includes_both(session, repo, service):
    model = make_model(session)
    user = make_user(session)
    _seed_completed_run(session, repo, model=model, user=user, trade_date="20260603", traded=100)
    _seed_empty_run(session, repo, trade_date="20260604")
    session.commit()

    result = service.list_runs(include_empty=True)
    dates = {r.date for r in result.runs}
    assert dates == {"2026-06-03", "2026-06-04"}


# ponytail (unit A4): this used to seed two runs on the SAME trade_date to
# prove list_runs collapses them into one entry -- trade_date is UNIQUE now,
# so that seeding is impossible and "one entry per date" is guaranteed by
# the schema itself rather than something this layer needs to prove.
def test_list_runs_one_entry_per_trade_date(session, repo, service):
    model = make_model(session)
    user = make_user(session)
    _seed_completed_run(
        session,
        repo,
        model=model,
        user=user,
        trade_date="20260603",
        traded=100,
        trigger=RunTrigger.MANUAL,
    )
    _seed_completed_run(
        session,
        repo,
        model=model,
        user=user,
        trade_date="20260604",
        traded=50,
        trigger=RunTrigger.SCHEDULED,
    )

    result = service.list_runs()
    assert len(result.runs) == 2
    assert {r.grandTotal for r in result.runs} == {100.0, 50.0}


def test_list_runs_empty_database_returns_empty_list(service):
    result = service.list_runs()
    assert result.runs == []
