// Generated by test-gen (standard) from docs/implementations/017-transaction-details-wiring-fe.md §FE-1. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-1 only adds 2 new DTO interfaces and
// widens AllotRdmptDTO with a required `has_transaction_detail: boolean` —
// there is no runtime behavior to exercise. The meaningful assertions here
// are compile-time (tsc --noEmit, part of the layer's CI gate); this file's
// runtime bodies just prove the literals are assignable and pass through
// unchanged.
import { describe, expect, it } from "vitest";
import type { AllotRdmptDTO, TransactionDetailDTO, TransactionDetailRequest } from "@/lib/onboarding/types";

describe("FE-1 TransactionDetailRequest", () => {
  it("accepts all pinned fields, with reference_no populated", () => {
    const req: TransactionDetailRequest = {
      bank_account: "HSBC-4471-001",
      settlement_amount: 180_000,
      transaction_date: "2026-08-01",
      transaction_time: "14:30",
      currency: "USD",
      reference_no: "TXN-20260801-001",
    };
    expect(typeof req.settlement_amount).toBe("number");
    expect(req.reference_no).toBe("TXN-20260801-001");
  });

  it("allows reference_no to be omitted (optional field)", () => {
    const req: TransactionDetailRequest = {
      bank_account: "HSBC-4471-001",
      settlement_amount: 180_000,
      transaction_date: "2026-08-01",
      transaction_time: "14:30",
      currency: "USD",
    };
    expect(req.reference_no).toBeUndefined();
  });
});

describe("FE-1 TransactionDetailDTO", () => {
  it("type-checks with all pinned fields, including a null reference_no", () => {
    const dto: TransactionDetailDTO = {
      id: "td-1",
      allotment_id: "a-1",
      bank_account: "HSBC-4471-001",
      settlement_amount: 180_000,
      transaction_date: "2026-08-01",
      transaction_time: "14:30",
      currency: "USD",
      reference_no: null,
      filed_by: "rm-firebase-uid",
      filed_at: "2026-08-01T14:31:00Z",
    };
    expect(typeof dto.settlement_amount).toBe("number");
    expect(dto.reference_no).toBeNull();
  });
});

describe("FE-1 widened AllotRdmptDTO", () => {
  const BASE = {
    id: "a1", reference: "REF-1", model_id: "m1", model_name: "Model A", units: 2, amount: 200_000,
    kind: "allotment" as const, status: "pending" as const, note: null, agg_before: 0, agg_after: 2,
    expected_cash_in: "2026-08-01", rm: "Jane", created_at: "2026-07-22T00:00:00Z", acknowledged_at: null,
    emergent: false, expected_cash_out: null, decided_by: null, decided_at: null, reject_reason: null,
  };

  it("requires has_transaction_detail: boolean — true for an already-filed row", () => {
    const dto: AllotRdmptDTO = { ...BASE, has_transaction_detail: true };
    expect(dto.has_transaction_detail).toBe(true);
  });

  it("requires has_transaction_detail: boolean — false for an unfiled row", () => {
    const dto: AllotRdmptDTO = { ...BASE, has_transaction_detail: false };
    expect(dto.has_transaction_detail).toBe(false);
  });

  // Negative — omitting the new required field is a compile-time error, not a
  // runtime one; asserted via a @ts-expect-error line so `tsc --noEmit` fails
  // if the field ever silently becomes optional.
  it("omitting has_transaction_detail is rejected at compile time", () => {
    // @ts-expect-error has_transaction_detail is required on AllotRdmptDTO
    const bad: AllotRdmptDTO = { ...BASE };
    expect(bad.id).toBe("a1");
  });
});
