// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-4 (mapper half).
// Regenerate: /test-gen standard.
import { describe, expect, it } from "vitest";
import { mapOnboardingToRow, docStatusToVerdict } from "@/lib/onboarding/mappers";
import type { DocStatus, OnboardingDTO, OnboardingStatus } from "@/lib/onboarding/types";

function makeOnboarding(status: OnboardingStatus): OnboardingDTO {
  return {
    id: "ob-1", user_id: "u-1",
    client_name: "Jane Doe", email: "jane@example.com", assigned_rm: "Alice RM",
    client_ref: "MEGA-0481",
    primary_phone: "+852 1234 5678", address: "1 Main St", country_of_residence: "HK",
    id_type: "passport", id_number: "P123456",
    client_ib: "U-1000001", sw_account: "SW-2000001",
    status, kind: "renewal",
    model_id: "m-1", model_name: "Zero", units: 5,
    mgmt_fee: 0.015, incentive_fee: 0.2,
    verified_count: 7, required_count: 7,
    reject_reason: status === "pending_review" ? "bad ID scan" : null,
    submitted_at: "2026-07-19T00:00:00Z", created_at: "2026-07-18T00:00:00Z",
    documents: [],
  };
}

describe("FE-4 OB_STATUS_MAP (via mapOnboardingToRow)", () => {
  it.each([
    ["reviewing", "pending"],
    ["pending_review", "rejected"],
    ["active", "approved"],
  ] as const)("maps OnboardingStatus %s to ObStatus %s per §4.2", (dbStatus, obStatus) => {
    const row = mapOnboardingToRow(makeOnboarding(dbStatus));
    expect(row.status).toBe(obStatus);
  });

  it("maps client/email/rm/clientRef/type and the widened D-9 fields straight through, no '—' fallback", () => {
    const row = mapOnboardingToRow(makeOnboarding("reviewing"));
    expect(row.client).toBe("Jane Doe");
    expect(row.email).toBe("jane@example.com");
    expect(row.phone).toBe("+852 1234 5678");
    expect(row.address).toBe("1 Main St");
    expect(row.country).toBe("HK");
    expect(row.idType).toBe("passport");
    expect(row.idNumber).toBe("P123456");
    expect(row.ibhk).toBe("U-1000001");
    expect(row.silverwate).toBe("SW-2000001");
    expect(row.rm).toBe("Alice RM");
    expect(row.clientRef).toBe("MEGA-0481");
    expect(row.type).toBe("Yearly Renewal");
  });

  it("passes rejectReason through from reject_reason", () => {
    const row = mapOnboardingToRow(makeOnboarding("pending_review"));
    expect(row.rejectReason).toBe("bad ID scan");
  });
});

describe("FE-4 docStatusToVerdict", () => {
  it.each([
    ["verified", "valid"],
    ["rejected", "issue"],
    ["not_started", null],
    ["uploaded", null],
    ["in_review", null],
    ["expired", null],
  ] as [DocStatus, "valid" | "issue" | null][])("maps DocStatus %s to verdict %s", (status, expected) => {
    expect(docStatusToVerdict(status)).toBe(expected);
  });
});
