// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-5 (mapper half).
// Regenerate: /test-gen standard.
import { describe, expect, it } from "vitest";
import { mapAllotmentsToView } from "@/lib/onboarding/mappers";
import type { AllotRdmptDTO } from "@/lib/onboarding/types";

const ALLOTMENT: AllotRdmptDTO = {
  id: "al-1", reference: "AL-3F9A2C",
  model_id: "m-1", model_name: "Zero", units: 5, amount: 1_000_000,
  kind: "allotment", status: "pending", note: "initial allotment",
  agg_before: 2, agg_after: 5,
  expected_cash_in: "2026-08-01T00:00:00Z",
  rm: "Alice RM", created_at: "2026-07-18T00:00:00Z", acknowledged_at: null,
};

describe("FE-5 mapAllotmentsToView", () => {
  it("passes aggBefore/aggAfter/expectedCashIn through verbatim from the DTO (D-9) — no derivation", () => {
    const [view] = mapAllotmentsToView([ALLOTMENT]);
    expect(view.aggBefore).toBe(2);
    expect(view.aggAfter).toBe(5);
    expect(view.expectedCashIn).toBe("2026-08-01T00:00:00Z");
  });

  it("passes amount/ref/modelName through verbatim, with zero client-side computation", () => {
    const [view] = mapAllotmentsToView([ALLOTMENT]);
    expect(view.amount).toBe(1_000_000);
    expect(view.ref).toBe("AL-3F9A2C");
    expect(view.modelName).toBe("Zero");
    expect(view.mult).toBe(5);
  });

  it("performs no aggregate arithmetic across multiple rows sharing a model_id", () => {
    const second: AllotRdmptDTO = { ...ALLOTMENT, id: "al-2", agg_before: 5, agg_after: 8 };
    const [v1, v2] = mapAllotmentsToView([ALLOTMENT, second]);
    expect(v1.aggBefore).toBe(2);
    expect(v1.aggAfter).toBe(5);
    expect(v2.aggBefore).toBe(5);
    expect(v2.aggAfter).toBe(8);
  });

  it("returns an empty array for an empty input with no crash", () => {
    expect(mapAllotmentsToView([])).toEqual([]);
  });
});
