// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-1.
// Regenerate: /test-gen standard.
import { afterEach, describe, expect, it, vi } from "vitest";

// server/api-client.ts imports "server-only" + "next/headers" (cookies()).
// Neither resolves under Vitest/jsdom — stub both so the real apiClient
// runs unmodified against a mocked global fetch (the §7.1 seam).
vi.mock("server-only", () => ({}));
vi.mock("next/headers", () => ({
  cookies: () => Promise.resolve({ get: () => undefined }),
}));

import { getReconciliation } from "@/server/mobo";
import { ENDPOINTS } from "@/server/endpoints";
import type { ReconciliationFlowViewDTO } from "@/lib/mobo/flow-types";

const FLOW_DTO: ReconciliationFlowViewDTO = {
  settleDay: "03 Jun 2026",
  orders: [
    {
      id: "o1", m: "mA", inst: "AAPL US", cat: "Equity", side: "Buy",
      qty: "12,000", px: "$187.40", not: "$2.25M", notVal: 2_250_000,
      ref: "TRD-88142", ib: "IB-40118", st: "ok",
      execs: [{ id: "x1", qty: "12,000", px: "$187.40", t: "09:31:02", st: "ok" }],
    },
  ],
  allocs: [],
  ports: [],
  algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
  counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
};

function mockFetchOnce(body: unknown, status = 200) {
  global.fetch = vi.fn().mockResolvedValue({
    ok: status < 300,
    status,
    json: async () => body,
    text: async () => JSON.stringify(body),
  }) as unknown as typeof fetch;
}

function calledUrl(): string {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][0] as string;
}

describe("FE-1 server/mobo getReconciliation", () => {
  afterEach(() => vi.restoreAllMocks());

  it("getReconciliation() with no session id hits the bare RECONCILIATION path", async () => {
    mockFetchOnce(FLOW_DTO);
    const result = await getReconciliation();
    expect(calledUrl().endsWith(ENDPOINTS.MOBO.RECONCILIATION)).toBe(true);
    expect(result).toEqual({ success: true, data: FLOW_DTO });
  });

  it("getReconciliation(sessionId) appends ?session_id=<id>", async () => {
    mockFetchOnce(FLOW_DTO);
    await getReconciliation("abc-123");
    expect(calledUrl().endsWith(`${ENDPOINTS.MOBO.RECONCILIATION}?session_id=abc-123`)).toBe(true);
  });

  it("URI-encodes a session id containing reserved characters", async () => {
    mockFetchOnce(FLOW_DTO);
    await getReconciliation("sess/with spaces");
    expect(calledUrl().endsWith(`?session_id=${encodeURIComponent("sess/with spaces")}`)).toBe(true);
  });

  it("surfaces a 404 (unknown session) as a failed APIResult with an HTTP_404 code", async () => {
    mockFetchOnce({ detail: "no such session" }, 404);
    const result = await getReconciliation("missing");
    expect(result.success).toBe(false);
    if (!result.success) expect(result.code).toBe("HTTP_404");
  });
});
