// Generated by test-gen (standard) from docs/implementations/015-eod-exception-report-fe.md §FE-1.
// Regenerate: /test-gen standard.
import { afterEach, describe, expect, it, vi } from "vitest";

// server/api-client.ts imports "server-only" + "next/headers" (cookies()).
// Neither resolves under Vitest/jsdom — stub both so the real apiClient runs
// unmodified against a mocked global fetch (FE-1.server-mobo.test.ts precedent).
vi.mock("server-only", () => ({}));
vi.mock("next/headers", () => ({
  cookies: () => Promise.resolve({ get: () => ({ value: "test-token" }) }),
}));

import { getEod, signOffEod, downloadEod } from "@/server/mobo";
import { ENDPOINTS } from "@/server/endpoints";
import type { EodReportViewDTO } from "@/lib/mobo/eod-types";

const EOD_DTO: EodReportViewDTO = {
  settleDay: "Tue 03 Jun 2026",
  tradeDate: "2026-06-03",
  orders: [], allocs: [], ports: [],
  algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
  counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
  status: "OPEN",
  signedOffBy: null, signedOffAt: null, generated: "10:02am",
  orderCount: 0, executionCount: 0, notionalTraded: "$2.25M", breakTotal: 0,
  outcome: "CLEAR", canSignOff: true, exportReady: false,
};

function mockFetchOnce(body: unknown, status = 200, headers: Record<string, string> = {}) {
  global.fetch = vi.fn().mockResolvedValue({
    ok: status < 300,
    status,
    headers: { get: (k: string) => headers[k] ?? null },
    json: async () => body,
    text: async () => JSON.stringify(body),
    arrayBuffer: async () => new TextEncoder().encode(JSON.stringify(body)).buffer,
  }) as unknown as typeof fetch;
}

function calledUrl(): string {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][0] as string;
}
function calledInit(): RequestInit | undefined {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][1] as RequestInit | undefined;
}

describe("FE-1 getEod/signOffEod", () => {
  afterEach(() => vi.restoreAllMocks());

  it("getEod() with no date hits the bare EOD path", async () => {
    mockFetchOnce(EOD_DTO);
    const result = await getEod();
    expect(calledUrl().endsWith(ENDPOINTS.MOBO.EOD)).toBe(true);
    expect(calledInit()?.method).toBeUndefined(); // GET default
    expect(result).toEqual({ success: true, data: EOD_DTO });
  });

  it("getEod(tradeDate) appends a URI-encoded ?trade_date=", async () => {
    mockFetchOnce(EOD_DTO);
    await getEod("2026-06-03");
    expect(calledUrl().endsWith(`${ENDPOINTS.MOBO.EOD}?trade_date=2026-06-03`)).toBe(true);
  });

  it("signOffEod(tradeDate) POSTs a JSON body {tradeDate}", async () => {
    mockFetchOnce({ ...EOD_DTO, status: "SIGNED", exportReady: true });
    const result = await signOffEod("2026-06-03");
    expect(calledUrl().endsWith(ENDPOINTS.MOBO.EOD_SIGNOFF)).toBe(true);
    expect(calledInit()?.method).toBe("POST");
    expect(JSON.parse(calledInit()?.body as string)).toEqual({ tradeDate: "2026-06-03" });
    expect(result).toEqual({ success: true, data: { ...EOD_DTO, status: "SIGNED", exportReady: true } });
  });

  it("surfaces a 409 sign-off conflict (already SIGNED / canSignOff false) as a failed APIResult with HTTP_409", async () => {
    mockFetchOnce({ detail: "already signed" }, 409);
    const result = await signOffEod("2026-06-03");
    expect(result.success).toBe(false);
    if (!result.success) expect(result.code).toBe("HTTP_409");
  });

  it("surfaces a 401 as UNAUTHORIZED", async () => {
    mockFetchOnce({}, 401);
    const result = await getEod();
    expect(result).toEqual({ success: false, error: "Unauthorized", code: "UNAUTHORIZED" });
  });
});

describe("FE-1 downloadEod", () => {
  afterEach(() => vi.restoreAllMocks());

  it("streams the PDF and base64-encodes it with the filename parsed from Content-Disposition", async () => {
    mockFetchOnce("%PDF-1.4", 200, {
      "Content-Disposition": 'attachment; filename="EoD-2026-06-03.pdf"',
      "Content-Type": "application/pdf",
    });
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      status: 200,
      headers: {
        get: (k: string) =>
          k === "Content-Disposition" ? 'attachment; filename="EoD-2026-06-03.pdf"' :
          k === "Content-Type" ? "application/pdf" : null,
      },
      arrayBuffer: async () => new TextEncoder().encode("%PDF-1.4").buffer,
    }) as unknown as typeof fetch;

    const result = await downloadEod("2026-06-03");
    expect(calledUrl()).toContain(`${ENDPOINTS.MOBO.EOD_EXPORT}?trade_date=2026-06-03`);
    expect(result).toEqual({
      success: true,
      data: { filename: "EoD-2026-06-03.pdf", contentType: "application/pdf", base64: expect.any(String) },
    });
  });

  it("falls back to a default filename when Content-Disposition is absent", async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      status: 200,
      headers: { get: () => null },
      arrayBuffer: async () => new TextEncoder().encode("%PDF-1.4").buffer,
    }) as unknown as typeof fetch;
    const result = await downloadEod();
    expect(result.success).toBe(true);
    if (result.success) expect(result.data.filename).toBe("EoD-report.pdf");
  });

  it("surfaces a 409 (day not yet SIGNED, no file) as a failed APIResult", async () => {
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 409,
      headers: { get: () => null },
      arrayBuffer: async () => new ArrayBuffer(0),
    }) as unknown as typeof fetch;
    const result = await downloadEod("2026-06-03");
    expect(result).toEqual({ success: false, error: "HTTP 409", code: "HTTP_409" });
  });

  it("surfaces a network error (thrown fetch) as a failed APIResult with NETWORK_ERROR", async () => {
    global.fetch = vi.fn().mockRejectedValue(new Error("boom")) as unknown as typeof fetch;
    const result = await downloadEod("2026-06-03");
    expect(result).toEqual({ success: false, error: "boom", code: "NETWORK_ERROR" });
  });
});
