// Generated by test-gen (standard) from docs/implementations/015-eod-exception-report-fe.md §FE-2.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/mobo", () => ({
  getEod: vi.fn(),
  signOffEod: vi.fn(),
  downloadEod: vi.fn(),
}));

import * as serverMobo from "@/server/mobo";
import { getEodReport, signOff, downloadEodPdf } from "@/app/(roles)/mobo/daily-exception-report/actions";

describe("FE-2 getEodReport/signOff/downloadEodPdf server-action wrappers", () => {
  beforeEach(() => vi.clearAllMocks());

  it("getEodReport(tradeDate) calls getEod(tradeDate) and returns its result verbatim", async () => {
    const dto = { success: true, data: { tradeDate: "2026-06-03" } };
    vi.mocked(serverMobo.getEod).mockResolvedValue(dto as never);
    const result = await getEodReport("2026-06-03");
    expect(serverMobo.getEod).toHaveBeenCalledWith("2026-06-03");
    expect(result).toBe(dto);
  });

  it("getEodReport() with no date passes undefined straight through (no default substitution)", async () => {
    vi.mocked(serverMobo.getEod).mockResolvedValue({ success: true, data: {} } as never);
    await getEodReport();
    expect(serverMobo.getEod).toHaveBeenCalledWith(undefined);
  });

  it("a thrown error from getEod is caught and converted to an ACTION_ERROR result, not re-thrown", async () => {
    vi.mocked(serverMobo.getEod).mockRejectedValue(new Error("network down"));
    const result = await getEodReport("2026-06-03");
    expect(result).toEqual({ success: false, error: "network down", code: "ACTION_ERROR" });
  });

  it("signOff(tradeDate) calls signOffEod(tradeDate) and returns its result verbatim", async () => {
    const dto = { success: true, data: { tradeDate: "2026-06-03", status: "SIGNED" } };
    vi.mocked(serverMobo.signOffEod).mockResolvedValue(dto as never);
    const result = await signOff("2026-06-03");
    expect(serverMobo.signOffEod).toHaveBeenCalledWith("2026-06-03");
    expect(result).toBe(dto);
  });

  it("a failed (non-throwing) signOffEod APIResult passes through unchanged", async () => {
    const err = { success: false, error: "already signed", code: "HTTP_409" };
    vi.mocked(serverMobo.signOffEod).mockResolvedValue(err as never);
    const result = await signOff("2026-06-03");
    expect(result).toBe(err);
  });

  it("a thrown error from signOffEod is caught and converted to ACTION_ERROR", async () => {
    vi.mocked(serverMobo.signOffEod).mockRejectedValue(new Error("boom"));
    const result = await signOff("2026-06-03");
    expect(result).toEqual({ success: false, error: "boom", code: "ACTION_ERROR" });
  });

  it("downloadEodPdf(tradeDate) calls downloadEod(tradeDate) and returns its result verbatim", async () => {
    const dto = { success: true, data: { filename: "EoD-2026-06-03.pdf", contentType: "application/pdf", base64: "AA==" } };
    vi.mocked(serverMobo.downloadEod).mockResolvedValue(dto as never);
    const result = await downloadEodPdf("2026-06-03");
    expect(serverMobo.downloadEod).toHaveBeenCalledWith("2026-06-03");
    expect(result).toBe(dto);
  });

  it("a thrown error from downloadEod is caught and converted to ACTION_ERROR, not re-thrown", async () => {
    vi.mocked(serverMobo.downloadEod).mockRejectedValue(new Error("stream failed"));
    const result = await downloadEodPdf("2026-06-03");
    expect(result).toEqual({ success: false, error: "stream failed", code: "ACTION_ERROR" });
  });
});
