// Generated by test-gen (standard) from docs/implementations/015-eod-exception-report-fe.md §FE-5.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

vi.mock("@/hooks/api/useEodReport", () => ({ useEodReport: vi.fn() }));
vi.mock("@/app/(roles)/mobo/daily-exception-report/actions", () => ({ downloadEodPdf: vi.fn() }));

import { useEodReport } from "@/hooks/api/useEodReport";
import { downloadEodPdf } from "@/app/(roles)/mobo/daily-exception-report/actions";
import DailyExceptionReportPage from "@/app/(roles)/mobo/daily-exception-report/page";

const ORDER = {
  id: "o1", m: "mA" as const, inst: "AAPL US", cat: "Equity", side: "Buy",
  qty: "12,000", px: "$187.40", not: "$2.25M", notVal: 2_250_000, multiplier: 1,
  ref: "TRD-88142", ib: "IB-40118", st: "ok" as const,
  execs: [{ id: "x1", qty: "12,000", px: "$187.40", t: "09:31:02", st: "ok" as const }],
};

const BASE_DATA = {
  settleDay: "Tue 03 Jun 2026", tradeDate: "2026-06-03",
  orders: [ORDER], allocs: [], ports: [],
  algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
  counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
  status: "OPEN" as const, signedOffBy: null, signedOffAt: null, generated: "10:02am",
  orderCount: 1, executionCount: 1, notionalTraded: "$2.25M", breakTotal: 0,
  outcome: "CLEAR" as const, canSignOff: true, exportReady: false,
};

function mockHook(overrides: Partial<ReturnType<typeof useEodReport>> = {}) {
  vi.mocked(useEodReport).mockReturnValue({
    data: BASE_DATA, loading: false, error: null, refetch: vi.fn(),
    signOff: vi.fn().mockResolvedValue(true), signingOff: false,
    ...overrides,
  } as ReturnType<typeof useEodReport>);
}

describe("FE-5 DailyExceptionReportPage", () => {
  beforeEach(() => vi.clearAllMocks());

  it("renders the AllClear verdict when outcome is CLEAR", () => {
    mockHook();
    render(<DailyExceptionReportPage />);
    expect(screen.getByText(/all clear/i)).toBeInTheDocument();
  });

  it("renders the leg tables (not AllClear) when outcome is EXCEPTIONS, even with breakTotal 0", () => {
    mockHook({ data: { ...BASE_DATA, outcome: "EXCEPTIONS", breakTotal: 0 } });
    render(<DailyExceptionReportPage />);
    expect(screen.queryByText(/all clear/i)).not.toBeInTheDocument();
  });

  it("Sign off button is enabled whenever status is OPEN and canSignOff is true, regardless of breakTotal", () => {
    mockHook({ data: { ...BASE_DATA, canSignOff: true, breakTotal: 3, outcome: "EXCEPTIONS" } });
    render(<DailyExceptionReportPage />);
    expect(screen.getByRole("button", { name: /sign off/i })).not.toBeDisabled();
  });

  it("Sign off button is disabled when canSignOff is false, even with zero open breaks", () => {
    mockHook({ data: { ...BASE_DATA, canSignOff: false, breakTotal: 0 } });
    render(<DailyExceptionReportPage />);
    expect(screen.getByRole("button", { name: /sign off/i })).toBeDisabled();
  });

  it("Export button is disabled when exportReady is false", () => {
    mockHook({ data: { ...BASE_DATA, exportReady: false } });
    render(<DailyExceptionReportPage />);
    expect(screen.getByRole("button", { name: /export/i })).toBeDisabled();
  });

  it("Export button is enabled when exportReady is true", () => {
    mockHook({ data: { ...BASE_DATA, exportReady: true } });
    render(<DailyExceptionReportPage />);
    expect(screen.getByRole("button", { name: /export/i })).not.toBeDisabled();
  });

  it("clicking Sign off calls the hook's signOff", () => {
    const signOff = vi.fn().mockResolvedValue(true);
    mockHook({ signOff });
    render(<DailyExceptionReportPage />);
    fireEvent.click(screen.getByRole("button", { name: /sign off/i }));
    expect(signOff).toHaveBeenCalled();
  });

  it("clicking Export calls downloadEodPdf with the loaded tradeDate", async () => {
    vi.mocked(downloadEodPdf).mockResolvedValue({
      success: true,
      data: { filename: "EoD-2026-06-03.pdf", contentType: "application/pdf", base64: "AA==" },
    });
    mockHook({ data: { ...BASE_DATA, exportReady: true } });
    render(<DailyExceptionReportPage />);
    fireEvent.click(screen.getByRole("button", { name: /export/i }));
    await waitFor(() => expect(downloadEodPdf).toHaveBeenCalledWith("2026-06-03"));
  });

  it("renders a loading state without throwing on undefined array access, when data is null and loading is true", () => {
    mockHook({ data: null, loading: true });
    expect(() => render(<DailyExceptionReportPage />)).not.toThrow();
  });

  it("renders an error branch (not a crash) when the hook reports an error", () => {
    mockHook({ data: null, loading: false, error: "network down" });
    render(<DailyExceptionReportPage />);
    expect(screen.getByRole("alert")).toBeInTheDocument();
  });

  it("clicking Retry in the error branch calls the hook's refetch", () => {
    const refetch = vi.fn();
    mockHook({ data: null, loading: false, error: "network down", refetch });
    render(<DailyExceptionReportPage />);
    fireEvent.click(screen.getByRole("button", { name: /retry/i }));
    expect(refetch).toHaveBeenCalled();
  });
});
