"""Shared fixtures/doubles for tests/cli (BE-20/BE-21).

Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-20/BE-21.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Layer isolation: only imports app/ + stdlib + pytest. No sibling-layer (DB/FE) imports.

Pre-implementation note: app.cli.bootstrap_admin does not exist on this branch yet (BE-20/BE-21
are unimplemented) -- collection of test_be21_bootstrap_seed.py is expected to fail with
ModuleNotFoundError until BE-21 lands. BE-21 also depends on BE-15's app.libs.staff
(StaffRepository), which does not exist yet either -- same expected failure mode. This
conftest itself imports only app.core.database/app.models.users (both already present), so it
collects cleanly on its own.
"""

from __future__ import annotations

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base
from app.models import users as _users_models  # noqa: F401  # registers tables on Base.metadata
from tests.conftest import FakeIdentityService  # noqa: F401 -- re-exported, BE-2 shared double


@pytest.fixture
def engine():
    """In-memory SQLite, shared across connections via StaticPool so that
    bootstrap_admin.run()'s own open/close-per-call SessionLocal() pattern
    (a fresh session per invocation) still sees data written by a prior call --
    a plain sqlite:///:memory: engine would hand each new connection a blank DB."""
    eng = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(eng)
    return eng


@pytest.fixture
def TestSessionLocal(engine):
    return sessionmaker(bind=engine, autocommit=False, autoflush=False, expire_on_commit=False)


@pytest.fixture
def session(TestSessionLocal):
    db = TestSessionLocal()
    try:
        yield db
    finally:
        db.close()


# FakeIdentityService moved to tests/conftest.py (BE-2) -- imported above.
