"""Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-21.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Pre-implementation note: app/cli/bootstrap_admin.py does not exist yet on this branch --
ModuleNotFoundError on collection is EXPECTED until BE-20/BE-21 land. BE-21 also depends on
BE-15's `app.libs.staff` (StaffRepository), which doesn't exist yet either -- StaffRepository is
NOT faked here (only identity is, per the impl doc's seam-mock column); once BE-15 lands this
file exercises the real repository against an in-memory SQLite session.
Run: .venv/Scripts/python.exe -m pytest -q tests/cli/test_be21_bootstrap_seed.py
"""

from __future__ import annotations

from unittest.mock import patch

import pytest

from app.cli import bootstrap_admin
from app.core.config import Settings
from app.libs.staff import StaffRepository
from app.models.users import AccountStatus, AdminRole, User
from tests.cli.conftest import FakeIdentityService


def _settings(**overrides) -> Settings:
    defaults = dict(
        firebase_auth_disabled=False,
        bootstrap_admin_email="root@example.com",
        bootstrap_admin_name="Bootstrap Admin",
    )
    defaults.update(overrides)
    return Settings(**defaults)


def _run(session, TestSessionLocal, settings, fake_identity):
    with patch("app.cli.bootstrap_admin.SessionLocal", TestSessionLocal), patch(
        "app.cli.bootstrap_admin.get_settings", return_value=settings
    ), patch("app.cli.bootstrap_admin.FirebaseIdentityService", return_value=fake_identity):
        bootstrap_admin.run()


# --- Positive --------------------------------------------------------------------


def test_empty_db_seeds_exactly_one_admin(session, TestSessionLocal, capsys):
    fake_identity = FakeIdentityService()
    settings = _settings()

    _run(session, TestSessionLocal, settings, fake_identity)

    repo = StaffRepository(session)
    assert repo.count_active_admins() == 1

    row = session.query(User).filter_by(email="root@example.com").one()
    assert row.status == AccountStatus.ACTIVE
    assert row.admin_profile.role == AdminRole.ADMIN
    assert row.authorized_by is None
    assert fake_identity.ensure_identity_calls == ["root@example.com"]
    assert fake_identity.generate_set_password_link_calls == ["root@example.com"]

    out = capsys.readouterr().out
    assert "seeded first ADMIN" in out
    assert "https://fake.invalid/invite" in out


def test_dev_bypass_seeds_dev_user_uid(session, TestSessionLocal, capsys):
    fake_identity = FakeIdentityService()
    settings = _settings(firebase_auth_disabled=True)

    _run(session, TestSessionLocal, settings, fake_identity)

    row = session.query(User).filter_by(firebase_uid="dev-user").one()
    assert row.status == AccountStatus.ACTIVE
    assert row.admin_profile.role == AdminRole.ADMIN
    # Contract hardcodes uid = "dev-user" for the dev branch -- ensure_identity must
    # never be called on this path.
    assert fake_identity.ensure_identity_calls == []


# --- Negative ----------------------------------------------------------------------


def test_rerun_is_noop_no_duplicate_admin_or_identity_call(session, TestSessionLocal, capsys):
    fake_identity = FakeIdentityService()
    settings = _settings()

    _run(session, TestSessionLocal, settings, fake_identity)
    assert fake_identity.ensure_identity_calls == ["root@example.com"]

    capsys.readouterr()  # drain first run's output
    _run(session, TestSessionLocal, settings, fake_identity)

    repo = StaffRepository(session)
    assert repo.count_active_admins() == 1
    # No second identity/DB interaction on the no-op branch.
    assert fake_identity.ensure_identity_calls == ["root@example.com"]

    out = capsys.readouterr().out
    assert "no-op" in out


def test_production_settings_without_bootstrap_email_raises_system_exit(session, TestSessionLocal):
    fake_identity = FakeIdentityService()
    settings = _settings(bootstrap_admin_email=None)

    with pytest.raises(SystemExit):
        _run(session, TestSessionLocal, settings, fake_identity)

    repo = StaffRepository(session)
    assert repo.count_active_admins() == 0
    assert fake_identity.ensure_identity_calls == []


# --- Invariants ----------------------------------------------------------------------


@pytest.mark.parametrize("n", [1, 2, 3, 5])
def test_running_seed_n_times_never_exceeds_one_admin(session, TestSessionLocal, capsys, n):
    fake_identity = FakeIdentityService()
    settings = _settings()

    for _ in range(n):
        _run(session, TestSessionLocal, settings, fake_identity)
        capsys.readouterr()

    repo = StaffRepository(session)
    assert repo.count_active_admins() == 1


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
