# Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-11..BE-14.
# Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md
#
# Shared fixtures/doubles for tests/libs/clients/test_be11_*.py .. test_be14_*.py.
#
# Layer isolation: imports only app/ + stdlib + pytest. `app.libs.identity` does not exist
# yet on this branch (BE-1..BE-4 unimplemented), so this file does NOT import it --
# instead it re-exports the shared FakeIdentityService test double (tests/conftest.py,
# BE-2) matching the public surface described in the impl doc §5.1/BE-1/BE-2
# (`ensure_identity(email) -> tuple[str, bool]`, `delete_user(uid) -> None`,
# `generate_set_password_link(email) -> str`).
#
# Pre-implementation note: `app.libs.clients.repository.ClientRepository.create_with_profile`/
# `.assign_rm` and `app.libs.clients.service.ClientService.assert_is_rm`/`.onboard` do not
# exist on this branch yet (BE-11/BE-12 unimplemented) -- this conftest itself only imports
# the EXISTING ClientRepository/ClientService classes (which already exist, per the read-only
# RM listing module), so it collects cleanly on its own. Calling the not-yet-implemented
# methods from the test files is what raises AttributeError, not collecting this conftest.

from __future__ import annotations

import uuid

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base
from app.models.users import AccountStatus, AdminProfile, AdminRole, ClientProfile, Portal, User
from tests.conftest import FakeIdentityService  # noqa: F401 -- re-exported, BE-2 shared double

# FakeIdentityService moved to tests/conftest.py (BE-2) -- imported above.


@pytest.fixture
def session():
    """In-memory SQLite session -- same engine/Base.metadata.create_all/sessionmaker
    pattern used by tests/models/conftest.py."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    with engine.connect() as conn:
        conn.exec_driver_sql("PRAGMA foreign_keys=ON")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False)
    db = Session()
    try:
        yield db
    finally:
        db.close()


@pytest.fixture
def rm_admin(session):
    """A Portal.ADMIN user carrying AdminProfile(role=AdminRole.RM) -- a valid
    `assigned_rm_uid` target for BE-12's `assert_is_rm`."""
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"rm-uid-{uuid.uuid4()}",
        email="rm@example.com",
        portal=Portal.ADMIN,
        status=AccountStatus.ACTIVE,
    )
    session.add(user)
    session.flush()
    session.add(AdminProfile(user_id=user.id, role=AdminRole.RM, name="RM One"))
    session.commit()
    return user


@pytest.fixture
def non_rm_admin(session):
    """A Portal.ADMIN user carrying AdminProfile(role=AdminRole.PM) -- must be
    REJECTED by `assert_is_rm` (RM-literal check, Q-E)."""
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"pm-uid-{uuid.uuid4()}",
        email="pm@example.com",
        portal=Portal.ADMIN,
        status=AccountStatus.ACTIVE,
    )
    session.add(user)
    session.flush()
    session.add(AdminProfile(user_id=user.id, role=AdminRole.PM, name="PM One"))
    session.commit()
    return user


@pytest.fixture
def client_target(session, rm_admin):
    """A plain, already-onboarded client user + client_profiles row -- used as the
    reassignment target for BE-14's `assign_rm`."""
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"client-uid-{uuid.uuid4()}",
        email="client@example.com",
        portal=Portal.CLIENT,
        status=AccountStatus.DISABLED,
    )
    session.add(user)
    session.flush()
    session.add(
        ClientProfile(user_id=user.id, name="Client One", assigned_rm_uid=rm_admin.firebase_uid)
    )
    session.commit()
    return user
