// Generated by test-gen (standard) from docs/implementations/011-2026-07-13-post-trade-allocation-fe.md §FE-2.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/mobo", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/server/mobo")>()),
  getPostTradeAllocation: vi.fn(),
  getPostTradeAllocationRuns: vi.fn(),
  runPostTradeAllocation: vi.fn(),
}));

import * as serverMobo from "@/server/mobo";
import { getRuns, getView, runSync } from "@/app/(roles)/mobo/post-trade-allocation/actions";

describe("FE-2 server-action wrappers", () => {
  beforeEach(() => vi.clearAllMocks());

  it("getView(date) calls getPostTradeAllocation(date) and returns its result verbatim", async () => {
    const dto = { success: true, data: { tradeDate: "2026-06-03" } };
    vi.mocked(serverMobo.getPostTradeAllocation).mockResolvedValue(dto as never);
    const result = await getView("2026-06-03");
    expect(serverMobo.getPostTradeAllocation).toHaveBeenCalledWith("2026-06-03");
    expect(result).toBe(dto);
  });

  it("getView() with no date passes undefined straight through (no default substitution)", async () => {
    vi.mocked(serverMobo.getPostTradeAllocation).mockResolvedValue({ success: true, data: {} } as never);
    await getView();
    expect(serverMobo.getPostTradeAllocation).toHaveBeenCalledWith(undefined);
  });

  it("getRuns() calls getPostTradeAllocationRuns() and returns its result verbatim", async () => {
    const dto = { success: true, data: { runs: [] } };
    vi.mocked(serverMobo.getPostTradeAllocationRuns).mockResolvedValue(dto as never);
    const result = await getRuns();
    expect(serverMobo.getPostTradeAllocationRuns).toHaveBeenCalled();
    expect(result).toBe(dto);
  });

  it("runSync() calls runPostTradeAllocation() and passes a failure result through untouched", async () => {
    const err = { success: false, error: "boom", code: "NETWORK_ERROR" };
    vi.mocked(serverMobo.runPostTradeAllocation).mockResolvedValue(err as never);
    const result = await runSync();
    expect(serverMobo.runPostTradeAllocation).toHaveBeenCalled();
    expect(result).toBe(err);
  });
});
