// Generated by test-gen (standard) from docs/implementations/011-2026-07-13-post-trade-allocation-fe.md §FE-6.
// Regenerate: /test-gen standard.
import { readFileSync } from "node:fs";
import path from "node:path";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

vi.mock("sonner", () => ({ toast: Object.assign(vi.fn(), { error: vi.fn() }) }));

vi.mock("@/hooks/api/usePostTradeAllocation", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/hooks/api/usePostTradeAllocation")>()),
  usePostTradeAllocation: vi.fn(),
  usePostTradeAllocationRuns: vi.fn(),
}));

import { toast } from "sonner";
import { usePostTradeAllocation, usePostTradeAllocationRuns } from "@/hooks/api/usePostTradeAllocation";
import PostTradeAllocationPage from "@/app/(roles)/mobo/post-trade-allocation/page";

const MODELS = [
  {
    id: "9f2c",
    name: "Zero",
    acct: "U-1234567",
    traded: 6_800_000,
    unitsTotal: 25,
    clientShares: [{ clientId: "3a11", name: "Strathmore Fund", units: 5, allocated: 1_360_000, pct: 20 }],
  },
];
const RUNS = [{ date: "2026-06-03", label: "Tue 03 Jun 2026", grandTotal: 6_800_000 }];

function mockHooks(overrides: { loading?: boolean; sync?: () => Promise<unknown> } = {}) {
  vi.mocked(usePostTradeAllocation).mockReturnValue({
    data: { settleDay: "Tue 03 Jun 2026", models: MODELS, grandTotal: 6_800_000 },
    loading: overrides.loading ?? false,
    error: null,
    refetch: vi.fn(),
    sync: overrides.sync ?? vi.fn().mockResolvedValue({ empty: false }),
  } as unknown as ReturnType<typeof usePostTradeAllocation>);
  vi.mocked(usePostTradeAllocationRuns).mockReturnValue({ runs: RUNS, loading: false });
}

describe("FE-6 PostTradeAllocationPage", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockHooks();
  });

  it("renders grandTotal/settleDay sourced from usePostTradeAllocation's data", () => {
    render(<PostTradeAllocationPage />);
    // ptaMoney's M-branch uses toFixed(3) (FE-4 ptaMoney verdict A, lib/mobo/allocation.ts).
    expect(screen.getByText(/\$6\.800M/)).toBeInTheDocument();
    expect(screen.getByText(/Tue 03 Jun 2026/)).toBeInTheDocument();
  });

  it("clicking Sync while not loading calls sync() and shows no toast on a real-run result", async () => {
    const sync = vi.fn().mockResolvedValue({ empty: false, checkedAt: "14:32" });
    mockHooks({ sync });
    render(<PostTradeAllocationPage />);
    fireEvent.click(screen.getByRole("button", { name: /sync/i }));
    await waitFor(() => expect(sync).toHaveBeenCalled());
    expect(toast).not.toHaveBeenCalled();
  });

  it("clicking Sync on an empty-run result shows exactly one toast naming the checked-at time", async () => {
    const sync = vi.fn().mockResolvedValue({ empty: true, checkedAt: "14:32" });
    mockHooks({ sync });
    render(<PostTradeAllocationPage />);
    fireEvent.click(screen.getByRole("button", { name: /sync/i }));
    await waitFor(() => expect(toast).toHaveBeenCalledTimes(1));
    expect(toast).toHaveBeenCalledWith(expect.stringContaining("14:32"));
  });

  it("a sync() error surfaces as an error toast, not a thrown exception", async () => {
    const sync = vi.fn().mockResolvedValue({ empty: false, error: "network down" });
    mockHooks({ sync });
    render(<PostTradeAllocationPage />);
    fireEvent.click(screen.getByRole("button", { name: /sync/i }));
    await waitFor(() => expect(vi.mocked(toast).error).toHaveBeenCalledWith("network down"));
  });

  it("the Sync button is disabled while loading, and a click is a no-op", () => {
    const sync = vi.fn();
    mockHooks({ loading: true, sync });
    render(<PostTradeAllocationPage />);
    const button = screen.getByRole("button", { name: /sync/i });
    expect(button).toBeDisabled();
    fireEvent.click(button);
    expect(sync).not.toHaveBeenCalled();
  });

  it("DateControl's dropdown options come from usePostTradeAllocationRuns's runs, not a hardcoded const", () => {
    // DateControl (components/mobo/allocation/Panels.tsx:389-588) is now a calendar-
    // grid picker, not a dropdown list of run labels — a day cell gets a "has data" dot
    // when its ISO date is in `dataSet = new Set(runs.map(r => r.date))` (:519, :541-546).
    // Fix the clock inside RUNS[0].date's month so June 2026 is the default calendar view
    // and the 3rd isn't treated as a future date (:402-404, :517).
    vi.useFakeTimers();
    vi.setSystemTime(new Date(2026, 5, 15));
    try {
      render(<PostTradeAllocationPage />);
      fireEvent.click(screen.getByRole("button", { name: "Latest" }));
      const runDay = screen.getByRole("button", { name: "3" }); // RUNS[0].date === "2026-06-03"
      expect(runDay.querySelector(".bg-primary-container")).toBeInTheDocument();
    } finally {
      vi.useRealTimers();
    }
  });

  it("has no import resolving to lib/mock/mobo-data's PTA_MODELS/PTA_CLIENTS/PTA_UNITS", () => {
    const src = readFileSync(
      path.resolve(process.cwd(), "app/(roles)/mobo/post-trade-allocation/page.tsx"),
      "utf-8",
    );
    expect(src).not.toMatch(/PTA_MODELS|PTA_CLIENTS|PTA_UNITS/);
  });
});
