// Generated by test-gen (standard) from docs/implementations/016-allotment-redemption-integration-fe.md §FE-2. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-2 adds submitAllotment/submitRedemption
// to server/rm/index.ts and 2 new ENDPOINTS.RM entries — neither exists yet,
// so this file's imports fail to resolve until the feature agent lands them.
// That module-resolution failure is the correct/expected pre-implementation
// signal for this unit.
import { afterEach, describe, expect, it, vi } from "vitest";

// server/api-client.ts imports "server-only" + "next/headers" (cookies()).
// Neither resolves under Vitest/jsdom — stub both so the real apiClient
// runs unmodified against a mocked global fetch (see
// tests/server/onboarding/FE-1.server-onboarding.test.ts precedent).
vi.mock("server-only", () => ({}));
vi.mock("next/headers", () => ({
  cookies: () => Promise.resolve({ get: () => ({ value: "test-token" }) }),
}));

import { submitAllotment, submitRedemption } from "@/server/rm";
import { ENDPOINTS } from "@/server/endpoints";
import type { AllotRdmptDTO } from "@/lib/onboarding/types";

const ALLOTMENT: AllotRdmptDTO = {
  id: "a1", reference: "REF-1", model_id: "m1", model_name: "Model A", units: 2, amount: 200_000,
  kind: "allotment", status: "pending", note: null, agg_before: 0, agg_after: 2,
  expected_cash_in: "2026-08-01", rm: "Jane", created_at: "2026-07-22T00:00:00Z", acknowledged_at: null,
};

function mockFetchOnce(body: unknown, status = 201) {
  global.fetch = vi.fn().mockResolvedValue({
    ok: status < 300,
    status,
    headers: { get: () => null },
    json: async () => body,
    text: async () => JSON.stringify(body),
  }) as unknown as typeof fetch;
}

function calledUrl(): string {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][0] as string;
}
function calledInit(): RequestInit | undefined {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][1] as RequestInit | undefined;
}

afterEach(() => vi.restoreAllMocks());

describe("FE-2 server/rm.submitAllotment", () => {
  it("POSTs to ENDPOINTS.RM.SUBMIT_ALLOTMENT with the exact request body", async () => {
    mockFetchOnce(ALLOTMENT);
    const req = { client_id: "c-1", model_id: "m-1", multiplier: 2, expected_cash_in: "2026-08-01", mgmt_fee: 0.015, incentive_fee: 0.2 };
    const result = await submitAllotment(req);
    expect(calledUrl().endsWith(ENDPOINTS.RM.SUBMIT_ALLOTMENT)).toBe(true);
    expect(calledInit()?.method).toBe("POST");
    expect(JSON.parse(calledInit()?.body as string)).toEqual(req);
    expect(result).toEqual({ success: true, data: ALLOTMENT });
  });

  it("resolves ENDPOINTS.RM.SUBMIT_ALLOTMENT to /api/rm/allotment", () => {
    expect(ENDPOINTS.RM.SUBMIT_ALLOTMENT).toBe("/api/rm/allotment");
  });
});

describe("FE-2 server/rm.submitRedemption", () => {
  it("POSTs to ENDPOINTS.RM.SUBMIT_REDEMPTION with the exact request body", async () => {
    const dto = { ...ALLOTMENT, kind: "redemption" as const, status: "awaiting_pc" as const };
    mockFetchOnce(dto);
    const req = { client_id: "c-1", model_id: "m-1", multiplier: 1, expected_cash_out: "2026-08-15", emergent: false };
    const result = await submitRedemption(req);
    expect(calledUrl().endsWith(ENDPOINTS.RM.SUBMIT_REDEMPTION)).toBe(true);
    expect(calledInit()?.method).toBe("POST");
    expect(JSON.parse(calledInit()?.body as string)).toEqual(req);
    expect(result).toEqual({ success: true, data: dto });
  });

  it("resolves ENDPOINTS.RM.SUBMIT_REDEMPTION to /api/rm/redemption", () => {
    expect(ENDPOINTS.RM.SUBMIT_REDEMPTION).toBe("/api/rm/redemption");
  });

  it("a non-2xx response surfaces as an APIResult failure, not a throw", async () => {
    mockFetchOnce({ detail: "wrong status" }, 409);
    const result = await submitRedemption({ client_id: "c-1", model_id: "m-1", multiplier: 1, expected_cash_out: null });
    expect(result.success).toBe(false);
    if (!result.success) expect(result.code).toBe("HTTP_409");
  });
});
