// Generated by test-gen (standard) from docs/implementations/017-transaction-details-wiring-fe.md §FE-2. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-2 adds fileTransactionDetail/
// getTransactionDetail to server/rm/index.ts and ENDPOINTS.RM.TRANSACTION_DETAIL
// to server/endpoints.ts — neither exists yet, so this file's imports fail to
// resolve until the feature agent lands them. That module-resolution failure
// is the correct/expected pre-implementation signal for this unit.
import { afterEach, describe, expect, it, vi } from "vitest";

// server/api-client.ts imports "server-only" + "next/headers" (cookies()).
// Neither resolves under Vitest/jsdom — stub both so the real apiClient runs
// unmodified against a mocked global fetch (see
// tests/server/onboarding/FE-1.server-onboarding.test.ts precedent).
vi.mock("server-only", () => ({}));
vi.mock("next/headers", () => ({
  cookies: () => Promise.resolve({ get: () => ({ value: "test-token" }) }),
}));

import { fileTransactionDetail, getTransactionDetail } from "@/server/rm";
import { ENDPOINTS } from "@/server/endpoints";
import type { TransactionDetailDTO, TransactionDetailRequest } from "@/lib/onboarding/types";

const DETAIL: TransactionDetailDTO = {
  id: "td-1", allotment_id: "a-1", bank_account: "HSBC-4471-001",
  settlement_amount: 180_000, transaction_date: "2026-08-01", transaction_time: "14:30",
  currency: "USD", reference_no: "TXN-1", filed_by: "rm-uid", filed_at: "2026-08-01T14:31:00Z",
};

function mockFetchOnce(body: unknown, status = 201) {
  global.fetch = vi.fn().mockResolvedValue({
    ok: status < 300,
    status,
    headers: { get: () => null },
    json: async () => body,
    text: async () => JSON.stringify(body),
  }) as unknown as typeof fetch;
}

function calledUrl(): string {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][0] as string;
}
function calledInit(): RequestInit | undefined {
  return (fetch as unknown as { mock: { calls: unknown[][] } }).mock.calls[0][1] as RequestInit | undefined;
}

afterEach(() => vi.restoreAllMocks());

describe("FE-2 ENDPOINTS.RM.TRANSACTION_DETAIL", () => {
  it("resolves to /api/rm/allotments/{id}/transaction-detail", () => {
    expect(ENDPOINTS.RM.TRANSACTION_DETAIL("abc")).toBe("/api/rm/allotments/abc/transaction-detail");
  });
});

describe("FE-2 server/rm.fileTransactionDetail", () => {
  it("POSTs to ENDPOINTS.RM.TRANSACTION_DETAIL(id) with the exact request body", async () => {
    mockFetchOnce(DETAIL);
    const req: TransactionDetailRequest = {
      bank_account: "HSBC-4471-001", settlement_amount: 180_000,
      transaction_date: "2026-08-01", transaction_time: "14:30",
      currency: "USD", reference_no: "TXN-1",
    };
    const result = await fileTransactionDetail("abc", req);
    expect(calledUrl().endsWith(ENDPOINTS.RM.TRANSACTION_DETAIL("abc"))).toBe(true);
    expect(calledInit()?.method).toBe("POST");
    expect(JSON.parse(calledInit()?.body as string)).toEqual(req);
    expect(result).toEqual({ success: true, data: DETAIL });
  });

  it("a failed POST (409 — already filed) surfaces as an APIResult failure, not a throw", async () => {
    mockFetchOnce({ detail: "already filed" }, 409);
    const req: TransactionDetailRequest = {
      bank_account: "HSBC-4471-001", settlement_amount: 180_000,
      transaction_date: "2026-08-01", transaction_time: "14:30", currency: "USD",
    };
    const result = await fileTransactionDetail("abc", req);
    expect(result.success).toBe(false);
    if (!result.success) expect(result.code).toBe("HTTP_409");
  });
});

describe("FE-2 server/rm.getTransactionDetail", () => {
  it("GETs ENDPOINTS.RM.TRANSACTION_DETAIL(id) with no body/POST method", async () => {
    mockFetchOnce(DETAIL, 200);
    const result = await getTransactionDetail("abc");
    expect(calledUrl().endsWith(ENDPOINTS.RM.TRANSACTION_DETAIL("abc"))).toBe(true);
    expect(calledInit()?.method).toBeUndefined();
    expect(result).toEqual({ success: true, data: DETAIL });
  });

  it("a 404 (no settlement filed yet) surfaces as an APIResult failure", async () => {
    mockFetchOnce({ detail: "not found" }, 404);
    const result = await getTransactionDetail("abc");
    expect(result.success).toBe(false);
    if (!result.success) expect(result.code).toBe("HTTP_404");
  });
});
