// Generated by test-gen (standard) from docs/implementations/013-client-onboarding-integration-fe.md §FE-2 (PC half).
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/onboarding", () => ({
  fetchAllotments: vi.fn(),
  acknowledgeAllotment: vi.fn(),
}));

import * as serverOnboarding from "@/server/onboarding";
import { fetchAllotments, acknowledgeAllotment } from "@/app/(roles)/pc/allotment-redemption/actions";

describe("FE-2 PC action wrappers", () => {
  beforeEach(() => vi.clearAllMocks());

  it("fetchAllotments() calls the FE-1 function and returns its success result verbatim", async () => {
    const ok = { success: true, data: [] };
    vi.mocked(serverOnboarding.fetchAllotments).mockResolvedValue(ok as never);
    const result = await fetchAllotments();
    expect(serverOnboarding.fetchAllotments).toHaveBeenCalled();
    expect(result).toBe(ok);
  });

  it("acknowledgeAllotment(id) forwards the id unchanged", async () => {
    const ok = { success: true, data: { id: "al-1", status: "acknowledged" } };
    vi.mocked(serverOnboarding.acknowledgeAllotment).mockResolvedValue(ok as never);
    const result = await acknowledgeAllotment("al-1");
    expect(serverOnboarding.acknowledgeAllotment).toHaveBeenCalledWith("al-1");
    expect(result).toBe(ok);
  });

  it("acknowledgeAllotment(id) converts a thrown error into ACTION_ERROR instead of propagating", async () => {
    vi.mocked(serverOnboarding.acknowledgeAllotment).mockRejectedValue(new Error("network down"));
    const result = await acknowledgeAllotment("al-1");
    expect(result).toEqual({ success: false, error: "network down", code: "ACTION_ERROR" });
  });
});
