# Generated by test-gen (thorough) from
# docs/implementations/019-admin-access-control-and-staff-enrollment-be.md §8.
# Regenerate: /test-gen thorough docs/implementations/019-admin-access-control-and-staff-enrollment-be.md
#
# Shared fixtures/doubles for tests/libs/access/test_be2_*.py .. test_be11_*.py.
#
# Pre-implementation note: app.libs.access (pages/repository/resolver/schemas/
# service/router) does not exist on this branch yet -- every test_be*.py file in
# this directory is expected to fail collection with ModuleNotFoundError/ImportError
# until BE-2/BE-3/BE-4/BE-8/BE-9/BE-10/BE-11 land. This conftest itself only imports
# already-committed modules (app.core.database, app.models.access, app.models.users,
# app.models.onboarding, sqlalchemy, stdlib, pytest), so it collects cleanly on its
# own -- same pattern as tests/libs/staff/conftest.py.
#
# Layer isolation: no import of admin-frontend or any sibling-layer file. The 16
# PageId literals and the 55-row page_access seed below are transcribed BY HAND
# from the frozen seam (impl doc §7.1) and from the already-landed DB migration
# (alembic/versions/5cd1cc1948cc_0028_admin_access_control.py, DB-7) -- never
# imported from either, per §8.1's "checked-in literal list" instruction.

from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone
from types import SimpleNamespace
from typing import Iterator

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.database import Base
from app.models.access import (
    AccessLevel,
    AdminAuditEvent,
    OverrideLevel,
    PageAccess,
    PageAccessOverride,
    PageAccessPublication,
)
from app.models.onboarding import ClientTicket, TicketKind, TicketStatus
from app.models.users import AccountStatus, AdminProfile, AdminRole, ClientProfile, Portal, User

# --------------------------------------------------------------------------
# The seam, transcribed by hand (§7.1's PageId union / D-8) -- NOT imported
# from admin-frontend/lib/pages-config.ts (belongs to the Frontend layer's
# tree) and NOT imported from app.libs.access.pages (doesn't exist yet).
# --------------------------------------------------------------------------
PAGE_IDS: frozenset[str] = frozenset(
    {
        "rm.client-info",
        "rm.onboarding-renewal",
        "rm.model-subscription",
        "rm.request-tickets",
        "mobo.recon-overview",
        "mobo.trade-reconciliation",
        "mobo.commission-tracking",
        "mobo.post-trade-allocation",
        "pc.model-management",
        "pc.allocation-matrix",
        "pc.allotment-redemption",
        "compliance.overview",
        "compliance.review",
        "shared.monthly-reports",
        "admin.enroll-user",
        "admin.system-config",
    }
)
assert len(PAGE_IDS) == 16

# The declared PAGE_META insertion order from impl doc §6 BE-2 (lines 312-328)
# -- the wire order of MatrixOut.pages (§7.2). Used by BE-2 and BE-8 tests to
# assert order without importing app.libs.access.pages.PAGE_META.
PAGE_META_ORDER: list[str] = [
    "rm.client-info",
    "rm.onboarding-renewal",
    "rm.model-subscription",
    "rm.request-tickets",
    "compliance.review",
    "pc.allotment-redemption",
    "pc.allocation-matrix",
    "mobo.post-trade-allocation",
    "mobo.trade-reconciliation",
    "mobo.commission-tracking",
    "shared.monthly-reports",
    "pc.model-management",
    "admin.enroll-user",
    "admin.system-config",
    "mobo.recon-overview",
    "compliance.overview",
]
assert set(PAGE_META_ORDER) == PAGE_IDS

# The literal 55-row page_access seed (30 edit + 25 view; RM 7 / MOBO 10 / PM 0 /
# PC 10 / COMPLIANCE 12 / ADMIN 16 -- D-11), transcribed BY HAND from the already
# -committed alembic/versions/5cd1cc1948cc_0028_admin_access_control.py (DB-7)
# INSERT statement. This is the DB layer's contract output, used here as a fixed
# fixture -- never recomputed or "improved", so a drift between this file and the
# live migration is a signal, not something to silently reconcile.
PAGE_ACCESS_SEED: list[tuple[str, str, str]] = [
    ("rm.client-info", "RM", "edit"),
    ("rm.client-info", "COMPLIANCE", "view"),
    ("rm.client-info", "ADMIN", "edit"),
    ("rm.onboarding-renewal", "RM", "edit"),
    ("rm.onboarding-renewal", "MOBO", "view"),
    ("rm.onboarding-renewal", "COMPLIANCE", "view"),
    ("rm.onboarding-renewal", "ADMIN", "edit"),
    ("rm.model-subscription", "RM", "edit"),
    ("rm.model-subscription", "MOBO", "view"),
    ("rm.model-subscription", "PC", "view"),
    ("rm.model-subscription", "COMPLIANCE", "view"),
    ("rm.model-subscription", "ADMIN", "edit"),
    ("rm.request-tickets", "RM", "edit"),
    ("rm.request-tickets", "ADMIN", "edit"),
    ("shared.monthly-reports", "RM", "view"),
    ("shared.monthly-reports", "MOBO", "view"),
    ("shared.monthly-reports", "PC", "edit"),
    ("shared.monthly-reports", "COMPLIANCE", "view"),
    ("shared.monthly-reports", "ADMIN", "edit"),
    ("mobo.recon-overview", "MOBO", "edit"),
    ("mobo.recon-overview", "PC", "view"),
    ("mobo.recon-overview", "COMPLIANCE", "view"),
    ("mobo.recon-overview", "ADMIN", "edit"),
    ("mobo.trade-reconciliation", "MOBO", "edit"),
    ("mobo.trade-reconciliation", "PC", "view"),
    ("mobo.trade-reconciliation", "COMPLIANCE", "view"),
    ("mobo.trade-reconciliation", "ADMIN", "edit"),
    ("mobo.post-trade-allocation", "MOBO", "edit"),
    ("mobo.post-trade-allocation", "PC", "view"),  # D-10: PC is READ-ONLY here
    ("mobo.post-trade-allocation", "COMPLIANCE", "view"),
    ("mobo.post-trade-allocation", "ADMIN", "edit"),
    ("mobo.commission-tracking", "MOBO", "edit"),
    ("mobo.commission-tracking", "ADMIN", "edit"),
    ("pc.model-management", "RM", "view"),
    ("pc.model-management", "MOBO", "view"),
    ("pc.model-management", "PC", "edit"),
    ("pc.model-management", "COMPLIANCE", "view"),
    ("pc.model-management", "ADMIN", "edit"),
    ("pc.allocation-matrix", "MOBO", "view"),
    ("pc.allocation-matrix", "PC", "edit"),
    ("pc.allocation-matrix", "COMPLIANCE", "view"),
    ("pc.allocation-matrix", "ADMIN", "edit"),
    ("pc.allotment-redemption", "RM", "view"),
    ("pc.allotment-redemption", "MOBO", "view"),
    ("pc.allotment-redemption", "PC", "edit"),
    ("pc.allotment-redemption", "COMPLIANCE", "view"),
    ("pc.allotment-redemption", "ADMIN", "edit"),
    ("compliance.overview", "PC", "view"),
    ("compliance.overview", "COMPLIANCE", "edit"),
    ("compliance.overview", "ADMIN", "edit"),
    ("compliance.review", "PC", "view"),
    ("compliance.review", "COMPLIANCE", "edit"),
    ("compliance.review", "ADMIN", "edit"),
    ("admin.enroll-user", "ADMIN", "edit"),
    ("admin.system-config", "ADMIN", "edit"),
]
assert len(PAGE_ACCESS_SEED) == 55
assert sum(1 for _, _, lvl in PAGE_ACCESS_SEED if lvl == "edit") == 30
assert sum(1 for _, _, lvl in PAGE_ACCESS_SEED if lvl == "view") == 25
_ROLE_COUNTS = {"RM": 7, "MOBO": 10, "PM": 0, "PC": 10, "COMPLIANCE": 12, "ADMIN": 16}
for _role, _n in _ROLE_COUNTS.items():
    assert sum(1 for _, r, _ in PAGE_ACCESS_SEED if r == _role) == _n, _role


# --------------------------------------------------------------------------
# DB engine / session
# --------------------------------------------------------------------------
@pytest.fixture
def engine():
    eng = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(eng)
    return eng


@pytest.fixture
def SessionLocal(engine):
    return sessionmaker(bind=engine, expire_on_commit=False)


@pytest.fixture
def session(SessionLocal) -> Iterator[Session]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# --------------------------------------------------------------------------
# Row builders -- plain session.add + commit, mirroring
# tests/libs/onboarding/conftest.py's / tests/libs/staff/conftest.py's style.
# --------------------------------------------------------------------------
def seed_page_access(session: Session, rows: list[tuple[str, str, str]] | None = None) -> None:
    for page_id, role, level in rows if rows is not None else PAGE_ACCESS_SEED:
        session.add(PageAccess(page_id=page_id, role=AdminRole(role), level=AccessLevel(level)))
    session.commit()


def make_admin_user(
    session: Session,
    role: AdminRole,
    *,
    name: str | None = "Some Admin",
    firebase_uid: str | None = None,
    status: AccountStatus = AccountStatus.ACTIVE,
    last_sign_in_at: datetime | None = None,
    department: str | None = None,
) -> User:
    """Seeds a Portal.ADMIN user + AdminProfile(role=role). page_access rows are
    role-keyed (not per-user), so a freshly-made admin with no overrides of its
    own automatically inherits its role's seeded standing levels -- useful when
    a test needs a "clean" user of a given role untouched by `world`'s deliberate
    per-user overrides."""
    user = User(
        id=uuid.uuid4(),
        firebase_uid=firebase_uid or f"{role.value.lower()}-uid-{uuid.uuid4()}",
        email=f"{role.value.lower()}-{uuid.uuid4().hex[:6]}@example.com",
        portal=Portal.ADMIN,
        status=status,
        last_sign_in_at=last_sign_in_at,
    )
    session.add(user)
    session.flush()
    session.add(AdminProfile(user_id=user.id, role=role, name=name, department=department))
    session.commit()
    session.refresh(user)
    # BE-2: load admin_profile onto the instance now, in case a caller closes
    # `session` before use in app.dependency_overrides -- an already-loaded
    # attribute is never lazy-loaded on the detached instance.
    session.refresh(user, attribute_names=["admin_profile"])
    return user


def make_client_user(
    session: Session, *, assigned_rm_uid: str | None = None, name: str = "Cathy Client"
) -> User:
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"client-uid-{uuid.uuid4()}",
        email=f"{name.lower().replace(' ', '.')}@example.com",
        portal=Portal.CLIENT,
        status=AccountStatus.ACTIVE,
    )
    session.add(user)
    session.flush()
    session.add(ClientProfile(user_id=user.id, name=name, assigned_rm_uid=assigned_rm_uid))
    session.commit()
    session.refresh(user)
    return user


def make_ticket(
    session: Session,
    client_user: User,
    rm_uid: str | None,
    *,
    status: TicketStatus = TicketStatus.NEW,
    kind: TicketKind = TicketKind.OTHER,
    reference: str | None = None,
) -> ClientTicket:
    ticket = ClientTicket(
        id=uuid.uuid4(),
        user_id=client_user.id,
        assigned_rm_uid=rm_uid,
        reference=reference or f"TK-{uuid.uuid4().hex[:8].upper()}",
        kind=kind,
        status=status,
        message="test ticket",
    )
    session.add(ticket)
    session.commit()
    return ticket


def make_override(
    session: Session,
    user: User,
    page_id: str,
    level: OverrideLevel,
    *,
    reason: str = "test reason",
    granted_by: str | None = None,
    expires_at: datetime | None = None,
) -> PageAccessOverride:
    row = PageAccessOverride(
        id=uuid.uuid4(),
        user_id=user.id,
        page_id=page_id,
        level=level,
        reason=reason,
        granted_by=granted_by,
        expires_at=expires_at,
    )
    session.add(row)
    session.commit()
    session.refresh(row)
    return row


def make_publication(
    session: Session,
    *,
    actor_uid: str | None = None,
    actor_name: str | None = None,
    change_count: int = 0,
    note: str | None = None,
    published_at: datetime | None = None,
) -> PageAccessPublication:
    row = PageAccessPublication(
        actor_uid=actor_uid,
        actor_name=actor_name,
        change_count=change_count,
        note=note,
    )
    if published_at is not None:
        row.published_at = published_at
    session.add(row)
    session.commit()
    session.refresh(row)
    return row


def make_audit(
    session: Session,
    *,
    actor_uid: str | None = None,
    actor_name: str | None = None,
    event: str,
    detail: str,
    at: datetime | None = None,
) -> AdminAuditEvent:
    row = AdminAuditEvent(
        id=uuid.uuid4(),
        actor_uid=actor_uid,
        actor_name=actor_name,
        event=event,
        detail=detail,
    )
    if at is not None:
        row.at = at
    session.add(row)
    session.commit()
    session.refresh(row)
    return row


# --------------------------------------------------------------------------
# The §8.1 seeded world: 55-row page_access seed + one ADMIN, one RM with 3
# clients (2 open + 1 resolved ticket), an empty-book RM, a second ACTIVE RM
# (handover receiver), a DEACTIVATED RM, one PC, one COMPLIANCE, one PM, plus
# one unexpired override, one expired override, and one level='none' override.
# --------------------------------------------------------------------------
@pytest.fixture
def world(session: Session, SessionLocal) -> SimpleNamespace:
    seed_page_access(session)

    admin = make_admin_user(session, AdminRole.ADMIN, name="Ada Admin", firebase_uid="uid-admin")
    rm_primary = make_admin_user(
        session, AdminRole.RM, name="Rita RM", firebase_uid="uid-rm-primary"
    )
    rm_receiver = make_admin_user(
        session, AdminRole.RM, name="Rick Receiver", firebase_uid="uid-rm-receiver"
    )
    rm_empty = make_admin_user(
        session, AdminRole.RM, name="Remy Empty", firebase_uid="uid-rm-empty"
    )
    rm_deactivated = make_admin_user(
        session,
        AdminRole.RM,
        name="Dee Deactivated",
        firebase_uid="uid-rm-deactivated",
        status=AccountStatus.DISABLED,
    )
    pc = make_admin_user(session, AdminRole.PC, name="Penny PC", firebase_uid="uid-pc")
    compliance = make_admin_user(
        session, AdminRole.COMPLIANCE, name="Cory Compliance", firebase_uid="uid-compliance"
    )
    pm = make_admin_user(session, AdminRole.PM, name="Pat PM", firebase_uid="uid-pm")

    clients = [
        make_client_user(session, assigned_rm_uid=rm_primary.firebase_uid, name=f"Client {i}")
        for i in range(3)
    ]
    ticket_open_new = make_ticket(
        session, clients[0], rm_primary.firebase_uid, status=TicketStatus.NEW, reference="TK-NEW-1"
    )
    ticket_open_progress = make_ticket(
        session,
        clients[1],
        rm_primary.firebase_uid,
        status=TicketStatus.IN_PROGRESS,
        reference="TK-PROG-1",
    )
    ticket_resolved = make_ticket(
        session,
        clients[2],
        rm_primary.firebase_uid,
        status=TicketStatus.RESOLVED,
        reference="TK-RES-1",
    )

    now = datetime.now(timezone.utc)
    # Unexpired VIEW override downgrading PC's seeded EDIT on pc.model-management.
    override_view_unexpired = make_override(
        session,
        pc,
        "pc.model-management",
        OverrideLevel.VIEW,
        reason="temporary downgrade",
        expires_at=now + timedelta(days=30),
    )
    # Unexpired NONE override revoking ADMIN's seeded EDIT on admin.system-config
    # for this one person -- D-3's "active revocation" case.
    override_none_unexpired = make_override(
        session,
        admin,
        "admin.system-config",
        OverrideLevel.NONE,
        reason="revoked pending review",
        expires_at=None,
    )
    # Expired NONE override on compliance.review (COMPLIANCE's seeded EDIT) --
    # must NOT suppress the role level; it is invisible.
    override_none_expired = make_override(
        session,
        compliance,
        "compliance.review",
        OverrideLevel.NONE,
        reason="expired revocation",
        expires_at=now - timedelta(days=1),
    )

    return SimpleNamespace(
        SessionLocal=SessionLocal,
        admin=admin,
        rm_primary=rm_primary,
        rm_receiver=rm_receiver,
        rm_empty=rm_empty,
        rm_deactivated=rm_deactivated,
        pc=pc,
        compliance=compliance,
        pm=pm,
        clients=clients,
        ticket_open_new=ticket_open_new,
        ticket_open_progress=ticket_open_progress,
        ticket_resolved=ticket_resolved,
        override_view_unexpired=override_view_unexpired,
        override_none_unexpired=override_none_unexpired,
        override_none_expired=override_none_expired,
    )


def override_get_db(SessionLocal):
    """Builds a FastAPI `get_db` dependency-override bound to one engine/Session
    factory, mirroring app/libs/trade_models/test_router_symbols.py's pattern."""

    def _get_db():
        db = SessionLocal()
        try:
            yield db
        finally:
            db.close()

    return _get_db


@pytest.fixture
def api_client(world):
    """TestClient wired against `world`'s engine, mirroring
    app/libs/trade_models/test_router_symbols.py's `client` fixture. Only
    references already-committed modules (app.core.database, app.libs.auth.deps,
    app.main) so this fixture collects cleanly even though app.libs.access.router
    (BE-8) doesn't exist yet -- the route tests themselves fail at their own
    `from app.libs.access... import ...` line, not here.

    Yields (TestClient, set_actor) where set_actor(user) swaps which admin user
    `get_current_admin_user` resolves to for the rest of the test."""
    from fastapi.testclient import TestClient

    from app.core.database import get_db
    from app.libs.auth.deps import get_current_admin_user
    from app.main import app

    app.dependency_overrides[get_db] = override_get_db(world.SessionLocal)

    def _set_actor(user):
        app.dependency_overrides[get_current_admin_user] = lambda: user

    _set_actor(world.admin)
    try:
        yield TestClient(app), _set_actor
    finally:
        app.dependency_overrides.clear()
