// Generated by test-gen (standard) from docs/implementations/011-2026-07-13-post-trade-allocation-fe.md §FE-5.
// Regenerate: /test-gen standard.
import { describe, expect, it } from "vitest";
import { fireEvent, render, screen } from "@testing-library/react";
import { Donut } from "@/components/mobo/allocation/Panels";
import { ptaMoney } from "@/lib/mobo/allocation";
import type { PtaClientShare } from "@/lib/mobo/types";

const SHARES: PtaClientShare[] = [
  { clientId: "3a11", name: "Strathmore Fund", units: 5, allocated: 1_360_000, pct: 20 },
  { clientId: "4b22", name: "Anchor Capital", units: 20, allocated: 5_440_000, pct: 80 },
];

describe("FE-5 Donut — reads share.allocated (renamed from share.delegated)", () => {
  it("renders one arc per client plus the center value/sub labels", () => {
    const { container } = render(<Donut shares={SHARES} centerVal={ptaMoney(6_800_000)} centerSub="traded" />);
    expect(container.querySelectorAll("circle")).toHaveLength(SHARES.length);
    expect(screen.getByText("traded")).toBeInTheDocument();
    expect(screen.getByText(ptaMoney(6_800_000))).toBeInTheDocument();
  });

  it("hovering a segment shows a tooltip with that client's allocated amount and pct", () => {
    const { container } = render(<Donut shares={SHARES} centerVal={ptaMoney(6_800_000)} centerSub="traded" />);
    const circles = container.querySelectorAll("circle");
    fireEvent.mouseEnter(circles[0]);
    expect(screen.getByText(SHARES[0].name)).toBeInTheDocument();
    expect(screen.getByText(ptaMoney(SHARES[0].allocated))).toBeInTheDocument();
    expect(screen.getByText(`${SHARES[0].pct}%`)).toBeInTheDocument();
  });

  it("sizes each arc's length by allocated/total, not by the pre-rounded pct", () => {
    const { container } = render(<Donut shares={SHARES} centerVal={ptaMoney(6_800_000)} centerSub="traded" />);
    const circles = container.querySelectorAll("circle");
    const [dash0] = circles[0].getAttribute("stroke-dasharray")!.split(" ").map(Number);
    const [dash1] = circles[1].getAttribute("stroke-dasharray")!.split(" ").map(Number);
    expect(dash0 / dash1).toBeCloseTo(SHARES[0].allocated / SHARES[1].allocated, 1);
  });

  it("falls back to a total of 1 (no divide-by-zero/NaN) when every share is zero", () => {
    const zeroShares: PtaClientShare[] = [{ clientId: "z1", name: "Zero Co", units: 1, allocated: 0, pct: 0 }];
    const { container } = render(<Donut shares={zeroShares} centerVal="$0" centerSub="traded" />);
    expect(container.querySelector("circle")!.getAttribute("stroke-dasharray")).not.toContain("NaN");
  });
});
