// Generated by test-gen (standard) from docs/implementations/011-2026-07-13-post-trade-allocation-fe.md §FE-5.
// Regenerate: /test-gen standard.
import type { ComponentType, ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { render } from "@testing-library/react";
import type { PtaModelAllocation } from "@/lib/mobo/types";
import { clientColor } from "@/components/mobo/allocation/Panels";
import { ptaMoney } from "@/lib/mobo/allocation";

let capturedTooltipContent: ComponentType<Record<string, unknown>> | undefined;
let capturedBars: { dataKey: string; fill: string }[] = [];

// Recharts needs real layout (ResponsiveContainer measuring a DOM box) to
// mount its children, which jsdom doesn't provide — mocked per the §8.1
// convention (no seam mocks needed for this pure-render unit, but recharts
// itself is a rendering dependency, not the seam under test) so the tooltip
// content function and each Bar's props are exercised directly instead.
vi.mock("recharts", () => ({
  ResponsiveContainer: ({ children }: { children: ReactNode }) => children,
  BarChart: ({ children }: { children: ReactNode }) => <>{children}</>,
  XAxis: () => null,
  YAxis: () => null,
  Tooltip: ({ content }: { content: ComponentType<Record<string, unknown>> }) => {
    capturedTooltipContent = content;
    return null;
  },
  Bar: (props: { dataKey: string; fill?: string }) => {
    if (props.fill && props.fill !== "transparent") capturedBars.push({ dataKey: props.dataKey, fill: props.fill });
    return null;
  },
}));

import { StackedBarChart } from "@/components/mobo/allocation/StackedBarChart";

const MODELS: PtaModelAllocation[] = [
  {
    id: "9f2c",
    name: "Zero",
    acct: "U-1234567",
    traded: 6_800_000,
    unitsTotal: 25,
    clientShares: [
      { clientId: "3a11", name: "Strathmore Fund", units: 5, allocated: 1_360_000, pct: 20 },
      { clientId: "4b22", name: "Anchor Capital", units: 20, allocated: 5_440_000, pct: 80 },
    ],
  },
];

describe("FE-5 StackedBarChart — reads cs.allocated/share.allocated (renamed from delegated)", () => {
  beforeEach(() => {
    capturedBars = [];
    capturedTooltipContent = undefined;
  });

  it("renders one Bar per client, colored via the shared clientColor(clientId)", () => {
    render(<StackedBarChart models={MODELS} orientation="vertical" />);
    expect(capturedBars).toEqual(
      expect.arrayContaining(
        MODELS[0].clientShares.map((cs) => ({ dataKey: cs.clientId, fill: clientColor(cs.clientId) })),
      ),
    );
  });

  it("the tooltip content renders the hovered client's allocated amount and pct", () => {
    render(<StackedBarChart models={MODELS} orientation="vertical" />);
    const Content = capturedTooltipContent!;
    const share = MODELS[0].clientShares[0];
    const row = {
      modelId: MODELS[0].id,
      modelName: MODELS[0].name,
      modelAcct: MODELS[0].acct,
      shares: { [share.clientId]: share },
    };
    const { getByText } = render(
      <Content active payload={[{ dataKey: share.clientId, color: "#fff", payload: row }]} />,
    );
    expect(getByText(share.name)).toBeInTheDocument();
    expect(getByText(ptaMoney(share.allocated))).toBeInTheDocument();
    expect(getByText(`${share.pct}%`)).toBeInTheDocument();
  });

  it("the tooltip renders nothing when inactive or the payload is empty", () => {
    render(<StackedBarChart models={MODELS} orientation="vertical" />);
    const Content = capturedTooltipContent!;
    const { container: inactive } = render(<Content active={false} payload={[]} />);
    expect(inactive).toBeEmptyDOMElement();
    const { container: noPayload } = render(<Content active payload={[]} />);
    expect(noPayload).toBeEmptyDOMElement();
  });
});
