"""Shared fixtures/doubles for tests/libs/staff (BE-15..BE-17).

Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-15..BE-17.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Layer isolation: only imports app/ + stdlib + pytest + sqlalchemy. Does NOT import
app.libs.identity -- that module does not exist on this branch yet. FakeIdentityService
is the shared test double (tests/conftest.py, BE-2) re-exported here -- it is not an
import of the real service, nor of identity's own fake (tests/libs/identity/conftest.py),
precisely so this dir collects without ever touching app.libs.identity.

Pre-implementation note: app.libs.staff does not exist on this branch yet (BE-15/16/17
are unimplemented) -- collection of test_be15_enroll.py / test_be16_update_toctou.py /
test_be17_router.py is expected to fail with ModuleNotFoundError until those units land.
This conftest itself only imports app.models.users + stdlib + pytest + sqlalchemy, so it
collects cleanly on its own.
"""

from __future__ import annotations

import uuid
from typing import Iterator

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

from app.core.database import Base
from app.models.users import AccountStatus, AdminProfile, AdminRole, Portal, User
from tests.conftest import FakeIdentityService, make_admin_stub  # noqa: F401 -- BE-2 shared helpers


@pytest.fixture
def session() -> Iterator[Session]:
    """In-memory SQLite session -- mirrors tests/models/conftest.py's pattern."""
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# FakeIdentityService moved to tests/conftest.py (BE-2) -- imported above. The
# `fake-uid-N` prefix it mints (not `fake-staff-uid-N`) is the shared double's
# prefix; test_be15_enroll.py's one assertion pinning the old staff-specific
# prefix was updated to match.


def make_admin_user(
    session: Session,
    *,
    role: AdminRole = AdminRole.ADMIN,
    status: AccountStatus = AccountStatus.ACTIVE,
    email: str | None = None,
    authorized_by: str | None = None,
) -> User:
    """Seeds one User(portal=ADMIN) + AdminProfile(role=role) pair directly via the
    ORM, bypassing StaffService entirely -- for TOCTOU/guard test setup that needs
    pre-existing admins/RMs before the unit under test runs."""
    firebase_uid = f"admin-{uuid.uuid4()}"
    user = User(
        id=uuid.uuid4(),
        firebase_uid=firebase_uid,
        email=email or f"{firebase_uid}@example.com",
        portal=Portal.ADMIN,
        status=status,
        authorized_by=authorized_by,
    )
    session.add(user)
    session.flush()
    session.add(AdminProfile(user_id=user.id, role=role))
    session.commit()
    session.refresh(user)
    # BE-2: load admin_profile onto the instance now -- callers (e.g. router
    # fixtures) may close `session` right after this returns, and an
    # already-loaded attribute is never lazy-loaded on the detached instance.
    session.refresh(user, attribute_names=["admin_profile"])
    return user


def make_active_admins(session: Session, n: int) -> list[User]:
    """N active AdminRole.ADMIN rows, for count_active_admins/TOCTOU setup."""
    return [make_admin_user(session, role=AdminRole.ADMIN, status=AccountStatus.ACTIVE) for _ in range(n)]


def make_client_user(session: Session, *, status: AccountStatus = AccountStatus.ACTIVE) -> User:
    """A bare Portal.CLIENT user -- for the "target is a client-portal user" 409 case.
    No ClientProfile needed: StaffService.update rejects on user.portal before ever
    touching a profile table."""
    user = User(
        id=uuid.uuid4(),
        firebase_uid=f"client-{uuid.uuid4()}",
        email="client@example.com",
        portal=Portal.CLIENT,
        status=status,
    )
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


# ============================================================================
# 019 section -- Admin Access Control & Staff Enrollment (BE-15..BE-19)
#
# Generated by test-gen (thorough) from
# docs/implementations/019-admin-access-control-and-staff-enrollment-be.md §8.1.
# Regenerate: /test-gen thorough docs/implementations/019-admin-access-control-and-staff-enrollment-be.md
#
# Purely additive: nothing above this line (the 004 fixtures) is modified.
# Layer isolation: app/ + stdlib + pytest + sqlalchemy + fastapi.testclient only.
#
# Pre-implementation note: app.libs.staff/{service,repository,router}.py and
# app.schemas.staff are all in their PRE-019 shape on this branch -- the new
# StaffDirectoryRow, OPEN_TICKET_STATUSES, _handover_block, reassign_book(),
# StaffOverrideIn, StaffCreatedOut, LinkSentOut etc. do not exist yet. Tests
# built on these fixtures are expected to fail (ImportError/AttributeError/404)
# until BE-15..BE-19 land -- see the top-level docstring in each test_be1{5..9}
# file for the exact expected failure per test.
# ============================================================================

from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Iterator as _Iterator019

from fastapi.testclient import TestClient
from sqlalchemy import event
from sqlalchemy.engine import Engine
from sqlalchemy.pool import StaticPool

from app.core.database import get_db
from app.libs.auth.deps import get_current_admin_user
from app.main import app as _main_app
from app.models.onboarding import ClientTicket, TicketKind, TicketStatus
from app.models.users import ClientProfile
from tests.libs.access.conftest import seed_page_access

NOW_UTC = datetime.now(timezone.utc)


@contextmanager
def count_queries(engine: Engine) -> _Iterator019[list[str]]:
    """Counts SQL statements executed against `engine` for the duration of the
    `with` block. `len(calls)` is the exact-query-count assertion BE-16 needs.
    Uses SQLAlchemy's own event hook -- no query-counting dependency added."""
    calls: list[str] = []

    def _before(conn, cursor, statement, parameters, context, executemany) -> None:
        calls.append(statement)

    event.listen(engine, "before_cursor_execute", _before)
    try:
        yield calls
    finally:
        event.remove(engine, "before_cursor_execute", _before)


class FakeSetPasswordMailer:
    """Test double for `send_set_password_email` (BE-14's seam). Call-tracked;
    `result` is the bool the real function returns for a successful/failed send.
    When `order` is passed, "email_sent" is appended to it -- paired with
    `_CommitFailSession` below to prove BE-17's "email strictly after commit"
    ordering invariant without timestamps.

    Takes no `link`/`name`: Firebase mints the one-time code as it sends, and its
    single project-wide template cannot be personalised."""

    def __init__(self, *, result: bool = True, order: list[str] | None = None) -> None:
        self.result = result
        self.calls: list[dict] = []
        self._order = order

    def __call__(self, *, to: str, portal, settings) -> bool:
        self.calls.append({"to": to, "portal": portal})
        if self._order is not None:
            self._order.append("email_sent")
        return self.result


class FakeAccountReadyMailer:
    """Test double for `send_account_ready_email` (Fix 3's generated-password
    enrollment flow) -- same call-tracked/orderable shape as
    FakeSetPasswordMailer, but matching that function's link-less signature."""

    def __init__(self, *, result: bool = True, order: list[str] | None = None) -> None:
        self.result = result
        self.calls: list[dict] = []
        self._order = order

    def __call__(self, *, to: str, name: str | None, portal, settings) -> bool:
        self.calls.append({"to": to, "name": name, "portal": portal})
        if self._order is not None:
            self._order.append("email_sent")
        return self.result


class FakeStaffIdentityService:
    """§8.1 identity double for BE-17/BE-18: ensure_identity / delete_user /
    generate_set_password_link, plus a tracked (never-should-be-called)
    update_user so BE-18's "no credential mutation" invariant is asserted
    against a real call list rather than the mere absence of a mock method.

    `existing={"email": "uid"}` seeds an ADOPTED identity (ensure_identity
    returns created=False for it) -- BE-17's "adopted identity is never
    deleted on compensation" negative saga needs exactly this."""

    def __init__(self, *, existing: dict[str, str] | None = None) -> None:
        self._existing: dict[str, str] = dict(existing or {})
        self._counter = 0
        self._link_counter = 0
        self.ensure_identity_calls: list[str] = []
        self.delete_user_calls: list[str] = []
        self.generate_set_password_link_calls: list[str] = []
        self.update_user_calls: list[tuple] = []

    def ensure_identity(self, email: str, password: str | None = None) -> tuple[str, bool]:
        self.ensure_identity_calls.append(email)
        existing_uid = self._existing.get(email)
        if existing_uid is not None:
            if password is not None:
                self.update_user_calls.append((existing_uid, {"password": password}))
            return existing_uid, False
        self._counter += 1
        uid = f"fake-staff-uid-{self._counter}"
        self._existing[email] = uid
        return uid, True

    def delete_user(self, uid: str) -> None:
        self.delete_user_calls.append(uid)
        for email, existing_uid in list(self._existing.items()):
            if existing_uid == uid:
                del self._existing[email]

    def generate_set_password_link(self, email: str) -> str:
        self._link_counter += 1
        self.generate_set_password_link_calls.append(email)
        return f"https://fake-staff.invalid/set-password?email={email}&n={self._link_counter}"

    def update_user(self, uid: str, **kwargs) -> None:  # pragma: no cover -- must stay unused
        self.update_user_calls.append((uid, kwargs))


class CommitFailSession:
    """Thin proxy around a real Session: `commit()` raises the first
    `fail_times` calls, then behaves normally. Every other attribute proxies
    straight through. Lets BE-17's forced-commit-failure sagas (compensating
    delete_user) be driven through the real router/service/repository stack
    over a real (in-memory) DB, instead of mocking the ORM."""

    def __init__(self, real_session, *, fail_times: int = 1, order: list[str] | None = None) -> None:
        self._real = real_session
        self._fail_times = fail_times
        self._order = order

    def commit(self):
        if self._fail_times > 0:
            self._fail_times -= 1
            raise RuntimeError("forced commit failure (test double)")
        if self._order is not None:
            self._order.append("commit")
        return self._real.commit()

    def __getattr__(self, name):
        return getattr(self._real, name)


def mk_admin_portal_user(
    session: Session,
    *,
    role: AdminRole,
    status: AccountStatus = AccountStatus.ACTIVE,
    last_sign_in_at: datetime | None = None,
    email: str | None = None,
    name: str | None = None,
    department: str | None = None,
) -> User:
    """One users(portal=ADMIN) + admin_profiles(role=role) pair, seeded directly
    via the ORM (bypassing StaffService, which is the thing under test)."""
    uid = f"be019-{role.value.lower()}-{uuid.uuid4().hex[:8]}"
    user = User(
        id=uuid.uuid4(),
        firebase_uid=uid,
        email=email or f"{uid}@megaannum.ai",
        portal=Portal.ADMIN,
        status=status,
        last_sign_in_at=last_sign_in_at,
    )
    session.add(user)
    session.flush()
    session.add(AdminProfile(user_id=user.id, role=role, name=name or uid, department=department))
    session.commit()
    session.refresh(user)
    # BE-2: load admin_profile onto the instance -- seed_be019_roster's caller
    # (be019_client) closes this session right after seeding, before handing
    # these users to app.dependency_overrides[get_current_admin_user].
    session.refresh(user, attribute_names=["admin_profile"])
    return user


def mk_client_with_rm(session: Session, *, rm_uid: str | None) -> User:
    """One users(portal=CLIENT) + client_profiles row, assigned to `rm_uid`."""
    uid = f"be019-client-{uuid.uuid4().hex[:8]}"
    user = User(
        id=uuid.uuid4(),
        firebase_uid=uid,
        email=f"{uid}@example.com",
        portal=Portal.CLIENT,
        status=AccountStatus.ACTIVE,
    )
    session.add(user)
    session.flush()
    session.add(ClientProfile(user_id=user.id, name=uid, assigned_rm_uid=rm_uid))
    session.commit()
    session.refresh(user)
    return user


def mk_ticket(
    session: Session, *, client_user: User, rm_uid: str, status: TicketStatus, ref: str
) -> ClientTicket:
    ticket = ClientTicket(
        id=uuid.uuid4(),
        user_id=client_user.id,
        assigned_rm_uid=rm_uid,
        reference=ref,
        kind=TicketKind.OTHER,
        status=status,
        message=f"seed ticket {ref}",
    )
    session.add(ticket)
    session.commit()
    session.refresh(ticket)
    return ticket


def seed_be019_roster(session: Session) -> dict:
    """§8.1's test-setup roster in one call: one ADMIN (the sole active admin --
    load-bearing for the last-active-ADMIN guard test), an RM with 3 clients + 2
    open (new/in_progress) + 1 resolved ticket, an empty-book RM, a second ACTIVE
    RM (the handover receiver), a DEACTIVATED RM, one PC, one COMPLIANCE, one PM.

    Returns a dict keyed by role name (`"clients"` holds the 3 ClientProfile
    owners). `rm_booked` and `pm` are seeded with last_sign_in_at=None so BE-16's
    derived-INITIATED path is exercised by the shared roster too.

    Corrected 2026-07-30 (orchestrator, Wave 5 gate): also seeds the real
    55-row `page_access` policy (tests/libs/access/conftest.py's
    `seed_page_access`, reused rather than duplicated) -- this fixture's own
    docstring always assumed the caller would hold "full USER_VIEW/USER_WRITE
    access once BE-1/BE-2/BE-5 land," but the row-seeding call was missing, so
    every BE-16..BE-19 route test 403'd the instant BE-5 made `require_action`
    resolve from the DB instead of the deleted `ROLE_ACTIONS` fallback."""
    seed_page_access(session)
    admin = mk_admin_portal_user(session, role=AdminRole.ADMIN, last_sign_in_at=NOW_UTC)
    rm_booked = mk_admin_portal_user(session, role=AdminRole.RM, last_sign_in_at=None)
    rm_empty = mk_admin_portal_user(session, role=AdminRole.RM, last_sign_in_at=NOW_UTC)
    rm_receiver = mk_admin_portal_user(session, role=AdminRole.RM, last_sign_in_at=NOW_UTC)
    rm_deactivated = mk_admin_portal_user(
        session, role=AdminRole.RM, status=AccountStatus.DISABLED, last_sign_in_at=NOW_UTC
    )
    pc = mk_admin_portal_user(session, role=AdminRole.PC, last_sign_in_at=NOW_UTC)
    compliance = mk_admin_portal_user(session, role=AdminRole.COMPLIANCE, last_sign_in_at=NOW_UTC)
    pm = mk_admin_portal_user(session, role=AdminRole.PM, last_sign_in_at=None)

    clients = [mk_client_with_rm(session, rm_uid=rm_booked.firebase_uid) for _ in range(3)]
    mk_ticket(
        session, client_user=clients[0], rm_uid=rm_booked.firebase_uid,
        status=TicketStatus.NEW, ref="TCK-019-1",
    )
    mk_ticket(
        session, client_user=clients[1], rm_uid=rm_booked.firebase_uid,
        status=TicketStatus.IN_PROGRESS, ref="TCK-019-2",
    )
    mk_ticket(
        session, client_user=clients[2], rm_uid=rm_booked.firebase_uid,
        status=TicketStatus.RESOLVED, ref="TCK-019-3",
    )

    return {
        "admin": admin,
        "rm_booked": rm_booked,
        "rm_empty": rm_empty,
        "rm_receiver": rm_receiver,
        "rm_deactivated": rm_deactivated,
        "pc": pc,
        "compliance": compliance,
        "pm": pm,
        "clients": clients,
    }


@dataclass
class Be019Client:
    """Everything a BE-16..BE-19 route test needs: a TestClient mounted on the
    REAL app (app.main.app, per the repo's own /admin/staff mount), a
    sessionmaker for direct DB assertions, the raw engine (for count_queries),
    and the seeded §8.1 roster. `as_caller` swaps who `require_action`'s
    `get_current_admin_user` sub-dependency resolves to -- the same technique
    app/libs/trade_models/test_router_symbols.py uses."""

    http: TestClient
    Session: object
    engine: Engine
    users: dict = field(default_factory=dict)

    def as_caller(self, user: User) -> None:
        _main_app.dependency_overrides[get_current_admin_user] = lambda: user

    def db(self) -> Session:
        return self.Session()


@pytest.fixture
def be019_client() -> _Iterator019[Be019Client]:
    """SQLite in-memory + StaticPool (§8.1), seeded with seed_be019_roster(),
    caller defaulted to the seeded ADMIN (full USER_VIEW/USER_WRITE access once
    BE-1/BE-2/BE-5 land). `raise_server_exceptions=False` so an unhandled 500
    from a forced-failure saga (BE-17) surfaces as a status code, not a raised
    exception, at the test call site."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine, expire_on_commit=False)

    def _override_get_db():
        db = Session()
        try:
            yield db
        finally:
            db.close()

    seed_db = Session()
    users = seed_be019_roster(seed_db)
    seed_db.close()

    from app.core.config import Settings, get_settings

    _main_app.dependency_overrides[get_db] = _override_get_db
    _main_app.dependency_overrides[get_current_admin_user] = lambda: users["admin"]
    # firebase_auth_disabled=True -- set_portal_claims (called by StaffService.update
    # on a role change) no-ops instead of trying to reach a real Firebase project
    # (app/core/security.py:177). Route tests are exercising the staff HTTP
    # boundary, not Firebase claim-stamping.
    _main_app.dependency_overrides[get_settings] = lambda: Settings(firebase_auth_disabled=True)
    try:
        yield Be019Client(
            http=TestClient(_main_app, raise_server_exceptions=False),
            Session=Session,
            engine=engine,
            users=users,
        )
    finally:
        _main_app.dependency_overrides.clear()
