"""Generated by test-gen (thorough) from docs/implementations/004-auth-flow-rework-be.md §BE-15.
Regenerate: /test-gen thorough docs/implementations/004-auth-flow-rework-be.md

Covers StaffRepository.create_with_profile / .count_active_admins and
StaffService.enroll. `set_portal_claims` (§7-adjacent, imported into
app.libs.staff.service) is patched at its use site so no real Firebase call is
ever made; the Firebase-identity seam itself is faked via conftest's
FakeIdentityService (this layer's own local double, not identity's).

Pre-implementation note: app.libs.staff does not exist on this branch yet (BE-15
is unimplemented) -- collection is expected to fail with ModuleNotFoundError
until it lands.
Run: .venv/Scripts/python.exe -m pytest -q tests/libs/staff/test_be15_enroll.py
"""

from __future__ import annotations

from unittest.mock import patch

import pytest

from app.core.config import Settings
from app.libs.staff.repository import StaffRepository
from app.libs.staff.service import StaffService
from app.models.users import AccountStatus, AdminProfile, AdminRole, Portal, User
from tests.libs.staff.conftest import FakeIdentityService, make_active_admins, make_admin_user


# --- StaffRepository.create_with_profile ------------------------------------------


def test_create_with_profile_sets_status_active_explicitly_not_via_default(session):
    """Q-D/§4.9: admin enrollment always overrides the column's DISABLED default --
    assert the value directly rather than merely asserting truthiness, so a future
    refactor that accidentally relies on the default again is caught."""
    import uuid

    user_id = uuid.uuid4()
    repo = StaffRepository(session)
    repo.create_with_profile(
        user_id=user_id, firebase_uid="fb-rm-1", email="rm@example.com",
        role=AdminRole.RM, authorized_by="caller-uid", name="Riley RM",
    )
    session.commit()

    row = session.query(User).filter(User.id == user_id).one()
    assert row.status == AccountStatus.ACTIVE
    assert row.status is not AccountStatus.DISABLED
    assert row.portal == Portal.ADMIN


@pytest.mark.parametrize(
    "role,status,expected_count",
    [
        (AdminRole.RM, AccountStatus.ACTIVE, 0),
        (AdminRole.ADMIN, AccountStatus.DISABLED, 0),
        (AdminRole.ADMIN, AccountStatus.ACTIVE, 1),
    ],
)
def test_count_active_admins_filters_role_and_status(session, role, status, expected_count):
    make_admin_user(session, role=role, status=status)
    repo = StaffRepository(session)
    assert repo.count_active_admins() == expected_count


def test_count_active_admins_counts_only_active_admin_rows_mixed_set(session):
    make_admin_user(session, role=AdminRole.RM, status=AccountStatus.ACTIVE)
    make_admin_user(session, role=AdminRole.ADMIN, status=AccountStatus.DISABLED)
    make_admin_user(session, role=AdminRole.ADMIN, status=AccountStatus.ACTIVE)
    make_admin_user(session, role=AdminRole.ADMIN, status=AccountStatus.ACTIVE)
    repo = StaffRepository(session)
    assert repo.count_active_admins() == 2


# --- StaffService.enroll: positive --------------------------------------------------


def _enroll(session, *, role, email="new@example.com", identity=None, caller_uid="super-admin-uid"):
    identity = identity or FakeIdentityService()
    service = StaffService(session)
    with patch("app.libs.staff.service.set_portal_claims") as claim_mock:
        user, invite_link = service.enroll(
            caller_uid=caller_uid, email=email, name="New Staff", role=role,
            phone_number="555-0100", identity=identity, settings=Settings(),
        )
    return service, identity, claim_mock, user, invite_link


def test_enroll_role_rm_creates_new_active_internal_user(session):
    _service, identity, claim_mock, user, invite_link = _enroll(session, role=AdminRole.RM)

    assert user.portal == Portal.ADMIN
    assert user.status == AccountStatus.ACTIVE  # explicit, not the DISABLED column default
    assert user.admin_profile.role == AdminRole.RM
    assert invite_link  # generate_set_password_link's faked return value
    claim_mock.assert_called_once()


def test_enroll_role_admin_permits_a_second_active_admin(session):
    """Q-I: peer enrollment permitted -- a first ADMIN pre-exists, enroll a second."""
    make_admin_user(session, role=AdminRole.ADMIN, status=AccountStatus.ACTIVE)
    repo = StaffRepository(session)
    assert repo.count_active_admins() == 1

    _service, _identity, _claim_mock, user, _invite = _enroll(session, role=AdminRole.ADMIN)

    assert user.status == AccountStatus.ACTIVE
    assert user.admin_profile.role == AdminRole.ADMIN
    assert repo.count_active_admins() == 2


# --- StaffService.enroll: negative --------------------------------------------------


def test_enroll_firebase_fail_leaves_zero_db_rows(session):
    identity = FakeIdentityService()
    identity.fail_next_ensure(RuntimeError("firebase down"))
    service = StaffService(session)

    with patch("app.libs.staff.service.set_portal_claims"):
        with pytest.raises(RuntimeError, match="firebase down"):
            service.enroll(
                caller_uid="super-admin-uid", email="fails@example.com", name="Nope",
                role=AdminRole.RM, phone_number=None, identity=identity, settings=Settings(),
            )

    assert session.query(User).count() == 0
    assert session.query(AdminProfile).count() == 0


def test_enroll_commit_fail_on_newly_created_identity_triggers_compensating_delete(session):
    identity = FakeIdentityService()  # fresh email -> created=True
    service = StaffService(session)

    with patch("app.libs.staff.service.set_portal_claims"), \
         patch.object(session, "commit", side_effect=RuntimeError("db down")):
        with pytest.raises(RuntimeError, match="db down"):
            service.enroll(
                caller_uid="super-admin-uid", email="orphan@example.com", name="Orphan",
                role=AdminRole.RM, phone_number=None, identity=identity, settings=Settings(),
            )

    # the uid minted by ensure_identity (created=True) is exactly the one compensated away
    assert identity.ensure_identity_calls == ["orphan@example.com"]
    assert len(identity.delete_user_calls) == 1
    assert identity.delete_user_calls[0].startswith("fake-uid-")
    assert session.query(User).count() == 0


def test_enroll_commit_fail_on_adopted_identity_never_calls_delete(session):
    """Risk A1 invariant: created=False (adopted/pre-existing orphan email) means
    the identity pre-dated this call -- deleting it on a later DB failure would
    destroy an identity this call didn't create. Mirrors BE-12's pattern."""
    identity = FakeIdentityService(existing={"adopted@example.com": "pre-existing-uid"})
    service = StaffService(session)

    with patch("app.libs.staff.service.set_portal_claims"), \
         patch.object(session, "commit", side_effect=RuntimeError("db down")):
        with pytest.raises(RuntimeError, match="db down"):
            service.enroll(
                caller_uid="super-admin-uid", email="adopted@example.com", name="Adopted",
                role=AdminRole.RM, phone_number=None, identity=identity, settings=Settings(),
            )

    assert identity.delete_user_calls == []
    assert session.query(User).count() == 0


# --- StaffService.enroll: invariants -------------------------------------------------


@pytest.mark.parametrize("role", [AdminRole.RM, AdminRole.ADMIN, AdminRole.MOBO, AdminRole.PC])
def test_enroll_stamps_portal_claim_exactly_once_with_enrolled_role(session, role):
    _service, _identity, claim_mock, _user, _invite = _enroll(session, role=role, email=f"{role.value}@example.com")

    claim_mock.assert_called_once()
    args, _kwargs = claim_mock.call_args
    # set_portal_claims(uid, "admin", role.value, settings)
    assert args[1] == "admin"
    assert args[2] == role.value


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
