// Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-fe.md §FE-13.
// Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: `components/admin/config/OverridesLedger.tsx` does
// not exist yet (the ledger still lives at `components/admin/enroll/OverridesLedger.tsx`
// with `onBack`/`onAddOverride` props and its own `<PageHeader>`); `ViewSwitch` still has
// only "matrix"/"role"; `system-config/page.tsx` has no `?view=` handling or "Add
// override" action; `enroll-user/page.tsx`'s `View` union still has three members
// (directory/wizard/overrides). Every assertion below is expected to fail (module
// resolution or behavior mismatch) until FE-13 lands.
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi, beforeEach } from "vitest";

const mockUseAdminStore = vi.fn();
vi.mock("@/lib/admin/AdminStoreContext", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/lib/admin/AdminStoreContext")>()),
  useAdminStore: () => mockUseAdminStore(),
}));

const mockSearchParams = new URLSearchParams();
vi.mock("next/navigation", async (importOriginal) => ({
    ...(await importOriginal<typeof import("next/navigation")>()),
  useSearchParams: () => mockSearchParams,
  useRouter: () => ({ push: vi.fn(), replace: vi.fn() }),
  usePathname: () => "/admin/system-config",
}));

vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn(), warning: vi.fn() } }));

beforeEach(() => {
  mockUseAdminStore.mockReset();
  mockSearchParams.forEach((_, key) => mockSearchParams.delete(key));
});

const OVERRIDES_FIXTURE = [
  {
    id: "o1", firebase_uid: "u1", user_name: "Amara Rahim", user_role: "RM",
    page_id: "pc.model-management", page_label: "Model Management", page_path: "/pc/model-management",
    role_default: "NONE", level: "VIEW", reason: "x", granted_by: "Omar Bakri",
    expires_at: "2026-08-01T00:00:00Z", expiring_soon: true,
  },
  {
    id: "o2", firebase_uid: "u2", user_name: "Dana Okafor", user_role: "MOBO",
    page_id: "rm.client-info", page_label: "Client Information", page_path: "/rm/client-info",
    role_default: "NONE", level: "VIEW", reason: "y", granted_by: "Omar Bakri",
    expires_at: null, expiring_soon: false,
  },
];

describe("FE-13 components/admin/config/OverridesLedger.tsx (moved, header stripped)", () => {
  it("positive: renders four stat cards computed from the OverrideOut[] fixture, including the expiring-soon count", async () => {
    mockUseAdminStore.mockReturnValue({ overrides: OVERRIDES_FIXTURE, revokeOverride: vi.fn() });
    const { OverridesLedger } = await import("@/components/admin/config/OverridesLedger");
    render(<OverridesLedger />);
    expect(screen.getByText("Active overrides")).toBeInTheDocument();
    expect(screen.getByText("Expiring in 30 days")).toBeInTheDocument();
    expect(screen.getByText("Users affected")).toBeInTheDocument();
    expect(screen.getByText("Roles affected")).toBeInTheDocument();
    expect(screen.getByText("2")).toBeInTheDocument(); // Active overrides = 2
    expect(screen.getByText("1")).toBeInTheDocument(); // Expiring in 30 days = 1
  });

  it("negative: renders no PageHeader of its own and no 'Back to directory' button", async () => {
    mockUseAdminStore.mockReturnValue({ overrides: OVERRIDES_FIXTURE, revokeOverride: vi.fn() });
    const { OverridesLedger } = await import("@/components/admin/config/OverridesLedger");
    render(<OverridesLedger />);
    expect(screen.queryByRole("button", { name: /back to directory/i })).not.toBeInTheDocument();
    expect(screen.queryByText("Overrides")).not.toBeInTheDocument(); // the old page's own <PageHeader title>
  });
});

describe("FE-13 components/admin/Shared.tsx ViewSwitch — widens to three options", () => {
  it("offers Matrix, By role and Overrides, and switches between all three", async () => {
    const { ViewSwitch } = await import("@/components/admin/Shared");
    const onChange = vi.fn();
    const { rerender } = render(<ViewSwitch view={"matrix" as never} onChange={onChange} />);
    expect(screen.getByText("Matrix")).toBeInTheDocument();
    expect(screen.getByText("By role")).toBeInTheDocument();
    expect(screen.getByText("Overrides")).toBeInTheDocument();
    screen.getByText("Overrides").click();
    expect(onChange).toHaveBeenCalledWith("overrides");
    rerender(<ViewSwitch view={"overrides" as never} onChange={onChange} />);
  });
});

describe("FE-13 app/(roles)/admin/system-config/page.tsx", () => {
  beforeEach(() => {
    mockUseAdminStore.mockReturnValue({
      stagedList: [], totalPages: 16, overrides: OVERRIDES_FIXTURE,
      published: { at: "2026-07-01T00:00:00Z", by: "Omar Bakri" }, discard: vi.fn(),
      pages: [], roles: [], eff: vi.fn(() => "NONE"), ovrOn: vi.fn(() => false), staged: {},
      roleUsers: vi.fn(() => 0), revokeOverride: vi.fn(),
    });
  });

  it("positive: mounting with ?view=overrides renders the ledger", async () => {
    mockSearchParams.set("view", "overrides");
    const { default: SystemConfigPage } = await import("@/app/(roles)/admin/system-config/page");
    render(<SystemConfigPage />);
    expect(screen.getByText("Active overrides")).toBeInTheDocument();
  });

  it("positive: the 'Add override' header action appears on the overrides view", async () => {
    mockSearchParams.set("view", "overrides");
    const { default: SystemConfigPage } = await import("@/app/(roles)/admin/system-config/page");
    render(<SystemConfigPage />);
    expect(screen.getByRole("button", { name: /add override/i })).toBeInTheDocument();
  });

  it("negative: the 'Add override' action is absent on the matrix and role views", async () => {
    mockSearchParams.set("view", "matrix");
    const { default: SystemConfigPage } = await import("@/app/(roles)/admin/system-config/page");
    render(<SystemConfigPage />);
    expect(screen.queryByRole("button", { name: /add override/i })).not.toBeInTheDocument();
  });
});

describe("Fix B — enroll-user/page.tsx Directory has no override-management entry point", () => {
  it("renders no 'Overrides' header action or link — System Config's own Overrides view is the only entry point", async () => {
    mockUseAdminStore.mockReturnValue({
      users: [], overrides: OVERRIDES_FIXTURE, staff: [], ovrFor: () => [],
    });
    const { Directory } = await import("@/components/admin/enroll/Directory");
    render(
      <Directory
        filter="All" onFilterChange={vi.fn()} query="" onQueryChange={vi.fn()}
        kebab={null} onKebabChange={vi.fn()} onAudit={vi.fn()} onEnroll={vi.fn()}
        onEdit={vi.fn()} onReset={vi.fn()}
        onDeactivate={vi.fn()} onReactivate={vi.fn()}
      />,
    );
    expect(screen.queryByRole("link", { name: /overrides/i })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /overrides/i })).not.toBeInTheDocument();
  });
});
