"""Generated by test-gen (thorough) from
docs/implementations/011-2026-07-13-post-trade-allocation-be.md §BE-5.
Regenerate: /test-gen thorough docs/implementations/011-2026-07-13-post-trade-allocation-be.md

PostTradeAllocationView DTO — the frozen wire contract (impl doc §7.1).
Money crosses as JSON numbers in major units, never Decimal/DecimalString.

Run: .venv/Scripts/python.exe -m pytest -q tests/schemas/test_be5_post_trade_allocation_schemas.py
"""

from __future__ import annotations

import json

import pytest
from app.schemas.post_trade_allocation import (
    PostTradeAllocationView,
    PtaModelOut,
    PtaRunListEntryOut,
    PtaRunListOut,
    PtaRunResultOut,
)
from pydantic import ValidationError

EXAMPLE_PAYLOAD = {
    "tradeDate": "2026-06-03",
    "grandTotal": 11450000.0,
    "models": [
        {
            "id": "9f2c1a3e-0000-0000-0000-000000000001",
            "name": "Zero",
            "acct": "U-1234567",
            "traded": 6800000.0,
            "unitsTotal": 25.0,
            "clientShares": [
                {
                    "clientId": "3a11f2b0-0000-0000-0000-000000000002",
                    "name": "Strathmore Fund",
                    "units": 5.0,
                    "allocated": 1360000.0,
                    "pct": 20,
                }
            ],
        }
    ],
}


def test_view_round_trips_example_payload_shape():
    view = PostTradeAllocationView.model_validate(EXAMPLE_PAYLOAD)
    round_tripped = json.loads(view.model_dump_json())

    assert round_tripped["tradeDate"] == EXAMPLE_PAYLOAD["tradeDate"]
    assert round_tripped["grandTotal"] == EXAMPLE_PAYLOAD["grandTotal"]
    assert round_tripped["models"][0]["id"] == EXAMPLE_PAYLOAD["models"][0]["id"]
    assert (
        round_tripped["models"][0]["clientShares"][0]
        == EXAMPLE_PAYLOAD["models"][0]["clientShares"][0]
    )
    # No field renaming/nesting drift.
    assert set(round_tripped.keys()) == set(EXAMPLE_PAYLOAD.keys())
    assert set(round_tripped["models"][0].keys()) == set(EXAMPLE_PAYLOAD["models"][0].keys())


def test_money_fields_serialize_as_json_numbers_not_strings():
    view = PostTradeAllocationView.model_validate(EXAMPLE_PAYLOAD)
    dumped = view.model_dump()

    assert isinstance(dumped["grandTotal"], float)
    assert isinstance(dumped["models"][0]["traded"], float)
    assert isinstance(dumped["models"][0]["unitsTotal"], float)
    assert isinstance(dumped["models"][0]["clientShares"][0]["allocated"], float)


def test_client_share_pct_is_int():
    view = PostTradeAllocationView.model_validate(EXAMPLE_PAYLOAD)
    assert isinstance(view.models[0].clientShares[0].pct, int)


def test_negative_traded_and_allocated_round_trip(monkeypatch=None):
    """D-3: a losing day's negative money fields must survive serialization untouched."""
    payload = {
        **EXAMPLE_PAYLOAD,
        "grandTotal": -1360000.0,
        "models": [
            {
                **EXAMPLE_PAYLOAD["models"][0],
                "traded": -6800000.0,
                "clientShares": [
                    {**EXAMPLE_PAYLOAD["models"][0]["clientShares"][0], "allocated": -1360000.0}
                ],
            }
        ],
    }
    view = PostTradeAllocationView.model_validate(payload)
    assert view.grandTotal == -1360000.0
    assert view.models[0].traded == -6800000.0
    assert view.models[0].clientShares[0].allocated == -1360000.0


def test_empty_run_maps_to_zero_grand_total_and_no_models():
    view = PostTradeAllocationView(
        tradeDate="2026-06-05", grandTotal=0.0, models=[]
    )
    assert view.grandTotal == 0.0
    assert view.models == []


@pytest.mark.parametrize("missing_field", ["tradeDate", "grandTotal", "models"])
def test_missing_required_field_raises_validation_error(missing_field):
    payload = {k: v for k, v in EXAMPLE_PAYLOAD.items() if k != missing_field}
    with pytest.raises(ValidationError):
        PostTradeAllocationView.model_validate(payload)


def test_missing_client_share_field_raises_validation_error():
    payload = {
        **EXAMPLE_PAYLOAD,
        "models": [
            {
                **EXAMPLE_PAYLOAD["models"][0],
                "clientShares": [{"clientId": "x", "name": "y"}],  # missing units/allocated/pct
            }
        ],
    }
    with pytest.raises(ValidationError):
        PostTradeAllocationView.model_validate(payload)


def test_no_decimal_or_decimalstring_ever_appears_in_serialized_json():
    view = PostTradeAllocationView.model_validate(EXAMPLE_PAYLOAD)
    serialized = view.model_dump_json()
    parsed = json.loads(serialized)
    assert isinstance(parsed["grandTotal"], (int, float))
    assert not isinstance(parsed["grandTotal"], str)


# --- Sibling DTOs: run list + run result ----------------------------------------


def test_run_list_entry_round_trips():
    entry = PtaRunListEntryOut(date="2026-06-03", grandTotal=11450000.0)
    assert PtaRunListOut(runs=[entry]).model_dump()["runs"][0]["date"] == "2026-06-03"


def test_run_list_out_empty_runs_list_is_valid():
    assert PtaRunListOut(runs=[]).runs == []


def test_run_result_out_wraps_latest_view():
    view = PostTradeAllocationView.model_validate(EXAMPLE_PAYLOAD)
    entry = PtaRunListEntryOut(date="2026-06-03", grandTotal=11450000.0)
    result = PtaRunResultOut(newRuns=[entry], latest=view)
    dumped = result.model_dump()
    assert dumped["latest"]["tradeDate"] == "2026-06-03"
    assert len(dumped["newRuns"]) == 1


def test_run_result_out_accepts_empty_new_runs_with_empty_latest():
    empty_view = PostTradeAllocationView(
        tradeDate="2026-06-05", grandTotal=0.0, models=[]
    )
    result = PtaRunResultOut(newRuns=[], latest=empty_view)
    assert result.newRuns == []
    assert result.latest.models == []


def test_model_out_and_client_share_out_construct_from_attributes():
    class _FakeCell:
        clientId = "u-1"
        name = "Strathmore Fund"
        units = 5.0
        allocated = 1360000.0
        pct = 20

    class _FakeModel:
        id = "m-1"
        name = "Zero"
        acct = "U-1234567"
        traded = 6800000.0
        unitsTotal = 25.0
        clientShares = [_FakeCell()]

    out = PtaModelOut.model_validate(_FakeModel())
    assert out.clientShares[0].name == "Strathmore Fund"


def test_model_out_acct_placeholder_when_none():
    """D-4: acct is '—' when the model traded through no known IB account."""
    payload = {**EXAMPLE_PAYLOAD["models"][0], "acct": "—"}
    model_out = PtaModelOut.model_validate(payload)
    assert model_out.acct == "—"
