// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-5.
// Regenerate: /test-gen standard.
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const ADMIN_FRONTEND_ROOT = process.cwd();

function read(relPath: string): string {
  return fs.readFileSync(path.resolve(ADMIN_FRONTEND_ROOT, relPath), "utf-8");
}

// Plain array return (not a generator) — this tsconfig has no `target` set
// (defaults below ES2015), so iterating a Generator trips TS2802.
function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === ".next" || entry.name === "tests") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (/\.(ts|tsx)$/.test(entry.name)) out.push(full);
  }
  return out;
}

function sweep(pattern: RegExp): string[] {
  const offenders: string[] = [];
  for (const dir of ["app", "components", "hooks", "lib", "server"]) {
    const abs = path.resolve(ADMIN_FRONTEND_ROOT, dir);
    if (!fs.existsSync(abs)) continue;
    for (const file of walk(abs)) {
      if (pattern.test(fs.readFileSync(file, "utf-8"))) {
        offenders.push(path.relative(ADMIN_FRONTEND_ROOT, file));
      }
    }
  }
  return offenders;
}

describe("ADM-5 mock symbol deletion", () => {
  it("TICKET_QUEUE, REQUEST_TICKETS, isOpenTicket, and the mock RequestTicket type are gone from lib/mock/rm-data.ts", () => {
    const src = read("lib/mock/rm-data.ts");
    expect(src).not.toMatch(/export\s+const\s+TICKET_QUEUE/);
    expect(src).not.toMatch(/export\s+const\s+REQUEST_TICKETS/);
    expect(src).not.toMatch(/isOpenTicket/);
    expect(src).not.toMatch(/export\s+type\s+RequestTicket\b/);
  });

  it("no remaining reference to TICKET_QUEUE/REQUEST_TICKETS/isOpenTicket anywhere under admin-frontend", () => {
    expect(sweep(/TICKET_QUEUE|REQUEST_TICKETS|isOpenTicket/)).toEqual([]);
  });

  it("RM_CLIENTS, CLIENT_EXTRA, SUB_CLIENTS, MODEL_SIZES, OB_MODEL_CATALOG, getMockOverlay are still exported unchanged", () => {
    const src = read("lib/mock/rm-data.ts");
    for (const sym of ["RM_CLIENTS", "CLIENT_EXTRA", "SUB_CLIENTS", "MODEL_SIZES", "OB_MODEL_CATALOG"]) {
      expect(src).toMatch(new RegExp(`export\\s+(const|type)\\s+${sym}\\b`));
    }
    expect(src).toMatch(/export\s+function\s+getMockOverlay/);
  });
});

describe("ADM-5 / proposal Non-Goals: no model_limit authoring surface added anywhere in this layer", () => {
  it("zero occurrences of 'model_limit' anywhere under admin-frontend", () => {
    expect(sweep(/model_limit/)).toEqual([]);
  });
});
