// Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-fe.md §FE-14.
// Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: Wizard.tsx's Access step has no expiry SelectField
// (EXPIRY_OPTS lives only in LifecycleModals.tsx today, keyed by `path`, not `page_id`);
// enroll-user/page.tsx's createUser() sends overrides with a fabricated
// `exp: "30 Sep 2026"` / `soon: true` and never sends `start_date`/`address`. Every
// assertion below targets the FE-14 contract and is expected to fail (missing control,
// wrong/absent request fields) until FE-2/FE-8/FE-9/FE-14 land.
//
// AccessEditor (FE-2's own unit, tested separately) is stubbed here with a minimal
// component exposing one button per test page, calling onSet(pageId, level) directly —
// this isolates FE-14's own concern (what happens to a chosen level: the expiry control
// and the enroll request body) from FE-2's rendering/grouping, which has its own test file.
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi, beforeEach } from "vitest";

vi.mock("@/components/admin/AccessEditor", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/components/admin/AccessEditor")>()),
  AccessEditor: ({ onSet }: { onSet: (pageId: string, level: string) => void }) => (
    <div>
      <button type="button" onClick={() => onSet("pc.model-management", "EDIT")}>Set pc.model-management EDIT</button>
      <button type="button" onClick={() => onSet("rm.client-info", "VIEW")}>Set rm.client-info VIEW</button>
    </div>
  ),
}));

vi.mock("@/lib/admin/catalog", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/lib/admin/catalog")>()),
  LEVEL_LABEL: { NONE: "None", VIEW: "View", EDIT: "Edit" },
  PAGE_BY_ID: {
    "pc.model-management": { page_id: "pc.model-management", label: "Model Management", path: "/pc/model-management", group: "System" },
    "rm.client-info": { page_id: "rm.client-info", label: "Client Information", path: "/rm/client-info", group: "Client Management" },
  },
  EXPIRY_OPTS: ["30 days", "90 days", "No expiry"],
  ROLE_CODES: ["RM", "MOBO", "PM", "PC", "COMPLIANCE", "ADMIN"],
}));

const mockUseAdminStore = vi.fn();
vi.mock("@/lib/admin/AdminStoreContext", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/lib/admin/AdminStoreContext")>()),
  useAdminStore: () => mockUseAdminStore(),
}));
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn(), warning: vi.fn() } }));

beforeEach(() => {
  document.body.innerHTML = '<div id="content-overlay-root"></div>';
  mockUseAdminStore.mockReset();
});

function baseDraft(overrides: Record<string, unknown> = {}) {
  return {
    mode: "new", first: "Sofia", last: "Petrova", email: "s.petrova@megaannum.ai",
    phone: "", start: "27 Jul 2026", addr: "", dept: "",
    role: "RM", ovr: {}, ovrExpiry: "90 days", notify: true,
    ...overrides,
  };
}

describe("FE-14 Wizard.tsx Access step — expiry select visibility", () => {
  async function renderAccessStep(ovr: Record<string, string>) {
    mockUseAdminStore.mockReturnValue({ eff: vi.fn(() => "NONE"), totalPages: 16, grantedFor: vi.fn(() => 0) });
    const { Wizard } = await import("@/components/admin/enroll/Wizard");
    return render(
      <Wizard
        draft={baseDraft({ ovr }) as never} step={2} setStep={vi.fn()} patchDraft={vi.fn()}
        openGroups={[]} onToggleGroup={vi.fn()} onLeave={vi.fn()} onSubmit={vi.fn()}
      />,
    );
  }

  it("negative: with no overrides, the expiry select is not rendered", async () => {
    await renderAccessStep({});
    expect(screen.queryByText(/overrides expire/i)).not.toBeInTheDocument();
    expect(screen.getByText(/no exceptions/i)).toBeInTheDocument();
  });

  it("positive: with at least one override, the expiry select renders", async () => {
    await renderAccessStep({ "pc.model-management": "EDIT" });
    expect(screen.getByText(/overrides expire/i)).toBeInTheDocument();
  });
});

describe("FE-14 enroll-user/page.tsx createUser — the enroll request body", () => {
  function mountEnrollWizard(enroll = vi.fn(async () => ({ firebase_uid: "u9", notified: true, generated_password: "sup3r-secret", override_count: 0 }))) {
    mockUseAdminStore.mockReturnValue({
      staff: [], eff: vi.fn(() => "NONE"), totalPages: 16, grantedFor: vi.fn(() => 0),
      enroll, updateStaff: vi.fn(async () => true),
    });
    return enroll;
  }

  async function fillThroughToSubmit(enroll: ReturnType<typeof vi.fn>, pickOverride: boolean) {
    const { default: EnrollUserPage } = await import("@/app/(roles)/admin/enroll-user/page");
    render(<EnrollUserPage />);
    fireEvent.click(screen.getByRole("button", { name: /^enroll user$/i }));

    fireEvent.change(screen.getByPlaceholderText("Sofia"), { target: { value: "Sofia" } });
    fireEvent.change(screen.getByPlaceholderText("Petrova"), { target: { value: "Petrova" } });
    fireEvent.change(screen.getByPlaceholderText("s.petrova@megaannum.ai"), {
      target: { value: "s.petrova@megaannum.ai" },
    });
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));

    fireEvent.click(screen.getByText("RM"));
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));

    if (pickOverride) {
      fireEvent.click(screen.getByText("Set pc.model-management EDIT"));
      fireEvent.click(screen.getByText("Set rm.client-info VIEW"));
    }
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));

    fireEvent.click(screen.getByRole("button", { name: /create account/i }));
    void enroll;
  }

  it("positive: with two changed levels, the enroll body carries two overrides entries with the chosen expiry and the fixed reason; start_date/address are sent", async () => {
    const enroll = mountEnrollWizard();
    await fillThroughToSubmit(enroll, true);
    expect(enroll).toHaveBeenCalledTimes(1);
    const body = enroll.mock.calls[0][0];
    expect(body.overrides).toHaveLength(2);
    expect(body.overrides).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ page_id: "pc.model-management", level: "EDIT", reason: "Set during enrolment" }),
        expect.objectContaining({ page_id: "rm.client-info", level: "VIEW", reason: "Set during enrolment" }),
      ]),
    );
    expect(body.overrides.every((o: { expires_at: string | null }) => o.expires_at !== null)).toBe(true);
    expect(body).toHaveProperty("start_date");
    expect(body).toHaveProperty("address");
    expect(body.notify).toBe(true);
  });

  it("negative: 'No expiry' maps to expires_at: null", async () => {
    const enroll = mountEnrollWizard();
    const { default: EnrollUserPage } = await import("@/app/(roles)/admin/enroll-user/page");
    render(<EnrollUserPage />);
    fireEvent.click(screen.getByRole("button", { name: /^enroll user$/i }));
    fireEvent.change(screen.getByPlaceholderText("Sofia"), { target: { value: "Sofia" } });
    fireEvent.change(screen.getByPlaceholderText("Petrova"), { target: { value: "Petrova" } });
    fireEvent.change(screen.getByPlaceholderText("s.petrova@megaannum.ai"), { target: { value: "s.petrova@megaannum.ai" } });
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));
    fireEvent.click(screen.getByText("RM"));
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));
    fireEvent.click(screen.getByText("Set pc.model-management EDIT"));
    fireEvent.click(screen.getByText(/overrides expire/i).closest("span")!.querySelector("button")!);
    // Pick "No expiry" from the now-open dropdown.
    fireEvent.click(screen.getByText("No expiry"));
    fireEvent.click(screen.getByRole("button", { name: /^next$/i }));
    fireEvent.click(screen.getByRole("button", { name: /create account/i }));

    const body = enroll.mock.calls[0][0];
    expect(body.overrides[0].expires_at).toBeNull();
  });

  it("negative: no changed level yields no overrides entries (undefined or empty array)", async () => {
    const enroll = mountEnrollWizard();
    await fillThroughToSubmit(enroll, false);
    const body = enroll.mock.calls[0][0];
    expect(body.overrides ?? []).toEqual([]);
  });

  it("invariant: one request per enrollment regardless of override count", async () => {
    const enroll = mountEnrollWizard();
    await fillThroughToSubmit(enroll, true);
    expect(enroll).toHaveBeenCalledTimes(1);
  });

  it("invariant: the reason string is identical across entries and matches the step's own notice copy", async () => {
    const enroll = mountEnrollWizard();
    await fillThroughToSubmit(enroll, true);
    const body = enroll.mock.calls[0][0];
    const reasons = new Set(body.overrides.map((o: { reason: string }) => o.reason));
    expect(reasons.size).toBe(1);
    expect([...reasons][0]).toBe("Set during enrolment");
  });
});
