// Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-fe.md §FE-11.
// Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: Wizard.tsx's Credentials step still renders a
// "Temporary password" TextField (with regenerate/copy) and a "Password expires"
// SelectField, both backed by `EnrollDraft.pw`/`.expiry` and `lib/admin/password.ts`'s
// `genPassword()`. That file has not been deleted, and `blankDraft()` in
// enroll-user/page.tsx still produces `pw`/`expiry`. Every assertion below is expected
// to fail (the password field is present, `pw`/`expiry` exist) until FE-8/FE-11 land.
import fs from "node:fs";
import path from "node:path";
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

const mockUseAdminStore = vi.fn();
vi.mock("@/lib/admin/AdminStoreContext", () => ({
  useAdminStore: () => mockUseAdminStore(),
}));

function baseDraft(overrides: Record<string, unknown> = {}) {
  return {
    mode: "new", first: "Sofia", last: "Petrova", email: "s.petrova@megaannum.ai",
    phone: "", start: "27 Jul 2026", addr: "", dept: "",
    role: "RM", ovr: {}, ovrExpiry: "90 days", notify: true,
    ...overrides,
  };
}

async function renderWizard(draft: ReturnType<typeof baseDraft>, step: number) {
  mockUseAdminStore.mockReturnValue({
    eff: vi.fn(() => "NONE"),
    totalPages: 16,
    grantedFor: vi.fn(() => 0),
  });
  const { Wizard } = await import("@/components/admin/enroll/Wizard");
  return render(
    <Wizard
      draft={draft as never}
      step={step}
      setStep={vi.fn()}
      patchDraft={vi.fn()}
      openGroups={[]}
      onToggleGroup={vi.fn()}
      onLeave={vi.fn()}
      onSubmit={vi.fn()}
    />,
  );
}

describe("FE-11 Wizard.tsx Credentials step", () => {
  it("positive: renders the account-ready-notice checkbox and the no-second-approver notice", async () => {
    await renderWizard(baseDraft(), 3); // new-mode: identity,role,access,creds
    expect(screen.getByText(/email an account-ready notice to/i)).toBeInTheDocument();
    expect(screen.getByText(/creates the account immediately/i)).toBeInTheDocument();
  });

  it("positive: the step's own copy describes the generated-password flow, not the old link flow", async () => {
    await renderWizard(baseDraft(), 3);
    expect(screen.getByText(/a password is generated and shown to you/i)).toBeInTheDocument();
    expect(screen.queryByText(/sets their own password from a link/i)).not.toBeInTheDocument();
  });

  it("positive: edit mode has no Credentials step — resending is a row action instead", async () => {
    await renderWizard(baseDraft({ mode: "edit", orig: "u1" }), 1); // edit-mode: identity,role only
    expect(screen.queryByText("Credentials")).not.toBeInTheDocument();
  });

  it("negative: renders no password input, no regenerate/copy button, and no expiry select", async () => {
    await renderWizard(baseDraft(), 3);
    expect(screen.queryByText(/temporary password/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/password expires/i)).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /generate a new one/i })).not.toBeInTheDocument();
  });

  it("negative: a blank draft has no pw or expiry property", () => {
    const blank = baseDraft();
    expect(blank).not.toHaveProperty("pw");
    expect(blank).not.toHaveProperty("expiry");
  });

  describe("invariants", () => {
    it("no module in the codebase imports lib/admin/password", () => {
      const root = path.resolve(__dirname, "../../../..");
      const files = [
        "components/admin/enroll/Wizard.tsx",
        "components/admin/enroll/LifecycleModals.tsx",
        "app/(roles)/admin/enroll-user/page.tsx",
      ];
      for (const f of files) {
        const text = fs.readFileSync(path.join(root, f), "utf8");
        expect(text, `${f} must not import lib/admin/password`).not.toMatch(/admin\/password/);
      }
    });

    it("lib/admin/password.ts no longer exists", () => {
      const root = path.resolve(__dirname, "../../../..");
      expect(fs.existsSync(path.join(root, "lib/admin/password.ts"))).toBe(false);
    });
  });
});
