// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-4.
// Regenerate: /test-gen standard.
//
// FE-3 (proposal 020) note: this file originally also covered
// mapDtoToReconciliationFlow (from the never-landed lib/mobo/reconciliation-flow.ts /
// flow-types.ts, spec-ahead for the 012 doc's literal FE-4 contract) — deleted here,
// no source file for it exists. The FE-10 mapTradeRecordToReconTrade coverage below
// is real and stays.
import { describe, expect, it } from "vitest";
import { mapTradeRecordToReconTrade } from "@/lib/mobo/reconciliation";
import type { TradeRecordRowDTO } from "@/lib/mobo/types";

// New for FE-10 (proposal 020): mapTradeRecordToReconTrade, added alongside
// the existing mapOrdersToReconTrade in lib/mobo/reconciliation.ts as part of
// rewiring recon-overview onto GET /api/mobo/trade-records.
const SAMPLE_ROW: TradeRecordRowDTO = {
  sys: "CRM",
  ref: "401180022",
  tradeId: "TRD-88142",
  tradeDate: "03 Jun 2026",
  mkt: "NYSE / NASDAQ",
  stock: "AAPL",
  price: "$187.40",
  qty: "12,000",
  txnType: "Buy",
  time: "09:31:02",
  status: "Confirmed",
  isFirst: true,
};

describe("FE-10 mapTradeRecordToReconTrade", () => {
  it("maps a trade-records row into a ReconTrade with both legs ok, no breakType, and empty fields", () => {
    const trade = mapTradeRecordToReconTrade(SAMPLE_ROW);
    expect(trade.id).toBe(SAMPLE_ROW.tradeId);
    expect(trade.inst).toBe(SAMPLE_ROW.stock);
    expect(trade.ti).toEqual({ state: "ok", ls: null, rs: null, fields: [] });
    expect(trade.ic).toEqual({ state: "ok", ls: null, rs: null, fields: [] });
    expect(trade.ti.breakType).toBeUndefined();
    expect(trade.ic.breakType).toBeUndefined();
  });

  it("carries the row's ref as both the ib and crm identifiers (single CRM source)", () => {
    const trade = mapTradeRecordToReconTrade(SAMPLE_ROW);
    expect(trade.ib).toBe(SAMPLE_ROW.ref);
    expect(trade.crm).toBe(SAMPLE_ROW.ref);
    expect(trade.trader).toBeNull();
  });
});
