// Generated by test-gen (standard) from docs/implementations/012-trade-recon-integration-fe.md §FE-4.
// Regenerate: /test-gen standard.
//
// Orchestrator note (012-fe run): the impl doc's literal FE-4 contract deletes
// RcScenarioKey from flow-types.ts, but lib/mock/mobo-flow-data.ts (deleted only
// in FE-6) still imports it, and tsconfig.json's `include: ["**/*.ts", ...]`
// means `tsc --noEmit` type-checks that file regardless of who imports it —
// removing the export in FE-4 would red the W1 gate until FE-6 lands. This run
// resequenced the deletion to land in FE-6 (same commit as the mock-file
// deletion) instead. The RcScenarioKey-removal invariant is asserted in the
// FE-6 test file, not here.
import { describe, expect, it } from "vitest";
import { mapDtoToReconciliationFlow } from "@/lib/mobo/reconciliation-flow";
import type { ReconciliationFlowViewDTO } from "@/lib/mobo/flow-types";

const MATCHED_DTO: ReconciliationFlowViewDTO = {
  settleDay: "03 Jun 2026",
  orders: [
    {
      id: "o1", m: "mA", inst: "AAPL US", cat: "Equity", side: "Buy",
      qty: "12,000", px: "$187.40", not: "$2.25M", notVal: 2_250_000,
      ref: "TRD-88142", ib: "IB-40118", st: "ok",
      execs: [{ id: "x1", qty: "12,000", px: "$187.40", t: "09:31:02", st: "ok" }],
    },
  ],
  allocs: [
    { cid: "cB", client: "Strathmore Fund", st: "ok", total: "$1.20M", totalVal: 1_200_000,
      models: [{ m: "mA", units: 5, amt: "$1.20M", amtVal: 1_200_000, st: "ok" }] },
  ],
  ports: [
    { cid: "cB", client: "Strathmore Fund", st: "ok", pre: "$22.10M", post: "$23.30M", chg: "+$1.20M", pct: "+5.4%",
      inTrade: 17_475_000, cash: 5_825_000, total: 23_300_000 },
  ],
  algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
  counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
};

// MSFT-partial-fill scenario: order o2 broke against IB's confirmed fill.
const MSFT_PARTIAL_FILL_DTO: ReconciliationFlowViewDTO = {
  settleDay: "03 Jun 2026",
  orders: [
    {
      id: "o2", m: "mA", inst: "MSFT US", cat: "Equity", side: "Sell",
      qty: "8,000", px: "$410.20", not: "$2.67M", notVal: 2_666_230,
      ref: "TRD-88150", ib: "IB-40126", st: "brk",
      brk: "$3.28M Ordered vs $2.67M Confirmed by IB",
      execs: [{ id: "x1", qty: "6,500", px: "$410.19", t: "10:05:39", st: "brk" }],
    },
  ],
  allocs: [
    { cid: "cB", client: "Strathmore Fund", st: "brk", total: "$1.20M", totalVal: 1_200_000,
      models: [{ m: "mA", units: 5, amt: "$1.20M", amtVal: 1_200_000, st: "brk", note: "Expected $1.48M from AlgoTrade" }] },
  ],
  ports: [
    { cid: "cB", client: "Strathmore Fund", st: "ok", pre: "$22.10M", post: "$23.30M", chg: "+$1.20M", pct: "+5.4%",
      inTrade: 17_475_000, cash: 5_825_000, total: 23_300_000 },
  ],
  algoTotal: "$2.67M", ibTotal: "$2.67M", crmTotal: "$2.67M",
  counts: { algIbBrk: 1, ibCrmBrk: 1, algCrmBrk: 0, totalBrk: 2 },
};

describe("FE-4 mapDtoToReconciliationFlow", () => {
  it("is a faithful identity mapping for the matched (all-ok) fixture", () => {
    expect(mapDtoToReconciliationFlow(MATCHED_DTO)).toEqual(MATCHED_DTO);
  });

  it("is a faithful identity mapping for the MSFT-partial-fill (breaks) fixture", () => {
    expect(mapDtoToReconciliationFlow(MSFT_PARTIAL_FILL_DTO)).toEqual(MSFT_PARTIAL_FILL_DTO);
  });

  it("passes counts through untouched — no re-derivation from filtered orders/allocs/ports", () => {
    const view = mapDtoToReconciliationFlow(MSFT_PARTIAL_FILL_DTO);
    expect(view.counts).toBe(MSFT_PARTIAL_FILL_DTO.counts);
  });

  it("is deterministic — calling twice on the same DTO yields equal output", () => {
    expect(mapDtoToReconciliationFlow(MATCHED_DTO)).toEqual(mapDtoToReconciliationFlow(MATCHED_DTO));
  });
});
