// Generated by test-gen (standard) from docs/implementations/015-eod-exception-report-fe.md §FE-4.
// Regenerate: /test-gen standard.
// FE-4 is type-level only per impl doc §8.3 ("Negative: n/a") — the real gate
// is `tsc --noEmit`; these tests assert the runtime shape/enum surface only.
import { describe, expect, it } from "vitest";
import type { EodOutcome, EodReportView, EodReportViewDTO, EodStatus } from "@/lib/mobo/eod-types";
import type { RcAlloc, RcOrder, RcPort } from "@/lib/mobo/flow-types";

const ORDER: RcOrder = {
  id: "o1", m: "mA", inst: "AAPL US", cat: "Equity", side: "Buy",
  qty: "12,000", px: "$187.40", not: "$2.25M", notVal: 2_250_000, multiplier: 1,
  ref: "TRD-88142", ib: "IB-40118", st: "ok",
  execs: [{ id: "x1", qty: "12,000", px: "$187.40", t: "09:31:02", st: "ok" }],
};

const ALLOC: RcAlloc = {
  cid: "cB", client: "Strathmore Fund", st: "ok", total: "$1.20M", totalVal: 1_200_000,
  models: [{ m: "mA", units: 5, amt: "$1.20M", amtVal: 1_200_000, st: "ok" }],
};

const PORT: RcPort = {
  cid: "cB", client: "Strathmore Fund", st: "ok", pre: "$22.10M", post: "$23.30M",
  chg: "+$1.20M", pct: "+5.4%", inTrade: 17_475_000, cash: 5_825_000, total: 23_300_000,
};

function buildView(overrides: Partial<EodReportView> = {}): EodReportView {
  return {
    settleDay: "Tue 03 Jun 2026",
    tradeDate: "2026-06-03",
    orders: [ORDER],
    allocs: [ALLOC],
    ports: [PORT],
    algoTotal: "$2.25M", ibTotal: "$2.25M", crmTotal: "$2.25M",
    counts: { algIbBrk: 0, ibCrmBrk: 0, algCrmBrk: 0, totalBrk: 0 },
    status: "OPEN",
    signedOffBy: null,
    signedOffAt: null,
    generated: null,
    orderCount: 1,
    executionCount: 1,
    notionalTraded: "$2.25M",
    breakTotal: 0,
    outcome: "CLEAR",
    canSignOff: true,
    exportReady: false,
    ...overrides,
  };
}

describe("FE-4 EodReportView / EodReportViewDTO", () => {
  it("a fully-populated view structurally matches every §7 EodReportViewOut field, and DTO is the same shape", () => {
    const view = buildView();
    const wireDto: EodReportViewDTO = view; // type-level: DTO alias accepts View verbatim
    expect(wireDto).toEqual(view);
  });

  it("embeds RcOrder/RcAlloc/RcPort from flow-types.ts unchanged — no duplicate row-shape type", () => {
    const view = buildView();
    expect(view.orders[0]).toEqual(ORDER);
    expect(view.allocs[0]).toEqual(ALLOC);
    expect(view.ports[0]).toEqual(PORT);
  });

  it("status is constrained to the frozen EodStatus enum values", () => {
    const statuses: EodStatus[] = ["OPEN", "SIGNED"];
    statuses.forEach((status) => expect(buildView({ status }).status).toBe(status));
  });

  it("outcome is constrained to the frozen EodOutcome enum values", () => {
    const outcomes: EodOutcome[] = ["CLEAR", "EXCEPTIONS"];
    outcomes.forEach((outcome) => expect(buildView({ outcome }).outcome).toBe(outcome));
  });

  it("signedOffBy/signedOffAt/generated accept null (unsigned day)", () => {
    const view = buildView({ signedOffBy: null, signedOffAt: null, generated: null });
    expect(view.signedOffBy).toBeNull();
    expect(view.signedOffAt).toBeNull();
    expect(view.generated).toBeNull();
  });

  it("signedOffBy/signedOffAt/generated accept populated strings (signed day)", () => {
    const view = buildView({
      status: "SIGNED", signedOffBy: "jane@megaannum.ai", signedOffAt: "2026-06-03T18:00:00Z",
      generated: "2026-06-03T18:00:05Z", exportReady: true,
    });
    expect(view.signedOffBy).toBe("jane@megaannum.ai");
    expect(view.exportReady).toBe(true);
  });
});
