// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-1.
// Regenerate: /test-gen standard.
import { describe, expect, it } from "vitest";
import { mapDtoToRequestTicket, type RmTicketDTO, type TicketKind, type TicketStatus } from "@/lib/rm/tickets";
import type { ChipTone } from "@/components/ui/Chip";

function dto(overrides: Partial<RmTicketDTO> = {}): RmTicketDTO {
  return {
    ref: "REQ-1001",
    client_id: "client-1",
    client: "Ardent Capital",
    contact: "Marcus Lindqvist",
    email: "m.lindqvist@ardentcap.com",
    account: "IB-4471",
    model: "Global Balanced",
    kind: "allotment",
    currency: "USD",
    amount: 180000,
    multiplier: 2,
    subject: null,
    message: "Please allot a further USD 180,000.",
    status: "new",
    created_at: "2026-06-06T00:00:00Z",
    responded_by: null,
    responded_at: null,
    response_note: null,
    ...overrides,
  };
}

const EXPECTED_TONE: Record<TicketStatus, ChipTone> = {
  new: "warm", in_progress: "review", resolved: "neutral", declined: "overdue",
};

describe("ADM-1 mapDtoToRequestTicket — status -> ChipTone (invariant: every TicketStatus maps to exactly one tone matching the mock data's prior encoding)", () => {
  (Object.keys(EXPECTED_TONE) as TicketStatus[]).forEach((status) => {
    it(`maps status="${status}" to tone="${EXPECTED_TONE[status]}"`, () => {
      const ticket = mapDtoToRequestTicket(dto({ status }));
      expect(ticket.tone).toBe(EXPECTED_TONE[status]);
    });
  });
});

describe("ADM-1 mapDtoToRequestTicket — kind -> type label", () => {
  const CASES: Array<[TicketKind, string]> = [
    ["allotment", "Allotment"],
    ["redemption", "Redemption"],
    ["other", "Other"],
  ];
  CASES.forEach(([kind, expected]) => {
    it(`kind="${kind}" -> type="${expected}"`, () => {
      const ticket = mapDtoToRequestTicket(dto({ kind, amount: null, multiplier: null }));
      expect(ticket.type).toBe(expected);
    });
  });
});

describe("ADM-1 mapDtoToRequestTicket — null rendering (global invariant §3.1)", () => {
  it("a null account renders the existing '—' placeholder (RequestTicketDetail/ActOnTradePanel render ticket.account with no fallback of their own)", () => {
    const ticket = mapDtoToRequestTicket(dto({ account: null }));
    expect(ticket.account).toBe("—");
  });

  it("a null model is preserved as absent (undefined/null) so the component's own `ticket.model ?? \"—\"` fallback still applies — the mapper must not pre-empt it with a different placeholder", () => {
    const ticket = mapDtoToRequestTicket(dto({ model: null }));
    expect(ticket.model == null).toBe(true);
  });
});

describe("ADM-1 mapDtoToRequestTicket — money passthrough for an Other-kind ticket (amount/multiplier both null)", () => {
  it("renders the existing '—' placeholders for ccy/cash/mult, not 'null' or 'NaN'", () => {
    const ticket = mapDtoToRequestTicket(dto({
      kind: "other", amount: null, multiplier: null, subject: "Update authorised signatory",
    }));
    expect(ticket.cash).not.toMatch(/null|NaN|undefined/i);
    expect(ticket.mult).not.toMatch(/null|NaN|undefined/i);
  });
});

describe("ADM-1 mapDtoToRequestTicket — ref/client passthrough", () => {
  it("carries ref, client, and message through verbatim", () => {
    const ticket = mapDtoToRequestTicket(dto({ ref: "REQ-9999", client: "Vela Holdings", message: "hello" }));
    expect(ticket.ref).toBe("REQ-9999");
    expect(ticket.client).toBe("Vela Holdings");
    expect(ticket.message).toBe("hello");
  });
});
