// Generated by test-gen (standard) from docs/implementations/017-transaction-details-wiring-fe.md §FE-3. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-3 appends dto.has_transaction_detail as
// a 12th TxnRow element in allotmentToTxnRow — the field doesn't exist on
// AllotRdmptDTO / isn't appended yet, so the 12th-element assertions below
// fail as the correct pre-implementation signal until FE-1 (DTO widening) and
// FE-3 (row appending) both land.
import { describe, expect, it } from "vitest";
import { allotmentToTxnRow } from "@/lib/rm/subscriptions";
import type { AllotRdmptDTO } from "@/lib/onboarding/types";

const BASE: AllotRdmptDTO = {
  id: "a1", reference: "REF-1", model_id: "m1", model_name: "Model A", units: 2, amount: 200_000,
  kind: "allotment", status: "pending", note: null, agg_before: 0, agg_after: 2,
  expected_cash_in: "2026-08-01", rm: "Jane", created_at: "2026-07-22T00:00:00Z", acknowledged_at: null,
  emergent: false, expected_cash_out: null, decided_by: null, decided_at: null, reject_reason: null,
  has_transaction_detail: false,
};

describe("FE-3 allotmentToTxnRow appends has_transaction_detail as the 12th element", () => {
  it("has_transaction_detail: true -> 12th element is true", () => {
    const row = allotmentToTxnRow({ ...BASE, has_transaction_detail: true }, "IB-4471");
    expect(row).toHaveLength(12);
    expect(row[11]).toBe(true);
  });

  it("has_transaction_detail: false -> 12th element is false", () => {
    const row = allotmentToTxnRow({ ...BASE, has_transaction_detail: false }, "IB-4471");
    expect(row).toHaveLength(12);
    expect(row[11]).toBe(false);
  });

  it("the first 11 elements are unaffected by has_transaction_detail — only appends, never reorders", () => {
    const rowFiled = allotmentToTxnRow({ ...BASE, has_transaction_detail: true }, "IB-4471");
    const rowUnfiled = allotmentToTxnRow({ ...BASE, has_transaction_detail: false }, "IB-4471");
    expect(rowFiled.slice(0, 11)).toEqual(rowUnfiled.slice(0, 11));
    expect(rowFiled[0]).toBe("Allotment");
    expect(rowFiled[9]).toBe("pending");
    expect(rowFiled[10]).toBe("a1");
  });
});
