// Generated by test-gen (standard) from docs/implementations/016-allotment-redemption-integration-fe.md §FE-4. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-4 adds statusToChip to
// lib/rm/subscriptions.ts and widens TxnRow to a 10-tuple — statusToChip
// does not exist and allotmentToTxnRow/netRow return 9-tuples until the
// feature agent lands FE-4, so the 10th-element assertions below fail
// (undefined, not the expected status) as the correct pre-implementation
// signal.
import { describe, expect, it } from "vitest";
import { statusToChip, allotmentToTxnRow } from "@/lib/rm/subscriptions";
import type { AllotRdmpStatus } from "@/lib/onboarding/types";
import type { AllotRdmptDTO, ClientSubscriptionsDTO } from "@/lib/onboarding/types";

function makeAllot(overrides: Partial<AllotRdmptDTO> = {}): AllotRdmptDTO {
  return {
    id: "a-1", reference: "REF-1", model_id: "m-1", model_name: "Balanced", units: 2, amount: 200_000,
    kind: "allotment", status: "pending", note: null,
    agg_before: 0, agg_after: 200_000, expected_cash_in: "2026-08-01T00:00:00Z",
    rm: "Alice", created_at: "2026-07-22T00:00:00Z", acknowledged_at: null,
    ...overrides,
  };
}

describe("FE-4 statusToChip", () => {
  it.each([
    ["pending", "active", "Confirmed"],
    ["acknowledged", "active", "Confirmed"],
    ["awaiting_pc", "pending", "Awaiting Approval"],
    ["awaiting_co", "pending", "Awaiting Approval"],
    ["approved", "active", "Approved"],
    ["rejected", "overdue", "Rejected"],
  ] as const)("statusToChip(%s) -> { tone: %s, label: %s }", (status, tone, label) => {
    expect(statusToChip(status as AllotRdmpStatus)).toEqual({ tone, label });
  });
});

describe("FE-4 allotmentToTxnRow carries status as the 10th element", () => {
  it.each([
    "pending", "acknowledged", "awaiting_pc", "awaiting_co", "approved", "rejected",
  ] as const)("a DTO with status=%s produces a TxnRow whose 10th element is that status", (status) => {
    const row = allotmentToTxnRow(makeAllot({ status }), "IB-4471");
    expect(row[9]).toBe(status);
  });

  it("the row still has its original 9 fields unchanged (append, not rewrite)", () => {
    const row = allotmentToTxnRow(makeAllot({ kind: "allotment", units: 2, amount: 200_000 }), "IB-4471");
    // 017/FE-3 appended dto.id (11th) and dto.has_transaction_detail (12th) after this
    // proposal's status element — 12 total, not 10.
    expect(row).toHaveLength(12);
    expect(row[0]).toBe("Allotment");
    expect(row[2]).toBe("IB-4471");
  });
});

describe("FE-4 netRow's 10th element is always '' (no chip on the Net row)", () => {
  it("a client's Net row (via mapSubscriptionsToSubClients) has 10th element ''", async () => {
    const { mapSubscriptionsToSubClients } = await import("@/lib/rm/subscriptions");
    const dto: ClientSubscriptionsDTO = {
      client_id: "c-1", client_name: "Ardent Capital",
      subscriptions: [{ model_id: "m-1", model_name: "Balanced", units: 2, mgmt_fee: 0.015, incentive_fee: 0.2, ib_account: "IB-4471", amount: 200_000 }],
    };
    const [client] = mapSubscriptionsToSubClients([dto], {});
    const netRow = client.models[0].rows[client.models[0].rows.length - 1];
    expect(netRow[0]).toBe("Net");
    expect(netRow[9]).toBe("");
  });
});
