// Generated by test-gen (thorough) from docs/implementations/014-onboarding-follow-up-fixes-fe.md §FE-6. Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: FE-6 CREATES two new files
// (hooks/api/useSubscriptions.ts, lib/rm/subscriptions.ts) that do not exist
// on disk yet. Importing them below is expected to fail this file's
// collection entirely (a module-resolution error, not per-test assertion
// failures) until the feature agent creates those files — this is the
// correct/expected pre-implementation signal for a unit whose whole job is
// standing up net-new modules, distinct from a fixture-wiring bug.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, renderHook, screen, waitFor } from "@testing-library/react";
import fs from "node:fs";
import path from "node:path";

vi.mock("@/app/(roles)/rm/model-subscription/actions", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/app/(roles)/rm/model-subscription/actions")>()),
  fetchSubscriptions: vi.fn(),
  fetchClientAllotments: vi.fn(),
}));

import * as actions from "@/app/(roles)/rm/model-subscription/actions";
import {
  initialsFromName,
  allotmentToTxnRow,
  mapSubscriptionsToSubClients,
} from "@/lib/rm/subscriptions";
import { useSubscriptions } from "@/hooks/api/useSubscriptions";
import type { AllotRdmptDTO, ClientSubscriptionsDTO } from "@/lib/onboarding/types";
import { SubscriptionFormModal } from "@/components/rm/SubscriptionFormModal";

function makeSub(overrides: Partial<ClientSubscriptionsDTO["subscriptions"][number]> = {}): ClientSubscriptionsDTO["subscriptions"][number] {
  return {
    model_id: "m-1", model_name: "Balanced", units: 2,
    mgmt_fee: 0.015, incentive_fee: 0.2, client_ib: "IB-4471", amount: 200_000,
    ...overrides,
  };
}

function makeClientDto(overrides: Partial<ClientSubscriptionsDTO> = {}): ClientSubscriptionsDTO {
  return { client_id: "c-1", client_name: "Ardent Capital Partners", subscriptions: [makeSub()], ...overrides };
}

function makeAllot(overrides: Partial<AllotRdmptDTO> = {}): AllotRdmptDTO {
  return {
    id: "a-1", reference: "REF-1", model_id: "m-1", model_name: "Balanced", units: 2, amount: 200_000,
    kind: "allotment", status: "acknowledged", note: null,
    agg_before: 0, agg_after: 200_000, expected_cash_in: "2026-06-01T00:00:00Z",
    rm: "Alice", created_at: "2026-05-28T00:00:00Z", acknowledged_at: "2026-05-30T00:00:00Z",
    ...overrides,
  };
}

beforeEach(() => vi.clearAllMocks());

describe("FE-6 initialsFromName", () => {
  it("'Ardent Capital Partners' -> 'AC' (first letter of the first two words)", () => {
    expect(initialsFromName("Ardent Capital Partners")).toBe("AC");
  });
  it("a single-word name -> its single uppercase letter, not a crash", () => {
    expect(() => initialsFromName("Solo")).not.toThrow();
    expect(initialsFromName("Solo")).toBe("S");
  });
  it("an empty/blank name -> '—', not a crash", () => {
    expect(initialsFromName("   ")).toBe("—");
  });
});

describe("FE-6 allotmentToTxnRow", () => {
  it("an allotment DTO maps to the Allotment TxnRow shape (unsigned amount, positive multiplier, Expected Cash In populated)", () => {
    const row = allotmentToTxnRow(makeAllot({ kind: "allotment", units: 2, amount: 200_000 }), "IB-4471");
    expect(row[0]).toBe("Allotment");
    expect(row[2]).toBe("IB-4471");
    expect(row[3]).toBe("USD");
    expect(row[5]).toBe("2×");
    expect(row[7]).not.toBe("—");   // Expected Cash In populated
    expect(row[8]).toBe("—");       // Expected Redemption not applicable
  });

  it("a redemption DTO maps to the parenthesized/negative-multiplier form with the last two columns swapped", () => {
    const row = allotmentToTxnRow(makeAllot({ kind: "redemption", units: 1, amount: 100_000, expected_cash_in: "2026-07-01T00:00:00Z" }), "IB-4471");
    expect(row[0]).toBe("Redemption");
    expect(row[4]).toMatch(/^\(.*\)$/);
    expect(row[5]).toBe("−1×");
    expect(row[7]).toBe("—");       // Expected Cash In not applicable
    expect(row[8]).not.toBe("—");   // Expected Redemption populated
  });

  it("falls back to '—' for the IB account column when the client_ib account is null", () => {
    const row = allotmentToTxnRow(makeAllot(), null);
    expect(row[2]).toBe("—");
  });
});

describe("FE-6 mapSubscriptionsToSubClients", () => {
  it("with no allotment cache loaded yet, every model has only its Net row", () => {
    const [client] = mapSubscriptionsToSubClients([makeClientDto()], {});
    expect(client.models[0].rows).toHaveLength(1);
    expect(client.models[0].rows[0][0]).toBe("Net");
  });

  it("with a populated allotment cache, ledger rows precede the Net row, filtered by model_id", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ model_id: "m-1" }), makeSub({ model_id: "m-2", model_name: "Growth" })] });
    const ledger = {
      "c-1": [
        makeAllot({ id: "a-1", model_id: "m-1" }),
        makeAllot({ id: "a-2", model_id: "m-2" }),
      ],
    };
    const [client] = mapSubscriptionsToSubClients([dto], ledger);
    const model1 = client.models.find((m) => m.name === "Balanced")!;
    expect(model1.rows).toHaveLength(2);
    expect(model1.rows[0][0]).toBe("Allotment");
    expect(model1.rows[1][0]).toBe("Net");
  });

  it("the Net row's multiplier/notional always reflects client_subscriptions' current units/amount, never a ledger sum", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ units: 3, amount: 300_000 })] });
    const ledger = { "c-1": [makeAllot({ units: 1, amount: 100_000 }), makeAllot({ units: 1, amount: 100_000 })] };
    const [client] = mapSubscriptionsToSubClients([dto], ledger);
    const netRow = client.models[0].rows[client.models[0].rows.length - 1];
    expect(netRow[5]).toBe("3×");
  });

  it("a subscription with amount: 0 (model_size unresolved server-side) produces a Net row of '0', not NaN/crash", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ units: 2, amount: 0 })] });
    expect(() => mapSubscriptionsToSubClients([dto], {})).not.toThrow();
    const [client] = mapSubscriptionsToSubClients([dto], {});
    const netRow = client.models[0].rows[0];
    expect(netRow[4]).not.toMatch(/nan/i);
    expect(netRow[5]).toBe("2×");
  });

  it("aum sums real subscription amounts across all of a client's models", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ amount: 200_000 }), makeSub({ model_id: "m-2", amount: 100_000 })] });
    const [client] = mapSubscriptionsToSubClients([dto], {});
    expect(client.aum).toBe("$300k");
  });

  it("mgmt_fee/incentive_fee fractions format as whole/short percentages (e.g. 0.015 -> '1.5%', 0.2 -> '20%')", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ mgmt_fee: 0.015, incentive_fee: 0.2 })] });
    const [client] = mapSubscriptionsToSubClients([dto], {});
    expect(client.models[0].mgmtFee).toBe("1.5%");
    expect(client.models[0].incentiveFee).toBe("20%");
  });

  it("a fully-redeemed (units: 0) subscription row still appears in the mapped models array -- the RM must still see it to re-add it via Add Allotment", () => {
    const dto = makeClientDto({ subscriptions: [makeSub({ units: 0, amount: 0 })] });
    const [client] = mapSubscriptionsToSubClients([dto], {});
    expect(client.models).toHaveLength(1);
    expect(client.models[0].units).toBe(0);
  });
});

describe("FE-6 useSubscriptions hook", () => {
  it("loads clients on mount from GET /rm/subscriptions", async () => {
    vi.mocked(actions.fetchSubscriptions).mockResolvedValue({ success: true, data: [makeClientDto()] } as never);
    const { result } = renderHook(() => useSubscriptions());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.clients).toHaveLength(1);
  });

  it("ensureAllotmentsLoaded called twice in a row for the same client before the first fetch resolves triggers exactly one network call", async () => {
    vi.mocked(actions.fetchSubscriptions).mockResolvedValue({ success: true, data: [makeClientDto()] } as never);
    let resolveFetch!: (v: unknown) => void;
    vi.mocked(actions.fetchClientAllotments).mockReturnValue(new Promise((res) => { resolveFetch = res; }) as never);
    const { result } = renderHook(() => useSubscriptions());
    await waitFor(() => expect(result.current.loading).toBe(false));

    result.current.ensureAllotmentsLoaded("c-1");
    result.current.ensureAllotmentsLoaded("c-1");
    expect(actions.fetchClientAllotments).toHaveBeenCalledTimes(1);
    resolveFetch({ success: true, data: [] });
  });
});

describe("FE-6 SubscriptionAccordion no longer imports SUB_CLIENTS (static negative-import check)", () => {
  it("the component source has no reference to SUB_CLIENTS", () => {
    const src = fs.readFileSync(
      path.resolve(__dirname, "../../../components/rm/SubscriptionAccordion.tsx"),
      "utf8",
    );
    expect(src).not.toMatch(/SUB_CLIENTS/);
  });
});

describe("FE-6 SubscriptionFormModal stays interactable (no persisting submit) — regression, this file is explicitly NOT touched by FE-6", () => {
  // @todo test-gen: a byte-identical-file check belongs at the PR/schedule
  // level per §8.3's own note, not here. This test instead exercises the
  // ACTUAL behavioral invariant ("still doesn't persist on submit") against
  // the real, unmodified component — it needs none of FE-6's new files, so
  // it is one of the few checks in this file that can run before they exist.
  beforeEach(() => {
    document.body.innerHTML = '<div id="content-overlay-root"></div>';
    vi.stubGlobal("fetch", vi.fn());
  });

  it("clicking 'Submit allotment' fires no network call and does not close the modal", () => {
    const onClose = vi.fn();
    render(
      <SubscriptionFormModal
        mode="add-allotment"
        context={{ clientName: "Ardent Capital", modelName: "Global Balanced", mgmtFee: "1.0%", incentiveFee: "10%" }}
        onClose={onClose}
      />,
    );
    fireEvent.click(screen.getByRole("button", { name: /submit allotment/i }));
    expect(fetch).not.toHaveBeenCalled();
    expect(onClose).not.toHaveBeenCalled();
  });
});
