// Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-fe.md §FE-16.
// Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: app/(auth)/login/page.tsx still renders a
// `<Link href="/register">Register (dev only) →</Link>`. This assertion is expected to
// fail until FE-16 lands.
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

vi.mock("next/navigation", async (importOriginal) => ({
    ...(await importOriginal<typeof import("next/navigation")>()),
  useRouter: () => ({ replace: vi.fn() }),
  useSearchParams: () => new URLSearchParams(),
}));

const mockUseAuth = vi.fn();
vi.mock("@/components/auth/AuthProvider", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/components/auth/AuthProvider")>()),
  useAuth: () => mockUseAuth(),
}));

mockUseAuth.mockReturnValue({
  user: null, portalUser: null, loading: false, backendSyncing: false,
  backendSyncError: null, firebaseReady: true,
  signInWithGoogle: vi.fn(), signInWithEmailPassword: vi.fn(),
});

describe("FE-16 admin-frontend login page — no register link", () => {
  it("negative: renders no link whose href is a register route", async () => {
    const { default: LoginPage } = await import("@/app/(auth)/login/page");
    render(<LoginPage />);
    const links = screen.queryAllByRole("link");
    expect(links.some((l) => l.getAttribute("href") === "/register")).toBe(false);
  });
});
