// Generated by test-gen (standard) from docs/implementations/018-client-portal-integration-admin-fe.md §ADM-2.
// Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";

const notFoundMock = vi.fn();
vi.mock("next/navigation", () => ({
  useParams: () => ({ ref: "REQ-1001" }),
  notFound: () => notFoundMock(),
}));
vi.mock("@/hooks/api/useRmTickets", () => ({ useRmTicket: vi.fn() }));
vi.mock("@/components/rm/RequestTickets", () => ({
  RequestTicketDetail: ({ ticket }: { ticket: { ref: string } }) => <div>Detail for {ticket.ref}</div>,
}));

import { useRmTicket } from "@/hooks/api/useRmTickets";
import RequestTicketDetailPage from "@/app/(roles)/rm/requests/[ref]/page";

function mockHook(overrides: Partial<ReturnType<typeof useRmTicket>>) {
  vi.mocked(useRmTicket).mockReturnValue({ data: null, loading: false, error: null, ...overrides } as never);
}

beforeEach(() => vi.clearAllMocks());

describe("ADM-2 RequestTicketDetailPage", () => {
  it("loading: renders the skeleton — never notFound or the detail before the real result resolves", () => {
    mockHook({ loading: true });
    render(<RequestTicketDetailPage />);
    expect(notFoundMock).not.toHaveBeenCalled();
    expect(screen.queryByText(/^Detail for/)).not.toBeInTheDocument();
  });

  it("resolved: renders RequestTicketDetail with the mapped ticket", () => {
    mockHook({ data: { ref: "REQ-1001" } as never, loading: false });
    render(<RequestTicketDetailPage />);
    expect(screen.getByText("Detail for REQ-1001")).toBeInTheDocument();
    expect(notFoundMock).not.toHaveBeenCalled();
  });

  it("unknown ref (data null, error null, not loading) calls notFound() — matches today's mock-find-or-notFound behavior", () => {
    mockHook({ data: null, error: null, loading: false });
    render(<RequestTicketDetailPage />);
    expect(notFoundMock).toHaveBeenCalled();
  });

  it("a non-404 error renders an error state, not notFound", () => {
    mockHook({ data: null, error: "boom", loading: false });
    render(<RequestTicketDetailPage />);
    expect(notFoundMock).not.toHaveBeenCalled();
    expect(screen.getByText(/boom/)).toBeInTheDocument();
  });
});
