// Generated by test-gen (thorough) from docs/implementations/019-admin-access-control-and-staff-enrollment-fe.md §FE-16.
// Regenerate: /test-gen thorough.
//
// NOTE on pre-implementation state: AuthProvider.tsx still exports
// `signUpWithEmailPassword` on its context value and still imports
// `createUserWithEmailAndPassword`; `lib/auth-api.ts` still exports
// `postBackendRegister` and the `/api/dev/register` 404 special-case; firebase-auth-
// errors.ts still maps `auth/email-already-in-use` to the registration copy. Every
// negative assertion below is expected to fail (the deleted symbol is still present)
// until FE-16 lands.
import { act, render, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AuthProvider, useAuth } from "@/components/auth/AuthProvider";

type FakeFirebaseUser = { getIdToken: () => Promise<string> };
type AuthStateCallback = (user: FakeFirebaseUser | null) => void | Promise<void>;

const authStateCallbacks: AuthStateCallback[] = [];
const signOutMock = vi.fn().mockResolvedValue(undefined);

vi.mock("firebase/auth", () => ({
  GoogleAuthProvider: vi.fn(),
  onAuthStateChanged: vi.fn((_auth: unknown, cb: AuthStateCallback) => {
    authStateCallbacks.push(cb);
    return () => {};
  }),
  onIdTokenChanged: vi.fn(() => () => {}),
  signInWithEmailAndPassword: vi.fn(),
  signInWithPopup: vi.fn(),
  signOut: (...args: unknown[]) => signOutMock(...args),
}));

vi.mock("@/lib/firebase", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/lib/firebase")>()),
  getFirebaseAuth: vi.fn(() => ({})),
  isFirebaseConfigured: vi.fn(() => true),
}));

vi.mock("@/lib/id-token", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/lib/id-token")>()), writeIdTokenCookie: vi.fn() }));

const postBackendLoginMock = vi.fn();
vi.mock("@/lib/auth-api", async () => {
  const actual = await vi.importActual<typeof import("@/lib/auth-api")>("@/lib/auth-api");
  return { ...actual, postBackendLogin: (...args: unknown[]) => postBackendLoginMock(...args) };
});

let ctx: unknown;
function Consumer() {
  ctx = useAuth();
  return null;
}

function renderProvider() {
  return render(
    <AuthProvider>
      <Consumer />
    </AuthProvider>,
  );
}

describe("FE-16 AuthProvider AuthContextValue", () => {
  beforeEach(() => {
    authStateCallbacks.length = 0;
    ctx = null;
    postBackendLoginMock.mockResolvedValue({ firebase_uid: "u1", email: "a@megaannum.ai", name: "A", role: "ADMIN" });
  });

  afterEach(() => vi.clearAllMocks());

  it("positive: exposes signInWithGoogle, signInWithEmailPassword, signOutUser, getIdToken, refreshPortalUser", async () => {
    await renderProvider();
    const value = ctx as Record<string, unknown>;
    expect(typeof value.signInWithGoogle).toBe("function");
    expect(typeof value.signInWithEmailPassword).toBe("function");
    expect(typeof value.signOutUser).toBe("function");
    expect(typeof value.getIdToken).toBe("function");
    expect(typeof value.refreshPortalUser).toBe("function");
  });

  it("positive: a successful auth-state change always attempts the login bind and sets portalUser", async () => {
    await renderProvider();
    await waitFor(() => expect(authStateCallbacks.length).toBe(1));
    await act(async () => {
      await authStateCallbacks[0]({ getIdToken: vi.fn().mockResolvedValue("tok") });
    });
    expect(postBackendLoginMock).toHaveBeenCalledTimes(1);
    expect((ctx as { portalUser: { role: string } | null }).portalUser?.role).toBe("ADMIN");
  });

  it("negative: the context value has no signUpWithEmailPassword key", async () => {
    await renderProvider();
    expect(ctx as Record<string, unknown>).not.toHaveProperty("signUpWithEmailPassword");
  });

  it("invariant: no module imports createUserWithEmailAndPassword", async () => {
    const mod = await import("firebase/auth");
    // The mock above deliberately omits createUserWithEmailAndPassword. If AuthProvider
    // still imports it, the import itself will already have failed to resolve the name
    // (undefined) at call time — this positive-shaped assertion documents the intended
    // absence for readers of this file; the resolution failure is what actually signals
    // it pre-FE-16 (see the file-level NOTE above).
    // Checked via "in" rather than a direct property read: current Vitest wraps a
    // factory-mocked module so that reading an unlisted property throws ("did you
    // forget to return it from vi.mock") instead of returning undefined — "in" doesn't
    // trigger that trap and still reflects the same real absence.
    expect("createUserWithEmailAndPassword" in mod).toBe(false);
  });
});

describe("FE-16 lib/auth-api.ts", () => {
  it("negative: has no postBackendRegister export", async () => {
    const mod = await import("@/lib/auth-api");
    expect("postBackendRegister" in mod).toBe(false);
  });

  it("invariant: no request is ever issued to a /api/dev/register path (syncPortalUserAfterFirebaseAuth calls login only)", async () => {
    const fetchSpy = vi.spyOn(globalThis, "fetch").mockResolvedValue({
      ok: true,
      json: async () => ({ firebase_uid: "u1", email: "a@megaannum.ai", name: "A", role: "ADMIN" }),
    } as Response);
    const { syncPortalUserAfterFirebaseAuth } = await import("@/lib/auth-api");
    await syncPortalUserAfterFirebaseAuth("tok");
    for (const call of fetchSpy.mock.calls) {
      expect(String(call[0])).not.toContain("/api/dev/register");
    }
    fetchSpy.mockRestore();
  });
});

describe("FE-16 lib/firebase-auth-errors.ts", () => {
  it("negative: auth/email-already-in-use falls through to the generic message rather than the registration copy", async () => {
    const { formatFirebaseAuthError } = await import("@/lib/firebase-auth-errors");
    const message = formatFirebaseAuthError({ code: "auth/email-already-in-use" });
    expect(message).not.toMatch(/already registered/i);
  });

  it("auth/weak-password still maps (its producer is not only registration — confirmPasswordReset raises it too)", async () => {
    const { formatFirebaseAuthError } = await import("@/lib/firebase-auth-errors");
    expect(formatFirebaseAuthError({ code: "auth/weak-password" })).toMatch(/weak/i);
  });
});
