# Generated by test-gen (standard) from docs/implementations/019-admin-access-control-and-staff-enrollment-db.md §8, DB-6/DB-7.
# Regenerate: /test-gen standard docs/implementations/019-admin-access-control-and-staff-enrollment-db.md
#
# Layer isolation: exercises alembic upgrade/downgrade only — no app.libs.*, no routes.
# DB-6 (schema) and DB-7 (seed) share exactly ONE Alembic revision (impl doc §3.2) — this
# file is the shared structural + seed migration test for that revision, mirroring
# test_migration_0026_client_portal_integration.py's precedent for a multi-unit shared
# revision.
#
# Runs against a disposable scratch schema (tests/models/conftest.py's
# `isolated_migration_db` fixture), NOT the real dev/live `portal` DB.
#
# Seam mock: the 16 PageId literals from admin-frontend/lib/pages-config.ts's PAGES keys
# (a TypeScript file, not importable from pytest), used both to bound VARCHAR(64) and as
# the universe every seeded page_id must belong to.
#
# Pre-implementation: revision 5cd1cc1948cc (0028) does not exist on this branch yet, so
# `head` is still b34f8c1a9d27 (0027) and every test below fails — that is the correct
# pre-implementation state.
#
# Run: cd api-backend && .venv/Scripts/python.exe -m pytest -q tests/models/test_migration_0028_admin_access_control.py

import glob
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import IntegrityError

from app.core.config import get_settings

API_BACKEND_DIR = Path(__file__).resolve().parents[2]
PRE_REVISION = "b34f8c1a9d27"
NEW_REVISION = "5cd1cc1948cc"
# The repo-wide alembic head has since moved past NEW_REVISION -- proposal 020's DB
# layer landed 0029/0030/0031 after this file was written (020 BE-3 mechanical-rename
# tail: pin refreshed to the actual current head, `.venv/Scripts/alembic.exe heads`).
CURRENT_HEAD = "a3f7c1d9e824"

# Seam mock: the 16 PageId literals (admin-frontend/lib/pages-config.ts PAGES keys).
PAGE_IDS = {
    "rm.client-info",
    "rm.onboarding-renewal",
    "rm.model-subscription",
    "rm.request-tickets",
    "shared.monthly-reports",
    "mobo.recon-overview",
    "mobo.trade-reconciliation",
    "mobo.post-trade-allocation",
    "mobo.commission-tracking",
    "pc.model-management",
    "pc.allocation-matrix",
    "pc.allotment-redemption",
    "compliance.overview",
    "compliance.review",
    "admin.enroll-user",
    "admin.system-config",
}
ADMIN_ROLES = {"RM", "MOBO", "PM", "PC", "COMPLIANCE", "ADMIN"}

# Expected {(page_id, role): level} matrix, transcribed cell-for-cell from impl doc §6
# DB-7's 16x6 table. Absent cell == NONE (no row). D-10/D-12/D-13/rule-2 exceptions are
# ordinary data here, not skipped assertions.
EXPECTED_MATRIX = {
    ("rm.client-info", "RM"): "edit",
    ("rm.client-info", "COMPLIANCE"): "view",
    ("rm.client-info", "ADMIN"): "edit",
    ("rm.onboarding-renewal", "RM"): "edit",
    ("rm.onboarding-renewal", "MOBO"): "view",
    ("rm.onboarding-renewal", "COMPLIANCE"): "view",
    ("rm.onboarding-renewal", "ADMIN"): "edit",
    ("rm.model-subscription", "RM"): "edit",
    ("rm.model-subscription", "MOBO"): "view",
    ("rm.model-subscription", "PC"): "view",
    ("rm.model-subscription", "COMPLIANCE"): "view",
    ("rm.model-subscription", "ADMIN"): "edit",
    ("rm.request-tickets", "RM"): "edit",
    ("rm.request-tickets", "ADMIN"): "edit",
    ("shared.monthly-reports", "RM"): "view",
    ("shared.monthly-reports", "MOBO"): "view",
    ("shared.monthly-reports", "PC"): "edit",
    ("shared.monthly-reports", "COMPLIANCE"): "view",
    ("shared.monthly-reports", "ADMIN"): "edit",
    ("mobo.recon-overview", "MOBO"): "edit",
    ("mobo.recon-overview", "PC"): "view",
    ("mobo.recon-overview", "COMPLIANCE"): "view",
    ("mobo.recon-overview", "ADMIN"): "edit",
    ("mobo.trade-reconciliation", "MOBO"): "edit",
    ("mobo.trade-reconciliation", "PC"): "view",
    ("mobo.trade-reconciliation", "COMPLIANCE"): "view",
    ("mobo.trade-reconciliation", "ADMIN"): "edit",
    ("mobo.post-trade-allocation", "MOBO"): "edit",
    ("mobo.post-trade-allocation", "PC"): "view",  # D-10
    ("mobo.post-trade-allocation", "COMPLIANCE"): "view",
    ("mobo.post-trade-allocation", "ADMIN"): "edit",
    ("mobo.commission-tracking", "MOBO"): "edit",
    ("mobo.commission-tracking", "ADMIN"): "edit",
    ("pc.model-management", "RM"): "view",
    ("pc.model-management", "MOBO"): "view",
    ("pc.model-management", "PC"): "edit",
    ("pc.model-management", "COMPLIANCE"): "view",
    ("pc.model-management", "ADMIN"): "edit",
    ("pc.allocation-matrix", "MOBO"): "view",
    ("pc.allocation-matrix", "PC"): "edit",
    ("pc.allocation-matrix", "COMPLIANCE"): "view",
    ("pc.allocation-matrix", "ADMIN"): "edit",
    ("pc.allotment-redemption", "RM"): "view",
    ("pc.allotment-redemption", "MOBO"): "view",
    ("pc.allotment-redemption", "PC"): "edit",
    ("pc.allotment-redemption", "COMPLIANCE"): "view",
    ("pc.allotment-redemption", "ADMIN"): "edit",
    ("compliance.overview", "PC"): "view",
    ("compliance.overview", "COMPLIANCE"): "edit",
    ("compliance.overview", "ADMIN"): "edit",
    ("compliance.review", "PC"): "view",
    ("compliance.review", "COMPLIANCE"): "edit",
    ("compliance.review", "ADMIN"): "edit",
    ("admin.enroll-user", "ADMIN"): "edit",
    ("admin.system-config", "ADMIN"): "edit",
}
assert len(EXPECTED_MATRIX) == 55, "fixture itself must encode exactly 55 cells"
assert sum(1 for v in EXPECTED_MATRIX.values() if v == "edit") == 30
assert sum(1 for v in EXPECTED_MATRIX.values() if v == "view") == 25


def _cfg() -> Config:
    cfg = Config(str(API_BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(API_BACKEND_DIR / "alembic"))
    return cfg


def _new_revision_file() -> str:
    matches = glob.glob(
        str(API_BACKEND_DIR / "alembic" / "versions" / "*_0028_admin_access_control.py")
    )
    assert len(matches) == 1, f"expected exactly one 0028 revision file, found {matches!r}"
    return matches[0]


def _columns(table: str) -> dict:
    engine = create_engine(get_settings().database_url)
    try:
        return {c["name"]: c for c in inspect(engine).get_columns(table)}
    finally:
        engine.dispose()


def _table_names() -> set[str]:
    engine = create_engine(get_settings().database_url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def _page_access_rows() -> list[tuple[str, str, str]]:
    engine = create_engine(get_settings().database_url)
    try:
        with engine.connect() as conn:
            return [
                tuple(r)
                for r in conn.execute(text("SELECT page_id, role, level FROM page_access"))
            ]
    finally:
        engine.dispose()


@pytest.fixture(autouse=True)
def _ensure_head_before_and_after(isolated_migration_db):
    command.upgrade(_cfg(), "head")
    yield
    command.upgrade(_cfg(), "head")


# --- Positive: DB-6 revision identity / history -----------------------------


def test_new_revision_down_revision_is_b34f8c1a9d27():
    revision_file = _new_revision_file()
    namespace: dict = {}
    exec(compile(open(revision_file).read(), revision_file, "exec"), namespace)
    assert namespace["revision"] == NEW_REVISION
    assert namespace["down_revision"] == PRE_REVISION


def test_alembic_history_shows_a_single_linear_head():
    script = ScriptDirectory.from_config(_cfg())
    assert len(script.get_heads()) == 1
    assert script.get_heads()[0] == CURRENT_HEAD


# --- Positive: DB-6 four new tables + four new columns ----------------------


def test_upgrade_head_creates_all_four_tables():
    assert {
        "page_access",
        "page_access_overrides",
        "page_access_publications",
        "admin_audit_events",
    } <= _table_names()


def test_page_access_columns_match_documented_types():
    columns = _columns("page_access")
    assert columns["page_id"]["nullable"] is False
    assert columns["role"]["nullable"] is False
    assert columns["level"]["nullable"] is False


def test_page_access_overrides_has_expected_fks_and_nullability():
    engine = create_engine(get_settings().database_url)
    try:
        insp = inspect(engine)
        fks = {fk["constrained_columns"][0]: fk["options"].get("ondelete") for fk in insp.get_foreign_keys("page_access_overrides")}
        assert fks.get("user_id") == "CASCADE"
        assert fks.get("granted_by") == "SET NULL"
    finally:
        engine.dispose()

    columns = _columns("page_access_overrides")
    assert columns["reason"]["nullable"] is False
    assert columns["expires_at"]["nullable"] is True
    assert columns["granted_by"]["nullable"] is True


def test_upgrade_head_adds_last_sign_in_at_and_admin_profile_columns():
    users_columns = _columns("users")
    assert users_columns["last_sign_in_at"]["nullable"] is True

    admin_columns = _columns("admin_profiles")
    assert admin_columns["department"]["nullable"] is True
    assert admin_columns["start_date"]["nullable"] is True
    assert admin_columns["address"]["nullable"] is True


def test_page_id_varchar_length_accommodates_every_known_page_id():
    columns = _columns("page_access")
    max_len = max(len(p) for p in PAGE_IDS)
    assert columns["page_id"]["type"].length >= max_len
    assert columns["page_id"]["type"].length == 64


# --- Positive: DB-7 the 55-row seed -----------------------------------------


def test_seed_has_exactly_55_rows():
    assert len(_page_access_rows()) == 55


def test_seed_role_counts_match_b1_matrix():
    rows = _page_access_rows()
    counts: dict[str, int] = {}
    for _, role, _ in rows:
        counts[role] = counts.get(role, 0) + 1
    assert counts == {"RM": 7, "MOBO": 10, "PC": 10, "COMPLIANCE": 12, "ADMIN": 16}
    assert "PM" not in counts


def test_seed_level_counts_match_b1_matrix():
    rows = _page_access_rows()
    counts: dict[str, int] = {}
    for _, _, level in rows:
        counts[level] = counts.get(level, 0) + 1
    assert counts == {"edit": 30, "view": 25}


def test_admin_has_sixteen_edit_rows_one_per_page():
    rows = [(p, lvl) for p, role, lvl in _page_access_rows() if role == "ADMIN"]
    assert len(rows) == 16
    assert all(lvl == "edit" for _, lvl in rows)
    assert {p for p, _ in rows} == PAGE_IDS


def test_seed_matches_expected_matrix_cell_for_cell():
    actual = {(page_id, role): level for page_id, role, level in _page_access_rows()}
    assert actual == EXPECTED_MATRIX


# --- Negative: DB-7 deliberate exceptions + integrity -----------------------


def test_pm_has_zero_rows():
    assert all(role != "PM" for _, role, _ in _page_access_rows())


def test_pc_post_trade_allocation_is_view_not_edit():
    actual = {(p, r): lvl for p, r, lvl in _page_access_rows()}
    assert actual[("mobo.post-trade-allocation", "PC")] == "view"


def test_monthly_reports_narrows_rm_and_mobo_to_view_while_pc_keeps_edit():
    actual = {(p, r): lvl for p, r, lvl in _page_access_rows()}
    assert actual[("shared.monthly-reports", "RM")] == "view"
    assert actual[("shared.monthly-reports", "MOBO")] == "view"
    assert actual[("shared.monthly-reports", "PC")] == "edit"


def test_no_seeded_page_id_falls_outside_the_sixteen_known_ids():
    seeded_ids = {p for p, _, _ in _page_access_rows()}
    assert seeded_ids <= PAGE_IDS
    # No fictional catalog path literal (e.g. "/rm/dashboard") survived the rename map.
    assert not any(p.startswith("/") for p in seeded_ids)


def test_no_seeded_role_falls_outside_admin_role_values():
    seeded_roles = {r for _, r, _ in _page_access_rows()}
    assert seeded_roles <= ADMIN_ROLES


def test_reexecuting_the_seed_raises_integrity_error_on_unique_constraint():
    engine = create_engine(get_settings().database_url)
    try:
        with engine.begin() as conn:
            with pytest.raises(IntegrityError):
                conn.execute(
                    text(
                        "INSERT INTO page_access (page_id, role, level) VALUES "
                        "('rm.client-info', 'RM', 'edit')"
                    )
                )
    finally:
        engine.dispose()


def test_downgrade_drops_all_four_tables_and_all_four_columns():
    command.downgrade(_cfg(), PRE_REVISION)

    assert not (
        {"page_access", "page_access_overrides", "page_access_publications", "admin_audit_events"}
        & _table_names()
    )

    users_columns = _columns("users").keys()
    assert "last_sign_in_at" not in users_columns

    admin_columns = _columns("admin_profiles").keys()
    assert "department" not in admin_columns
    assert "start_date" not in admin_columns
    assert "address" not in admin_columns


# --- Invariants --------------------------------------------------------------


def test_no_pre_existing_table_or_column_is_touched():
    users_columns = _columns("users")
    assert {"id", "firebase_uid", "email", "portal"} <= users_columns.keys()


def test_upgrade_downgrade_upgrade_cycle_is_idempotent_and_reseeds():
    command.downgrade(_cfg(), PRE_REVISION)
    command.upgrade(_cfg(), "head")

    assert "page_access" in _table_names()
    assert len(_page_access_rows()) == 55


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
