// Generated by test-gen (standard) from docs/implementations/014-onboarding-follow-up-fixes-fe.md §FE-4. Regenerate: /test-gen standard.
import { beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen } from "@testing-library/react";

vi.mock("next/navigation", async (importOriginal) => ({
    ...(await importOriginal<typeof import("next/navigation")>()),
  useParams: () => ({ id: "client-1" }),
  notFound: vi.fn(),
}));

// FE-4's "Files:" list only names hooks/api/useClient.ts as modified (no new
// hook file) — so useOnboardingByClient/useClientEvents are assumed to be
// added as new exports from that same existing module, per this repo's
// convention of one hooks/api/use*.ts file per domain hook (useOnboardingBoard,
// useModels, etc.). If the implementation instead creates dedicated files,
// regenerate this test against the actual paths.
vi.mock("@/hooks/api/useClient", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/hooks/api/useClient")>()),
  useClient: vi.fn(),
  useOnboardingByClient: vi.fn(),
  useClientEvents: vi.fn(),
}));
import { useClient, useOnboardingByClient, useClientEvents } from "@/hooks/api/useClient";
import { dtoToRow, type ClientListItemDTO, type ClientRow } from "@/lib/rm/clients";
import ClientDetailPage from "@/app/(roles)/rm/client-info/[id]/page";

function baseDto(overrides: Partial<ClientListItemDTO> = {}): ClientListItemDTO {
  return {
    id: "client-1", name: "Jane Doe", phone: "+1", assigned_rm: "Alice",
    address: "1 Main St", country_of_residence: "US",
    authorized_person: null, initiate_method: "Referral", ib_account: "IB-1", email: "j@x.com",
    ...overrides,
  };
}

function baseRow(overrides: Partial<ClientRow> = {}): ClientRow {
  return { ...dtoToRow(baseDto()), subscriptions: [], ...overrides };
}

function mockClient(data: ClientRow | null, overrides: Partial<ReturnType<typeof useClient>> = {}) {
  vi.mocked(useClient).mockReturnValue({ data, loading: false, error: null, notFound: false, ...overrides } as never);
}

beforeEach(() => {
  vi.clearAllMocks();
  mockClient(baseRow());
  vi.mocked(useOnboardingByClient).mockReturnValue({ data: null, loading: false, error: null } as never);
  vi.mocked(useClientEvents).mockReturnValue({ data: null, loading: false, error: null } as never);
});

describe("FE-4 dtoToRow widening (lib/rm/clients.ts)", () => {
  it("maps id_type/id_number/authorized_by_name onto idType/idNumber/authorizedByName", () => {
    const row = dtoToRow({
      ...baseDto(),
      ...({ id_type: "Passport", id_number: "A1", authorized_by_name: "Jane Compliance" } as Partial<ClientListItemDTO>),
    } as ClientListItemDTO);
    expect((row as unknown as Record<string, unknown>).idType).toBe("Passport");
    expect((row as unknown as Record<string, unknown>).idNumber).toBe("A1");
    expect((row as unknown as Record<string, unknown>).authorizedByName).toBe("Jane Compliance");
  });
});

describe("FE-4 ID Info field", () => {
  it("renders '<idType> <idNumber>' when both are present", () => {
    mockClient(baseRow({ ...({ idType: "Passport", idNumber: "A1" } as Partial<ClientRow>) }));
    render(<ClientDetailPage />);
    expect(screen.getByText("Passport A1")).toBeInTheDocument();
  });

  it("renders just the one present field when only idType is set (not 'Passport —')", () => {
    mockClient(baseRow({ ...({ idType: "Passport", idNumber: null } as Partial<ClientRow>) }));
    render(<ClientDetailPage />);
    expect(screen.getByText("Passport")).toBeInTheDocument();
    expect(screen.queryByText(/Passport\s*—/)).not.toBeInTheDocument();
  });

  it("renders '—' only when both idType and idNumber are null", () => {
    mockClient(baseRow({ ...({ idType: null, idNumber: null } as Partial<ClientRow>) }));
    render(<ClientDetailPage />);
    expect(screen.getAllByText("—").length).toBeGreaterThan(0);
  });
});

describe("FE-4 Authorized Person field", () => {
  it("renders the resolved name when present", () => {
    mockClient(baseRow({ ...({ authorizedByName: "Jane Compliance" } as Partial<ClientRow>) }));
    render(<ClientDetailPage />);
    expect(screen.getByText("Jane Compliance")).toBeInTheDocument();
  });

  it("renders '—' when authorizedByName is null (not yet approved)", () => {
    mockClient(baseRow({ ...({ authorizedByName: null } as Partial<ClientRow>) }));
    render(<ClientDetailPage />);
    expect(screen.getAllByText("—").length).toBeGreaterThan(0);
  });
});

describe("FE-4 KYC & Documents — fetched, not mocked", () => {
  it("renders the client's real documents/verified count from the onboarding DTO, not getMockOverlay", () => {
    vi.mocked(useOnboardingByClient).mockReturnValue({
      data: {
        documents: [{ doc_type: "passport", label: "Passport / ID", status: "verified" }],
        verified_count: 5, required_count: 7,
      },
      loading: false, error: null,
    } as never);
    render(<ClientDetailPage />);
    expect(screen.getByText("5 of 7 verified")).toBeInTheDocument();
  });

  it("a client with no onboarding row (404) renders an empty state, not a crash", () => {
    vi.mocked(useOnboardingByClient).mockReturnValue({ data: null, loading: false, error: null } as never);
    expect(() => render(<ClientDetailPage />)).not.toThrow();
  });
});

describe("FE-4 History — fetched, not mocked", () => {
  it("renders real client_events rows instead of getMockOverlay's history", () => {
    vi.mocked(useClientEvents).mockReturnValue({
      data: [{ id: "e1", category: "kyc", title: "Renewed passport", body: "detail", created_at: "2026-07-01T00:00:00Z" }],
      loading: false, error: null,
    } as never);
    render(<ClientDetailPage />);
    expect(screen.getByText("Renewed passport")).toBeInTheDocument();
  });
});

describe("FE-4 invariant: Account Balance card is untouched", () => {
  // FE-16 (020 refactor): lib/mock/rm-data.ts and getMockOverlay are deleted —
  // this page already computes totalPortfolioValue from real data, not the
  // mock overlay, so the invariant is just that the card still renders.
  it("still renders", () => {
    render(<ClientDetailPage />);
    expect(screen.getByText("Total Portfolio Value")).toBeInTheDocument();
  });
});
