# Generated by test-gen (standard) from
# docs/implementations/018-client-portal-integration-be.md §BE-3.
# Regenerate: /test-gen standard.
#
# Portfolio GET: total_value/change_pct/position amount derivations, and the
# DB B-3 "missing client_portfolios row never 404s" invariant.
#
# Pre-implementation note: app/libs/client_portal/{schemas,service,
# repository}.py do not exist yet -- every import below is expected to raise
# ImportError/ModuleNotFoundError at collection, not a test-gen bug.
#
# Seam mocks: none per §8.3 -- exercised against a real (in-memory) DB.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/client_portal/test_be3_portfolio.py

from __future__ import annotations

from decimal import Decimal

import pytest
from app.libs.client_portal.schemas import PortfolioDTO
from app.libs.client_portal.service import ClientPortalService

from tests.libs.client_portal.conftest import (
    make_client,
    make_model,
    make_portfolio,
    make_subscription,
)

# --- Positive: derivations match hand-computed values ------------------------------


def test_portfolio_derives_totals_and_change_pct_for_two_positions(session):
    client_user = make_client(session, name="Cathy Client")
    model_a = make_model(session, name="Zeta Model", model_size=Decimal("1000000"))
    model_b = make_model(session, name="Alpha Model", model_size=Decimal("500000"))
    make_subscription(session, client_user, model_a, multiplier=Decimal("2"))
    make_subscription(session, client_user, model_b, multiplier=Decimal("1"))
    make_portfolio(
        session,
        client_user,
        cash_deposit=Decimal("100000"),
        amount_in_trade=Decimal("2500000"),
        previous_amount_in_trade=Decimal("2000000"),
    )

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    assert isinstance(dto, PortfolioDTO)
    assert dto.cash_deposit == 100000.0
    assert dto.amount_in_trade == 2500000.0
    assert dto.total_value == 2600000.0
    assert dto.change_amount == 500000.0
    assert dto.change_pct == 0.25
    # name-sorted: "Alpha Model" before "Zeta Model"
    assert [p.model_name for p in dto.positions] == ["Alpha Model", "Zeta Model"]
    alpha = next(p for p in dto.positions if p.model_name == "Alpha Model")
    assert alpha.amount == 500000.0  # 1 * 500_000
    zeta = next(p for p in dto.positions if p.model_name == "Zeta Model")
    assert zeta.amount == 2000000.0  # 2 * 1_000_000


# --- Negative: missing client_portfolios row never 404s (DB B-3) ------------------


def test_portfolio_with_no_client_portfolios_row_returns_all_zero_no_exception(session):
    client_user = make_client(session, name="Pre014 Client")
    make_model(session, name="Solo Model")  # unsubscribed -- irrelevant to this client

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    assert dto.cash_deposit == 0.0
    assert dto.amount_in_trade == 0.0
    assert dto.previous_amount_in_trade == 0.0
    assert dto.total_value == 0.0
    assert dto.change_pct is None
    assert dto.updated_at is None
    assert dto.positions == []


# --- Invariants ---------------------------------------------------------------------


def test_change_pct_is_none_when_previous_amount_is_zero_regardless_of_current(session):
    client_user = make_client(session, name="Cathy Client")
    make_portfolio(
        session,
        client_user,
        cash_deposit=Decimal("0"),
        amount_in_trade=Decimal("999999"),
        previous_amount_in_trade=Decimal("0"),
    )

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    assert dto.change_pct is None
    assert dto.change_amount == 999999.0


def test_position_model_limit_is_raw_column_value_never_derived(session):
    client_user = make_client(session, name="Cathy Client")
    capped_model = make_model(session, name="Capped Model", model_limit=Decimal("5000000"))
    uncapped_model = make_model(session, name="Uncapped Model", model_limit=None)
    make_subscription(session, client_user, capped_model, multiplier=Decimal("1"))
    make_subscription(session, client_user, uncapped_model, multiplier=Decimal("1"))

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    capped = next(p for p in dto.positions if p.model_name == "Capped Model")
    uncapped = next(p for p in dto.positions if p.model_name == "Uncapped Model")
    assert capped.model_limit == 5000000.0
    assert uncapped.model_limit is None


def test_position_reports_the_per_client_per_model_ib_account(session):
    """The account lives in client_ib_accounts keyed by (user_id, model_id) --
    client_profiles.ib_account is gone, so it is no longer shared across a
    client's models."""
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_subscription(session, client_user, model)
    from app.models.pc import ClientIbAccount

    session.add(
        ClientIbAccount(user_id=client_user.id, model_id=model.id, ib_account="IB-777")
    )
    session.commit()

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    assert dto.positions[0].client_ib == "IB-777"


def test_positions_exclude_a_fully_redeemed_zero_unit_subscription(session):
    """A full redemption floors the subscription's multiplier at 0 rather than
    deleting the row (its client_ib_accounts binding is permanent); the 0-unit
    row must not surface as a phantom position with 0 units/amount."""
    client_user = make_client(session, name="Cathy Client")
    held_model = make_model(session, name="Held Model")
    redeemed_model = make_model(session, name="Redeemed Model")
    make_subscription(session, client_user, held_model, multiplier=Decimal("1"))
    make_subscription(session, client_user, redeemed_model, multiplier=Decimal("0"))

    svc = ClientPortalService(session)
    dto = svc.portfolio(client_user.id)

    names = {p.model_name for p in dto.positions}
    assert "Held Model" in names
    assert "Redeemed Model" not in names


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
