# Generated by test-gen (standard) from
# docs/implementations/018-client-portal-integration-be.md §BE-4.
# Regenerate: /test-gen standard.
#
# Portfolio history GET: calendar-month bucketing (D-10) -- same-month
# collapse, empty-month carry-forward, pre-window cumulative correctness,
# months=1/24 exact counts. §8.4 flags this unit as a `thorough` re-pass
# candidate; this file is the `standard`-depth pass only.
#
# Pre-implementation note: app/libs/client_portal/{schemas,service,
# repository,router}.py do not exist yet -- every import below is expected to
# raise ImportError/ModuleNotFoundError at collection, not a test-gen bug.
#
# Seam mocks: none per §8.3.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/client_portal/test_be4_portfolio_history.py

from __future__ import annotations

from datetime import datetime
from decimal import Decimal

import pytest
from app.libs.client_portal.router import router as client_portal_router
from app.libs.client_portal.schemas import HistoryPointDTO
from app.libs.client_portal.service import ClientPortalService
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.core.database import get_db
from app.libs.auth.deps import get_current_client_user
from tests.libs.client_portal.conftest import (
    make_allocation,
    make_client,
    make_model,
    make_run,
    make_run_delta,
)


def _month_token(back: int) -> str:
    """The calendar-month token `back` months before the current UTC month
    (0 == this month), same lexical YYYYMM shape the service buckets on."""
    today = datetime.utcnow().date()
    y, m = today.year, today.month
    for _ in range(back):
        m -= 1
        if m == 0:
            m, y = 12, y - 1
    return f"{y:04d}{m:02d}"


@pytest.fixture
def eight_month_fixture(session):
    """Seeds runs across 8 distinct calendar months (back=7..0, oldest first):
    - back=7,6: 2 months strictly BEFORE a months=6 window -> total_before.
    - back=5..0: the 6-month window itself.
    - back=4: deliberately NO run at all (empty-month carry-forward).
    - back=3: TWO runs in the same month, on different days (same-month
      collapse), 150 + 150.
    Every other month gets exactly one run. Delta and allocated amounts are
    kept equal for simplicity (both come from the same seeded run)."""
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")

    def _seed(back: int, amount: Decimal, day: str = "15") -> None:
        # `day` only ever varies to keep two same-month runs on DISTINCT
        # dates: post_trade_allocation_runs.trade_date is unique now (one
        # session row per trading day), so the old "two runs, same date"
        # shape is no longer representable. The service buckets on YYYYMM,
        # so the same-month collapse this fixture exercises is unchanged.
        run = make_run(session, trade_date=f"{_month_token(back)}{day}")
        make_run_delta(session, run, client_user, amount)
        make_allocation(session, run, model, client_user, allocated=amount)

    _seed(7, Decimal("100"))
    _seed(6, Decimal("200"))
    _seed(5, Decimal("300"))
    # back=4: no run at all -- carried-forward flat point.
    _seed(3, Decimal("150"))
    _seed(3, Decimal("150"), day="16")  # second run, same month, next day
    _seed(2, Decimal("400"))
    _seed(1, Decimal("500"))
    _seed(0, Decimal("600"))
    return client_user


# --- Positive: 6-month window matches a hand-computed running cumulative ----------


def test_portfolio_history_six_month_window_matches_hand_computed_cumulative(
    session, eight_month_fixture
):
    client_user = eight_month_fixture
    svc = ClientPortalService(session)
    points = svc.portfolio_history(client_user.id, 6)

    assert len(points) == 6
    assert all(isinstance(p, HistoryPointDTO) for p in points)

    expected_totals = [600.0, 600.0, 900.0, 1300.0, 1800.0, 2400.0]
    assert [p.total for p in points] == expected_totals
    assert [p.per_model.get("Alpha Model") for p in points] == expected_totals

    expected_months = [_month_token(b)[:4] + "-" + _month_token(b)[4:] for b in (5, 4, 3, 2, 1, 0)]
    assert [p.month for p in points] == expected_months


# --- Invariants: same-month collapse + empty-month carry-forward are embedded above,
# spelled out again here as standalone single-purpose assertions -------------------


def test_two_runs_in_the_same_month_collapse_into_one_point(session, eight_month_fixture):
    svc = ClientPortalService(session)
    points = svc.portfolio_history(eight_month_fixture.id, 6)
    same_month_point = points[2]  # back=3, the two-run month
    assert same_month_point.total == 900.0  # 600 (carried) + 150 + 150


def test_a_month_with_zero_runs_still_appears_carrying_the_prior_cumulative(
    session, eight_month_fixture
):
    svc = ClientPortalService(session)
    points = svc.portfolio_history(eight_month_fixture.id, 6)
    empty_month_point = points[1]  # back=4, no run seeded
    assert empty_month_point.total == points[0].total == 600.0


def test_first_point_cumulative_includes_runs_strictly_before_the_window(
    session, eight_month_fixture
):
    """total_before = 100 (back=7) + 200 (back=6) = 300, folded into the first
    in-window point's running total (300 + 300 from back=5 == 600)."""
    svc = ClientPortalService(session)
    points = svc.portfolio_history(eight_month_fixture.id, 6)
    assert points[0].total == 600.0


# --- Invariants: months=1 and months=24 both return exactly that many points -----


def test_months_equals_one_returns_exactly_one_point(session, eight_month_fixture):
    svc = ClientPortalService(session)
    points = svc.portfolio_history(eight_month_fixture.id, 1)
    assert len(points) == 1
    assert points[0].total == 2400.0  # cumulative of every seeded run


def test_months_equals_twenty_four_returns_exactly_twenty_four_points(session, eight_month_fixture):
    svc = ClientPortalService(session)
    points = svc.portfolio_history(eight_month_fixture.id, 24)
    assert len(points) == 24


def test_a_client_with_no_history_at_all_gets_flat_zero_points(session):
    client_user = make_client(session, name="Bare Client")
    svc = ClientPortalService(session)
    points = svc.portfolio_history(client_user.id, 3)
    assert len(points) == 3
    assert all(p.total == 0.0 for p in points)
    assert all(p.per_model == {} for p in points)


# --- Negative: months out of [1, 24] 422s at the route's own bound check ----------


@pytest.fixture
def scratch_app() -> FastAPI:
    fastapi_app = FastAPI()
    fastapi_app.include_router(client_portal_router, prefix="/api")
    return fastapi_app


@pytest.fixture
def client(scratch_app, db_factory):
    db = db_factory()
    client_user = make_client(db, name="Cathy Client")
    db.close()

    def _override_get_db():
        session = db_factory()
        try:
            yield session
        finally:
            session.close()

    scratch_app.dependency_overrides[get_db] = _override_get_db
    scratch_app.dependency_overrides[get_current_client_user] = lambda: client_user
    try:
        yield TestClient(scratch_app)
    finally:
        scratch_app.dependency_overrides.clear()


@pytest.mark.parametrize("months", [0, 25])
def test_portfolio_history_out_of_bounds_months_returns_422(client, months):
    resp = client.get(f"/api/client/portfolio/history?months={months}")
    assert resp.status_code == 422


def test_portfolio_history_in_bounds_months_returns_200(client):
    resp = client.get("/api/client/portfolio/history?months=6")
    assert resp.status_code == 200, resp.text
    assert len(resp.json()) == 6


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
