# Generated by test-gen (standard) from
# docs/implementations/018-client-portal-integration-be.md §BE-12.
# Regenerate: /test-gen standard.
#
# Ticket create/list/status + RM scoping (D-2, D-3, C-11, C-14).
#
# Pre-implementation note: app/libs/client_portal/{schemas,service,
# repository}.py do not exist yet -- every import below is expected to raise
# ImportError/ModuleNotFoundError at collection, not a test-gen bug.
#
# Seam mocks: none per §8.3.
#
# Run: .venv/Scripts/python.exe -m pytest -q tests/libs/client_portal/test_be12_tickets.py

from __future__ import annotations

import uuid

import pytest
from app.libs.client_portal.schemas import (
    RaiseTicketReq,
    RmTicketDTO,
    RmTicketStatusReq,
    TicketKind,
    TicketStatus,
)
from app.libs.client_portal.service import ClientPortalService
from fastapi import HTTPException
from pydantic import ValidationError

from app.models.users import AdminRole
from tests.libs.client_portal.conftest import make_admin, make_client, make_model, set_assigned_rm

# --- Positive: a valid ticket persists, snapshots assigned_rm_uid, and is RM-scoped --


def test_raise_allotment_ticket_persists_and_appears_only_for_its_assigned_rm(session):
    client_user = make_client(session, name="Cathy Client")
    rm_a = make_admin(session, AdminRole.RM, name="Ricky RM")
    rm_b = make_admin(session, AdminRole.RM, name="Robin RM")
    model = make_model(session, name="Alpha Model")
    set_assigned_rm(session, client_user, rm_a)

    svc = ClientPortalService(session)
    req = RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=model.id, message="Please allot more.")
    result = svc.create_ticket(client_user.id, req)
    assert result.kind == TicketKind.ALLOTMENT

    rm_a_tickets = svc.list_rm_tickets(rm_uid=rm_a.firebase_uid, role=AdminRole.RM)
    rm_b_tickets = svc.list_rm_tickets(rm_uid=rm_b.firebase_uid, role=AdminRole.RM)
    assert len(rm_a_tickets) == 1
    assert all(isinstance(t, RmTicketDTO) for t in rm_a_tickets)
    assert rm_a_tickets[0].client_id == client_user.id
    assert rm_b_tickets == []


def test_admin_sees_every_ticket_a_superset_of_any_single_rms_view(session):
    client_user = make_client(session, name="Cathy Client")
    rm_a = make_admin(session, AdminRole.RM, name="Ricky RM")
    admin_user = make_admin(session, AdminRole.ADMIN, name="Andy Admin")
    model = make_model(session, name="Alpha Model")
    set_assigned_rm(session, client_user, rm_a)

    svc = ClientPortalService(session)
    svc.create_ticket(
        client_user.id, RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=model.id, message="x")
    )

    rm_tickets = svc.list_rm_tickets(rm_uid=rm_a.firebase_uid, role=AdminRole.RM)
    admin_tickets = svc.list_rm_tickets(rm_uid=admin_user.firebase_uid, role=AdminRole.ADMIN)
    assert {t.ref for t in rm_tickets}.issubset({t.ref for t in admin_tickets})
    assert len(admin_tickets) >= len(rm_tickets)


# --- Positive: a status change stamps responded_by/responded_at ------------------


def test_set_rm_ticket_status_stamps_responder_and_timestamp(session):
    client_user = make_client(session, name="Cathy Client")
    rm = make_admin(session, AdminRole.RM, name="Ricky RM")
    model = make_model(session, name="Alpha Model")
    set_assigned_rm(session, client_user, rm)

    svc = ClientPortalService(session)
    created = svc.create_ticket(
        client_user.id, RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=model.id, message="x")
    )
    updated = svc.set_rm_ticket_status(
        created.ref,
        RmTicketStatusReq(status=TicketStatus.IN_PROGRESS, note="Looking into it"),
        rm_uid=rm.firebase_uid,
        role=AdminRole.RM,
    )
    assert updated.status == TicketStatus.IN_PROGRESS
    assert updated.responded_by == rm.firebase_uid
    assert updated.responded_at is not None
    assert updated.response_note == "Looking into it"


# --- Negative: the kind-conditional validator 422s at the wire boundary ----------


def test_allotment_ticket_without_model_id_raises_validation_error():
    with pytest.raises(ValidationError):
        RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=None, message="x")


def test_other_ticket_without_subject_raises_validation_error():
    with pytest.raises(ValidationError):
        RaiseTicketReq(kind=TicketKind.OTHER, subject=None, message="x")


def test_other_ticket_with_model_id_present_raises_validation_error():
    with pytest.raises(ValidationError):
        RaiseTicketReq(
            kind=TicketKind.OTHER, subject="A question", model_id=uuid.uuid4(), message="x"
        )


# --- Negative: a status change on a terminal ticket 409s -------------------------


@pytest.mark.parametrize("terminal_status", [TicketStatus.RESOLVED, TicketStatus.DECLINED])
def test_status_change_on_a_terminal_ticket_409s(session, terminal_status):
    client_user = make_client(session, name="Cathy Client")
    rm = make_admin(session, AdminRole.RM, name="Ricky RM")
    model = make_model(session, name="Alpha Model")
    set_assigned_rm(session, client_user, rm)

    svc = ClientPortalService(session)
    created = svc.create_ticket(
        client_user.id, RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=model.id, message="x")
    )
    svc.set_rm_ticket_status(
        created.ref,
        RmTicketStatusReq(status=terminal_status),
        rm_uid=rm.firebase_uid,
        role=AdminRole.RM,
    )

    with pytest.raises(HTTPException) as exc_info:
        svc.set_rm_ticket_status(
            created.ref,
            RmTicketStatusReq(status=TicketStatus.IN_PROGRESS),
            rm_uid=rm.firebase_uid,
            role=AdminRole.RM,
        )
    assert exc_info.value.status_code == 409


# --- Negative: a non-owning, non-ADMIN RM fetching another RM's ticket 404s ------


def test_non_owning_rm_fetching_another_rms_ticket_gets_404(session):
    client_user = make_client(session, name="Cathy Client")
    owning_rm = make_admin(session, AdminRole.RM, name="Ricky RM")
    other_rm = make_admin(session, AdminRole.RM, name="Robin RM")
    model = make_model(session, name="Alpha Model")
    set_assigned_rm(session, client_user, owning_rm)

    svc = ClientPortalService(session)
    created = svc.create_ticket(
        client_user.id, RaiseTicketReq(kind=TicketKind.ALLOTMENT, model_id=model.id, message="x")
    )

    with pytest.raises(HTTPException) as exc_info:
        svc._require_rm_visible_ticket_dto(
            created.ref, rm_uid=other_rm.firebase_uid, role=AdminRole.RM
        )
    assert exc_info.value.status_code == 404


# --- Invariant: TicketStatus is exactly the frozen 5-member vocabulary -----------


def test_ticket_status_has_exactly_the_five_frozen_members():
    assert {s.value for s in TicketStatus} == {
        "new",
        "in_progress",
        "replied",
        "closed",
        "declined",
    }


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
