# Generated by test-gen (thorough) from
# docs/implementations/020-schema-format-cleanup-refactor-be.md §BE-15.
# Regenerate: /test-gen thorough.
#
# Entitlement check on client material download. Trust boundary (§8.4:
# thorough regardless of layer level) -- any authenticated client could
# previously download any model's marketing material, subscribed or not.
#
# Seam mocks: none per §8.3. `get_storage` is monkeypatched to a local
# double purely so a rejection can be proven to never touch it -- not a
# cross-layer seam.
#
# Run: .venv/Scripts/python.exe -m pytest -q \
#   tests/libs/client_portal/test_be15_material_entitlement.py

from __future__ import annotations

import io
import uuid
from decimal import Decimal
from unittest.mock import MagicMock

import pytest
from fastapi import HTTPException
from fastapi.testclient import TestClient

from app.core.database import get_db
from app.libs.auth.deps import get_current_client_user
from app.libs.client_portal.repository import ClientPortalRepository
from app.libs.client_portal.service import ClientPortalService
from app.main import app
from tests.libs.client_portal.conftest import make_client, make_model, make_model_material, make_subscription

_NOT_FOUND_MSG = "No material uploaded for this model"


class _SpyStorage:
    """FileStorage double whose .open() records every call -- proves a
    rejected request never reaches the filesystem (§8.3 invariant)."""

    def __init__(self) -> None:
        self.open_calls: list[str] = []

    def open(self, storage_key: str):
        self.open_calls.append(storage_key)
        return io.BytesIO(b"material bytes")


@pytest.fixture
def spy_storage(monkeypatch):
    storage = _SpyStorage()
    monkeypatch.setattr("app.libs.client_portal.service.get_storage", lambda bucket: storage)
    return storage


# --- Positive: a subscribed client's download is unchanged ------------------------


def test_subscribed_client_receives_the_stream_unchanged(session, spy_storage):
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_subscription(session, client_user, model)
    material = make_model_material(session, model, storage_key="marketing/alpha-v0.pdf")

    svc = ClientPortalService(session)
    stream, filename, content_type = svc.model_material_stream(model.id, user_id=client_user.id)

    assert filename == material.filename
    assert content_type == material.content_type
    assert stream.read() == b"material bytes"
    assert spy_storage.open_calls == ["marketing/alpha-v0.pdf"]


# --- Negative: unsubscribed client gets the SAME 404 as an unknown model ----------


def test_unsubscribed_client_gets_404_identical_to_unknown_model(session, spy_storage):
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_model_material(session, model, storage_key="marketing/alpha-v0.pdf")  # material EXISTS

    svc = ClientPortalService(session)

    with pytest.raises(HTTPException) as unsubscribed_exc:
        svc.model_material_stream(model.id, user_id=client_user.id)

    with pytest.raises(HTTPException) as unknown_model_exc:
        svc.model_material_stream(uuid.uuid4(), user_id=client_user.id)

    assert unsubscribed_exc.value.status_code == 404
    assert unknown_model_exc.value.status_code == 404
    # Byte-identical bodies -- a future divergence that leaks model existence
    # to an unentitled caller must fail this assertion.
    assert unsubscribed_exc.value.detail == unknown_model_exc.value.detail == _NOT_FOUND_MSG
    assert spy_storage.open_calls == []


def test_client_subscribed_to_a_different_model_is_also_rejected(session, spy_storage):
    client_user = make_client(session, name="Cathy Client")
    subscribed_model = make_model(session, name="Subscribed Model")
    other_model = make_model(session, name="Other Model")
    make_subscription(session, client_user, subscribed_model)
    make_model_material(session, other_model, storage_key="marketing/other-v0.pdf")

    svc = ClientPortalService(session)
    with pytest.raises(HTTPException) as exc_info:
        svc.model_material_stream(other_model.id, user_id=client_user.id)

    assert exc_info.value.status_code == 404
    assert exc_info.value.detail == _NOT_FOUND_MSG
    assert spy_storage.open_calls == []


@pytest.mark.parametrize(
    "seed_material",
    [True, False],
    ids=["material-exists-but-unentitled", "material-does-not-exist"],
)
def test_no_403_is_ever_emitted_on_rejection(session, spy_storage, seed_material):
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    if seed_material:
        make_model_material(session, model, storage_key="marketing/alpha-v0.pdf")

    svc = ClientPortalService(session)
    with pytest.raises(HTTPException) as exc_info:
        svc.model_material_stream(model.id, user_id=client_user.id)

    assert exc_info.value.status_code != 403
    assert exc_info.value.status_code == 404


# --- Invariant: latest_material is never called and no filesystem read happens ---


def test_latest_material_not_called_and_no_filesystem_read_on_rejection(
    session, spy_storage, monkeypatch
):
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_model_material(session, model, storage_key="marketing/alpha-v0.pdf")

    spy_latest_material = MagicMock(wraps=ClientPortalRepository.latest_material)
    monkeypatch.setattr(ClientPortalRepository, "latest_material", spy_latest_material)

    svc = ClientPortalService(session)
    with pytest.raises(HTTPException):
        svc.model_material_stream(model.id, user_id=client_user.id)

    spy_latest_material.assert_not_called()
    assert spy_storage.open_calls == []


def test_fully_redeemed_client_loses_material_access(session, spy_storage):
    """A full redemption floors client_subscriptions.multiplier at 0 rather
    than deleting the row (permanent client_ib_accounts anchor) -- entitlement
    must not survive that as a plain row-existence check would let it."""
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_subscription(session, client_user, model, multiplier=Decimal("0"))
    make_model_material(session, model, storage_key="marketing/alpha-v0.pdf")

    svc = ClientPortalService(session)
    with pytest.raises(HTTPException) as exc_info:
        svc.model_material_stream(model.id, user_id=client_user.id)

    assert exc_info.value.status_code == 404
    assert exc_info.value.detail == _NOT_FOUND_MSG
    assert spy_storage.open_calls == []


def test_the_subscription_lookup_uses_user_id_model_id_order(session):
    """has_subscription(user_id, model_id) -- proves the two positional
    arguments are not silently swappable (the PK order the impl doc pins)."""
    client_user = make_client(session, name="Cathy Client")
    model = make_model(session, name="Alpha Model")
    make_subscription(session, client_user, model)

    repo = ClientPortalRepository(session)
    assert repo.has_subscription(client_user.id, model.id) is True
    # Swapped args -- two random-looking UUIDs that don't collide with any
    # real row -- must not accidentally match.
    assert repo.has_subscription(model.id, client_user.id) is False  # type: ignore[arg-type]


# --- Router: dependency wiring passes the real caller's id, not a stub -----------


@pytest.fixture
def client(session, db_factory):
    def _override_get_db():
        db = db_factory()
        try:
            yield db
        finally:
            db.close()

    def _make(stub_user):
        app.dependency_overrides[get_db] = _override_get_db
        app.dependency_overrides[get_current_client_user] = lambda: stub_user
        return TestClient(app)

    yield _make
    app.dependency_overrides.clear()


def test_router_download_succeeds_for_a_subscribed_client(session, db_factory, client, spy_storage):
    db = db_factory()
    client_user = make_client(db, name="Cathy Client")
    model = make_model(db, name="Alpha Model")
    make_subscription(db, client_user, model)
    make_model_material(db, model, storage_key="marketing/alpha-v0.pdf")

    http = client(client_user)
    resp = http.get(f"/client/models/{model.id}/material")

    assert resp.status_code == 200
    assert resp.content == b"material bytes"


def test_router_download_404s_identically_for_an_unsubscribed_client(
    session, db_factory, client, spy_storage
):
    db = db_factory()
    client_user = make_client(db, name="Cathy Client")
    model = make_model(db, name="Alpha Model")
    make_model_material(db, model, storage_key="marketing/alpha-v0.pdf")

    http = client(client_user)

    unsubscribed_resp = http.get(f"/client/models/{model.id}/material")
    unknown_model_resp = http.get(f"/client/models/{uuid.uuid4()}/material")

    assert unsubscribed_resp.status_code == 404
    assert unknown_model_resp.status_code == 404
    assert unsubscribed_resp.status_code != 403
    assert unsubscribed_resp.json() == unknown_model_resp.json()
    assert spy_storage.open_calls == []


if __name__ == "__main__":
    import sys

    sys.exit(pytest.main([__file__, "-q"]))
