// Generated by test-gen (standard) from docs/implementations/016-allotment-redemption-integration-fe.md §FE-2. Regenerate: /test-gen standard.
//
// NOTE on pre-implementation state: FE-2 adds submitAllotment/submitRedemption
// to server/rm/index.ts and app/(roles)/rm/model-subscription/actions.ts —
// neither export exists yet, so this file's imports fail to resolve until
// the feature agent lands them. That module-resolution failure is the
// correct/expected pre-implementation signal for this unit.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/server/rm", async (importOriginal) => ({
    ...(await importOriginal<typeof import("@/server/rm")>()),
  submitAllotment: vi.fn(),
  submitRedemption: vi.fn(),
}));

import * as serverRm from "@/server/rm";
import { submitAllotment, submitRedemption } from "@/app/(roles)/rm/model-subscription/actions";
import type { AllotRdmptDTO } from "@/lib/onboarding/types";

const FAKE_DTO: AllotRdmptDTO = {
  id: "a1", reference: "REF-1", model_id: "m1", model_name: "Model A", units: 2, amount: 200_000,
  kind: "allotment", status: "pending", note: null, agg_before: 0, agg_after: 2,
  expected_cash_in: "2026-08-01", rm: "Jane", created_at: "2026-07-22T00:00:00Z", acknowledged_at: null,
};

beforeEach(() => vi.clearAllMocks());

describe("FE-2 submitAllotment action wrapper", () => {
  it("forwards the request to server/rm.submitAllotment verbatim and returns its success result", async () => {
    const ok = { success: true, data: FAKE_DTO } as const;
    vi.mocked(serverRm.submitAllotment).mockResolvedValue(ok as never);
    const req = { client_id: "c-1", model_id: "m-1", multiplier: 2, expected_cash_in: "2026-08-01" };
    const result = await submitAllotment(req);
    expect(serverRm.submitAllotment).toHaveBeenCalledWith(req);
    expect(result).toEqual(ok);
  });

  it("never mutates its input req object", async () => {
    vi.mocked(serverRm.submitAllotment).mockResolvedValue({ success: true, data: FAKE_DTO } as never);
    const req = { client_id: "c-1", model_id: "m-1", multiplier: 2, expected_cash_in: "2026-08-01" };
    const snapshot = { ...req };
    await submitAllotment(req);
    expect(req).toEqual(snapshot);
  });

  it("a thrown error is funneled through toErrorResult, never propagated", async () => {
    vi.mocked(serverRm.submitAllotment).mockRejectedValue(new Error("network down"));
    const result = await submitAllotment({ client_id: "c-1", model_id: "m-1", multiplier: 1, expected_cash_in: null });
    expect(result).toEqual({ success: false, error: "network down", code: "ACTION_ERROR" });
  });
});

describe("FE-2 submitRedemption action wrapper", () => {
  it("forwards the request to server/rm.submitRedemption verbatim and returns its success result", async () => {
    const dto = { ...FAKE_DTO, kind: "redemption" as const, status: "awaiting_pc" as const };
    const ok = { success: true, data: dto } as const;
    vi.mocked(serverRm.submitRedemption).mockResolvedValue(ok as never);
    const req = { client_id: "c-1", model_id: "m-1", multiplier: 1, expected_cash_out: "2026-08-15", emergent: false };
    const result = await submitRedemption(req);
    expect(serverRm.submitRedemption).toHaveBeenCalledWith(req);
    expect(result).toEqual(ok);
  });

  it("a thrown error is funneled through toErrorResult, never propagated", async () => {
    vi.mocked(serverRm.submitRedemption).mockRejectedValue(new Error("500 upstream"));
    const result = await submitRedemption({ client_id: "c-1", model_id: "m-1", multiplier: 0, expected_cash_out: null, emergent: true });
    expect(result).toEqual({ success: false, error: "500 upstream", code: "ACTION_ERROR" });
  });
});
